### ISSUE TITLE
hamming: make classes and methods package private in reference and starter implementations

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/java#1049]
All the public class and method [access modifiers](https://docs.oracle.com/javase/tutorial/java/javaOO/accesscontrol.html) in the [hamming reference solution](https://github.com/exercism/java/blob/master/exercises/hamming/.meta/src/reference/java/) and [hamming starter implementation](https://github.com/exercism/java/tree/master/exercises/hamming/src/main/java) can be changed to package private (which is the default therefore the access modifier can be left out). For example, in Hamming.java, `public class Hamming {` should be changed to `class Hamming {`.

We do this since it's best practice to restrict access to a class and its methods as much as possible (see our [POLICIES doc](https://github.com/exercism/java/blob/master/POLICIES.md#adhere-to-best-practices) for more information).

**Comment by FridaTveit** [comment]
This has been fixed for the hamming reference solution in PR #1071. Thanks @t0dd :)

The hamming starter implementation still needs fixing :)

**Comment by sjwarner-bp** [comment]
Is this now resolved (and can be closed) thanks to #1083 ?

**Comment by FridaTveit** [comment]
No, the starter implementation still needs fixing :)
