### ISSUE TITLE
reverse-string: choose appropriate unlocked_by exercise

### ISSUE THREAD

**Issue by Smarticles101** [exercism/java#1054]
Choose and exercise for reverse-string to be `unlocked_by` there is previous discussion in #1044 :)

**Comment by sjwarner-bp** [comment]
I think there aren't too many options here as it is a `"difficulty": 1` exercise, and I don't think it would make too much sense for it to be unlocked by something harder!

My vote goes for `two-fer` - though I'd be interested in hearing what others have to say! :slightly_smiling_face:

**Comment by bmkiefer** [comment]
Yeah, I also agree on using `two-fer` given there isn't any exercises in the unimplemented or implemented exercises that are more simple than `reverse-string`. Also could entertain putting the same information about TDD that is in `two-fer` in this exercise if we don't want to have it hidden behind unlock, but I am voting for unlock behind `two-fer`.

**Comment by sjwarner-bp** [comment]
I like the idea of having some info about TDD in early exercises - I imagine some people might need a little reminder, especially if they are starting out more slowly.

**Comment by FridaTveit** [comment]
I agree that it should be unlocked by `two-fer`. We have info about TDD in `two-fer` so if it's unlocked by that then that should probably be fine. Users can refer back to the information in `two-fer` if they need to. But I would be happy to duplicate the information in `reverse-string` if people think that would be useful :)

**Comment by Smarticles101** [comment]
Sounds good, I like `two-fer` as well as the option

**Comment by stkent** [comment]
I like `two-fer` as the pick. Additionally, I'd prefer to avoid this duplication:

> But I would be happy to duplicate the information in `reverse-string` if people think that would be useful :)
