### ISSUE TITLE
matrix: make classes and methods package private in reference solution

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/java#1080]
All the public class and method [access modifiers](https://docs.oracle.com/javase/tutorial/java/javaOO/accesscontrol.html) in the [matrix reference solution](https://github.com/exercism/java/blob/master/exercises/matrix/.meta/src/reference/java/) can be changed to package private (which is the default therefore the access modifier can be left out). For example, in Matrix.java, `public class Matrix {` should be changed to `class Matrix {`.

We do this since it's best practice to restrict access to a class and its methods as much as possible (see our [POLICIES doc](https://github.com/exercism/java/blob/master/POLICIES.md#adhere-to-best-practices) for more information).

**Comment by c-thornton** [comment]
I was thinking about taking care of this for you really quick. Do you want just the class to be changed or do you want the methods within that class also changed as well? If you want the methods as well I can knock this out in a few minutes for the Matrix.java in matrix/.meta/src/reference/java folder and the MatrixTest.java file in the matrix/src.test/java folder as well. JLet me know which way you want it and I can take care of it.

**Comment by stkent** [comment]
I believe JUnit tests require `public` methods; this issue applies to the reference solution (and, if provided, starter implementation) for the exercise only :)

**Comment by c-thornton** [comment]
Got it. Thanks for the input @stkent, just starting out contributing on Open Source so I want to make sure I do it right. I will modify this tomorrow and get a pull request submitted for it.

**Comment by pratikpalashikar** [comment]
@sjwarner-bp @c-thornton  I was working on this issue and I have submitted a pull request for this issue.

**Comment by c-thornton** [comment]
@pratikpalashikar Thanks for letting me know you made a pull request on this one. I will not worry about it then.

**Comment by FridaTveit** [comment]
Fixed in PR #1083. Thanks @pratikpalashikar :)
