### ISSUE TITLE
meetup: make classes and methods package private in reference solution and associated enums

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/java#1081]
All the public class and method [access modifiers](https://docs.oracle.com/javase/tutorial/java/javaOO/accesscontrol.html) in the [meetup reference solution](https://github.com/exercism/java/blob/master/exercises/meetup/.meta/src/reference/java/) can be changed to package private (which is the default therefore the access modifier can be left out). For example, in Meetup.java, `public class Meetup {` should be changed to `class Meetup {`. The same principle can be applied to MeetupSchedule.java in both [reference](https://github.com/exercism/java/blob/master/exercises/meetup/.meta/src/reference/java/) and [starter](https://github.com/exercism/java/tree/master/exercises/meetup/src/main/java) solutions.

We do this since it's best practice to restrict access to a class and its methods as much as possible (see our [POLICIES doc](https://github.com/exercism/java/blob/master/POLICIES.md#adhere-to-best-practices) for more information).

**Comment by c-thornton** [comment]
Suggest closing this issue as it was resolved in merged pull request #1082.

**Comment by sjwarner-bp** [comment]
Thanks for spotting this @c-thornton - knew I was forgetting something!

It might be useful to know that if you put 'fixes' and then an issue number, it will auto-close the issue upon merge! Details [here](https://help.github.com/articles/closing-issues-using-keywords/) :slightly_smiling_face:

**Comment by sjwarner-bp** [comment]
Closed as per #1082

**Comment by c-thornton** [comment]
Awesome, thanks for the info @sjwarner-bp. I will keep that in mind for future issues I work on.
