### ISSUE TITLE
parallel-letter-frequency: illegal character error for test file

### ISSUE THREAD

**Issue by wolf99** [exercism/java#1104]
Testing a basic stub implementation of this exercise (on Windows with VS Code) results in three errors.

```java
// Stub implementation - first step of TDD
import java.util.Map;

class ParallelLetterFrequency {
    ParallelLetterFrequency(String input) {
        throw new UnsupportedOperationException();
    }

    Map<Integer, Integer> letterCounts() {
        throw new UnsupportedOperationException();
    }
}
```

```bash
# Errors from build output
ParallelLetterFrequencyTest.java:146: error: unclosed character literal
        assertEquals(new Integer(2), p.letterCounts().get((int) '├╝'));
                                                                ^
ParallelLetterFrequencyTest.java:146: error: illegal character: '\u00bc'
        assertEquals(new Integer(2), p.letterCounts().get((int) '├╝'));
                                                                  ^
ParallelLetterFrequencyTest.java:146: error: unclosed character literal
        assertEquals(new Integer(2), p.letterCounts().get((int) '├╝'));
```

Changing the literal at line 146 of the test file from `'ü'` to `'\u00FC'` fixes this - not sure if that is cross platform or not though? If it is, this issue is probably a candidate for <kbd>[good-first-patch]()</kbd>
```java
        assertEquals(new Integer(2), p.letterCounts().get((int) '\u00FC')); //Unicode ü
```

**Comment by stkent** [comment]
Most exercises with canonical data have stripped more exotic characters over time unless they are absolutely core to the exercise. Let's just remove them from the Java tests, and then maybe propose canonical data for this exercise as a stretch goal :)

**Comment by sjwarner-bp** [comment]
I'm looking to pick this one up next - I'd like to just double check with others first. Just to confirm, removing 'OdeAnDieFreude' and 'Wilhelmus' will amend this issue and not reduce test coverage too much?

Or do we want to look in to adding a couple of tests to compensate here too? I think the only real difference if we didn't do this would be that we're missing a test that appends several strings (but I am not sure that increases test coverage anyway).

Let me know - I'll probably open a PR with a suggestion in the morning :slightly_smiling_face:
