### ISSUE TITLE
two-fer: make classes and methods package private in reference and starter implementations

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/java#1108]
All the public class and method [access modifiers](https://docs.oracle.com/javase/tutorial/java/javaOO/accesscontrol.html) in the [two-fer reference solution](https://github.com/exercism/java/blob/master/exercises/two-fer/.meta/src/reference/java/) and [two-fer starter implementation](https://github.com/exercism/java/tree/master/exercises/two-fer/src/main/java) can be changed to package private (which is the default therefore the access modifier can be left out). For example, in Twofer.java, `public class Twofer {` should be changed to `class Twofer {`.

We do this since it's best practice to restrict access to a class and its methods as much as possible (see our [POLICIES doc](https://github.com/exercism/java/blob/master/POLICIES.md#adhere-to-best-practices) for more information).

**Comment by rdavid1099** [comment]
Opened PR fixing this issue.

**Comment by sjwarner-bp** [comment]
Closed via #1111
