### ISSUE TITLE
Version numbers of tests

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/java#1116]
Upon running the `canonical_data_check.sh` script, I've noticed that a large number of exercises either do not have `./meta/version` files, or the exercises are out of date.

I think this could make a good number of new issues (though possibly not `good-first-patch` if updates to test suites require re-implementing the reference solution), and in my opinion it would be good to try and keep these up to date.

The output from the script currently is:

```
$ scripts/canonical_data_check.sh -t . -s ../problem-specifications/
hello-world: needs update or version file (v1.0.0).
two-fer: needs update or version file (v1.1.0).
rna-transcription: needs update (v1.0.1 -> v1.1.0).
pangram: needs update (v1.1.0 -> v1.3.0).
hamming: needs update (v1.1.0 -> v2.0.1).
gigasecond: needs update or version file (v1.0.0).
space-age: needs update or version file (v1.0.0).
acronym: needs update (v1.1.0 -> v1.2.0).
raindrops: needs update or version file (v1.0.0).
protein-translation: needs update (v1.0.0 -> v1.0.1).
proverb: needs update or version file (v1.0.0).
sum-of-multiples: needs update or version file (v1.1.0).
luhn: needs update or version file (v1.0.0).
largest-series-product: needs update or version file (v1.0.0).
sieve: needs update or version file (v1.0.0).
twelve-days: needs update or version file (v1.0.0).
rotational-cipher: needs update or version file (v1.1.0).
kindergarten-garden: needs update or version file (v1.0.0).
nth-prime: needs update or version file (v2.0.0).
isogram: needs update or version file (v1.2.0).
pig-latin: needs update or version file (v1.1.0).
phone-number: needs update or version file (v1.2.0).
nucleotide-count: needs update or version file (v1.2.0).
word-count: needs update or version file (v1.0.0).
run-length-encoding: needs update or version file (v1.0.0).
prime-factors: needs update or version file (v1.0.0).
allergies: needs update or version file (v1.1.0).
bob: needs update or version file (v1.1.0).
pascals-triangle: needs update (v1.0.0 -> v1.2.0).
atbash-cipher: needs update or version file (v1.0.0).
roman-numerals: needs update or version file (v1.0.0).
transpose: needs update or version file (v1.1.0).
house: needs update or version file (v2.0.0).
food-chain: needs update or version file (v2.0.0).
beer-song: needs update or version file (v2.1.0).
etl: needs update or version file (v1.0.0).
robot-simulator: needs update (v1.0.0 -> v2.0.0).
binary-search: needs update or version file (v1.1.0).
wordy: needs update or version file (v1.0.0).
all-your-base: needs update (v1.1.0 -> v2.1.0).
bowling: needs update or version file (v1.0.1).
tournament: needs update or version file (v1.3.0).
anagram: needs update or version file (v1.1.0).
word-search: needs update (v1.0.0 -> v1.1.0).
meetup: needs update or version file (v1.0.0).
crypto-square: needs update or version file (v3.1.0).
poker: needs update or version file (v1.0.0).
circular-buffer: needs update or version file (v1.0.1).
book-store: needs update or version file (v1.2.0).
list-ops: needs update (v1.0.0 -> v2.0.0).
palindrome-products: needs update or version file (v1.0.0).
forth: needs update (v1.2.0 -> v1.4.0).
custom-set: needs update (v1.0.1 -> v1.1.0).
```

@exercism/java let me know what you guys think, and we can begin to action this 👍

**Comment by FridaTveit** [comment]
This sounds like a great plan! I think you're right that the ones requiring change shouldn't be good first patch issues. So we can either:
- Open them all as normal issues (or possibly one issue with a ticklist in for each exercise that needs updating). If someone looks into doing one of them and finds it just requires adding a version file they could then change the issue to a good first patch.
- Or look through the exercises output from the script and find out which ones only require a version file. For those, open good first patch issues. For the others open normal issues (or one issue wih a ticklist).

I think either would be fine. We've got quite a few good first patch issues right now (12 I think) so we don't desperately need more but it wouldn't hurt to have a few more :) What do you think?

**Comment by sjwarner-bp** [comment]
I like the sound of the second option 🙂 

It never hurts to have a few more good first patch issues, plus as they're so small they may all get picked up very quickly (and by the same person). I agree the others can be opened as normal other issues 🙂

**Comment by FridaTveit** [comment]
Great, I'll start looking through them and opening issues :)

**Comment by sjwarner-bp** [comment]
Thanks @FridaTveit - I might try a couple of these and see exactly what's involved for a fix 🙂

**Comment by FridaTveit** [comment]
I've made issues for all of the exercises that need updating :) Are you happy closing this issue now @sjwarner-bp since we've got other issues tracking it? Or do you think it should stay open until those other issues are closed?

**Comment by sjwarner-bp** [comment]
I think we won't be forgetting it any time soon with all of those issues! 😂 I'm happy to close this one now ☺️ Thanks for all that work Frida!
