### ISSUE TITLE
accumulate: Improve naming

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [exercism/java#1117]
The term `accumulate` does not seem to reflect the problem statement correctly (see what this term means in the context of `Stream.reduce` or `Stream.collect` methods: https://docs.oracle.com/javase/tutorial/collections/streams/reduction.html). 

We can perhaps rename this exercise to `map` instead since it connotes the idea of converting an object to something else.

**Comment by sjwarner-bp** [comment]
Hi @Zhiyuan-Amos - thanks for the suggestion!

I think that the [problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/accumulate) repo would be the best place to suggest this, as this is where the slug names are determined 🙂
