### ISSUE TITLE
exercises: Simplify model answers

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [exercism/java#1119]
1. `Accumulate` - If we expect end-users to be familiar with Java 8, then we can utilize `Stream` to simplify the model answer. Same goes for `Anagram#match`.

1. `Acronym` - `generateAcronym` uses `Pattern` and `Matcher` classes to split the strings in order to generate the acronym. We can simplify it by using `String.split("\W")`

1. `Anagram` - `canonicalize` converts the input `String` into a `char[]`. This step is unnecessary.

1. `Atbash` - `stripInvalidCharacters` can be simplified to be something like `input.replaceAll("\W", "")`

I can take a look at other answers and attempt to simplify them. Would love to work on this if possible! :)

**Comment by FridaTveit** [comment]
Thanks for raising this @Zhiyuan-Amos :)

1. `Accumulate` is deprecated meaning it's no longer available to users. So there's no need to simplify that one :)

2. I think that might cause problems for words with punctuation? But feel free to try it and open a PR for it if it works :)

3. It converts the input string to a `char[]` to sort the characters. That way you can compare the sorted array of the characters of two strings to see if one is an anagram of the other. Does that make sense? I think that's an okay approach but feel free to open a PR if you have a different suggestion :)

4. Yes, I think that would be a good simplification, feel free to open a PR :)

In general, as I mentioned on issue #1118, these reference solutions are not model answers. So you don't have to worry about what we expect of end-users, they shouldn't see this code :) We do want it to be good code however, so feel free to suggest improvements. You can do this either by opening issues or by opening PRs to fix it yourself. Either is fine, but it would be great if you could only deal with one problem (e.g. one exercise) in each issue or each PR. That makes it easier to review and merge PRs and easier to close issues :)
