### ISSUE TITLE
two-fer: update tests

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1121]
The last test in the [`two-fer` tests](https://github.com/exercism/java/blob/master/exercises/two-fer/src/test/java/TwoferTest.java) can be removed since it's no longer in the [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/two-fer/canonical-data.json).

Please also create a file at `exercises/two-fer/.meta/version` specifying the canonical data version which can be found at the top of [the canonical data file for that exercise](https://github.com/exercism/problem-specifications/blob/master/exercises/two-fer/canonical-data.json).

**Comment by jssander** [comment]
I would like to try and do this.

**Comment by jssander** [comment]
Btw, this is my first contribution. Should I comment it out or just simply delete it?

**Comment by sjwarner-bp** [comment]
Hi! Please delete the test that isn't in the canonical data, that way the file will be very clear in what it is testing 🙂

**Comment by jssander** [comment]
I deleted the test and added the version file. Do I submit a pull request now?

**Comment by Kyle-P** [comment]
Hi @jssander! You should be able to create a pull request by navigating to https://github.com/exercism/java. Once there, there should be an option near the top of the file listings to "create a pull request" with the commits you've added to your new branch. After clicking on that, you should be able to write a description of the pull request, what it contains, and what issue it references by using something such as "closes #1121."

**Comment by jssander** [comment]
I submitted a pull request.

**Comment by sjwarner-bp** [comment]
Thanks for that @jssander - I'll take a look over it :slightly_frowning_face:
