### ISSUE TITLE
proverb: add version file

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1130]
Each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. Please create a file at `exercises/proverb/.meta/version` specifying the canonical data version which can be found at the top of [the canonical data file for that exercise](https://github.com/exercism/problem-specifications/blob/master/exercises/proverb/canonical-data.json).

**Comment by hgvanpariya** [comment]
Hi @sjwarner-bp , @FridaTveit ,

Please provide your review comments.

**Comment by sjwarner-bp** [comment]
Closed via #1256
