### ISSUE TITLE
sum-of-multiples: add version file

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1131]
Each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. Please create a file at `exercises/sum-of-multiples/.meta/version` specifying the canonical data version which can be found at the top of [the canonical data file for that exercise](https://github.com/exercism/problem-specifications/blob/master/exercises/sum-of-multiples/canonical-data.json).

**Comment by hgvanpariya** [comment]
@FridaTveit : https://github.com/exercism/java/pull/1251

Please provide your suggestion. Is it what expected ?

**Comment by sjwarner-bp** [comment]
Closed via #1251
