### ISSUE TITLE
twelve-days: update tests and add version file

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1135]
The twelve-days tests should be updated to exactly match the canonical data. Also a version file should be added to match the canonical data version.

**Comment by Kyle-P** [comment]
I'll take care of this one :)

**Comment by Kyle-P** [comment]
Based on the canonical data, should which is correct?

String expectedVerseThree = "On the third day of Christmas my true love gave to me, " + "three French Hens, " +
                "two Turtle Doves, " + "and a Partridge in a Pear Tree.\n";

OR

String expectedVerseThree = "On the third day of Christmas my true love gave to me, three French Hens, " +
                "two Turtle Doves, " + "and a Partridge in a Pear Tree.\n";


Not sure if each comma ends a String. Thank you!

**Comment by FridaTveit** [comment]
Those are equivalent. The only reason we split up the strings is to keep each line shorter than 120 characters. It doesn't affect the output of the test at all 🙂 Does that make sense?

**Comment by Kyle-P** [comment]
Yes. I was just confused why certain strings were being constructed differently. Thank you!

**Comment by FridaTveit** [comment]
No problem 🙂
