### ISSUE TITLE
nth-prime: add version file

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1138]
Each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. Please create a file at `exercises/nth-prime/.meta/version` specifying the canonical data version which can be found at the top of [the canonical data file for that exercise](https://github.com/exercism/problem-specifications/blob/master/exercises/nth-prime/canonical-data.json).

**Comment by Kyle-P** [comment]
Should the file just contain a statement of which version it is? For example, would I just create a file stating that this is Version 2.0.0? Thank you!
