### ISSUE TITLE
pig-latin: update tests and add version file

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1140]
The pig-latin tests should be updated to exactly match the canonical data. Also a version file should be added to match the canonical data version.

**Comment by Kyle-P** [comment]
I'll tackle this one

**Comment by sjwarner-bp** [comment]
Good luck! I have a personal vendetta against the pig-latin exercise...

This one might need the example tweaking too, if memory serves! :slightly_smiling_face:

**Comment by Kyle-P** [comment]
What is the point of the constructor:
`    public PigLatinTranslatorTest(String englishPhrase, String pigLatinTranslation) {
        this.englishPhrase = englishPhrase;
        this.pigLatinTranslation = pigLatinTranslation;
    }`

in the test class?
