### ISSUE TITLE
nucleotide-count: update tests and add version file

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1142]
The nucleotide-count tests should be updated to exactly match the canonical data. Also a version file should be added to match the canonical data version.

**Comment by tshradheya** [comment]
I will take a stab at this one

**Comment by tshradheya** [comment]
Can I confirm that to fix this issue I need to write tests exactly as in `canonical-data.json` and remove the unnecessary tests?

**Comment by FridaTveit** [comment]
Yes, that's right. The test names and method names don't have to exactly match, but otherwise we want to follow the canonical data as closely as possible 🙂 Does that make sense?

**Comment by tshradheya** [comment]
So I can delete the already existing ones which arent present in canonical data?

**Comment by FridaTveit** [comment]
Yes 🙂

**Comment by FridaTveit** [comment]
Sometimes we have extra tests just for the Java track if there's some Java specific feature that we need to test. But in that case the test should have a comment on it explaining why we're diverging from the canonical data 🙂
