### ISSUE TITLE
run-length-encoding: add version file

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1144]
Each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. Please create a file at `exercises/run-length-encoding/.meta/version` specifying the canonical data version which can be found at the top of [the canonical data file for that exercise](https://github.com/exercism/problem-specifications/blob/master/exercises/run-length-encoding/canonical-data.json).

**Comment by Kyle-P** [comment]
Would you prefer to leave these types of issues open for newcomers because of the "Good first patches" policy? Thanks!

**Comment by sjwarner-bp** [comment]
Hi @Kyle-P - I think it is a bit of a grey area, though if you are comfortable submitting PRs for the other issues first, it's probably best to do that! They're a bit more meaty and have a little more challenge to them :slightly_smiling_face:

**Comment by Kyle-P** [comment]
Alright, I'll do that. Thanks @sjwarner-bp!
