### ISSUE TITLE
robot-simulator: update tests

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1157]
The robot-simulator tests should be updated to exactly match the canonical data. Also the version file should be updated to match the canonical data version.

**Comment by Kyle-P** [comment]
When updating tests, would you like us to go through the whole thing? Or is it okay if we just take care of a portion?

**Comment by sjwarner-bp** [comment]
I think the best thing to do is to update all tests for the relevant exercise in a single PR.

This means that we won't get confused as to which tests of the exercise have been updated and which parts have not been 🙂

**Comment by Kyle-P** [comment]
Alright, thanks @sjwarner-bp!

**Comment by Kyle-P** [comment]
@sjwarner-bp I updated the robot-simulator tests and created a PR for them. Some commits that I believe have been taken care of already showed up in the PR. Not sure why they're there. Is there a way to ignore them? Thanks!

**Comment by sjwarner-bp** [comment]
Hi @Kyle-P I can't be too sure why this is happening without cloning your repo and looking a little more closely, but my first impression is that you might have previously commited to the `master` branch of your fork before making the changes you wanted in this PR.

What you could do to fix this would be create a new branch, cherry-pick the desired commit(s) over to that new branch, and raise a PR from there.

If this isn't the case, I'll definitely have a closer look later :slightly_smiling_face:
