### ISSUE TITLE
Should we delete the @exercism/java-admin team?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/java#1166]
Stuart mentioned in passing that we have a java-admin team, and I'm not sure what we're using it for.

Has it been useful? If so, in what way? If not, should we delete it?

**Comment by FridaTveit** [comment]
I wasn't aware we had a java-admin team so I don't mind if we delete it :) What do you think @sjwarner-bp, @Smarticles101?

**Comment by sjwarner-bp** [comment]
Looks as though @FridaTveit is the only one in that team. I've only been using exercism/java for pinging people, as it seems to have a few of us in it :slightly_smiling_face: 

I'm not adverse to deleting it!

**Comment by FridaTveit** [comment]
I also wasn't aware I was in the team :P I've also been using exercism/java to ping people :)

**Comment by kytrinyx** [comment]
Sweet—killing that team now. Thanks :)
