### ISSUE TITLE
list-ops: update tests

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1174]
The list-ops tests should be updated to exactly match the canonical data. Also the version file should be updated to match the canonical data version.

**Comment by Kyle-P** [comment]
It looks like most test cases match the canonical data. Does this mean we should just remove the @Ignore lines? @FridaTveit @sjwarner-bp

**Comment by sjwarner-bp** [comment]
Hi @Kyle-P,

The tests need to match the canonical data exactly (no missing cases, and extra cases can be removed).

Only the first test should be without an `@ignore` - all others should be ignored.

**Comment by Kyle-P** [comment]
Thanks @sjwarner-bp! I'll go through make sure everything matches. Just out of interest, why is everything but the first `@ignored`?

**Comment by sjwarner-bp** [comment]
It's one of our [POLICIES](https://github.com/exercism/java/blob/master/POLICIES.md#ignore-noninitial-tests) here on the Java track.

The way the tests are ordered most often reflects adding in features or methods. By ignoring all tests, and enabling them as each test passes, users aren't overwhelmed and it feels a bit more like TDD 🙂

**Comment by Kyle-P** [comment]
Oh. I see. That makes a lot of sense and it's a great idea 👍
