### ISSUE TITLE
palindrome-products: update tests and add version file

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1175]
The palindrome-products tests should be updated to exactly match the canonical data. Also a version file should be added to match the canonical data version.

**Comment by sjwarner-bp** [comment]
Was inadvertently closed as I linked the wrong issue in #1200!

**Comment by jssander** [comment]
I would like to give this one a shot. However, I am unsure of how to do the four tests that are supposed to throw errors. Is there another exercise that does something similar which I could refer to?

**Comment by sjwarner-bp** [comment]
Hi @jssander - the [collatz test](https://github.com/exercism/java/blob/master/exercises/collatz-conjecture/src/test/java/CollatzCalculatorTest.java) is a good example of how to test for errors 🙂 

Hopefully this is what you were looking for!

**Comment by jssander** [comment]
Yes, thank you.

**Comment by jssander** [comment]
I have added a few tests, but would you also like me to also update the .meta solution to throw the proper exceptions with the provided messages? Or only change the tests? If you take a look I don't think the provided solution does this according to the canonical file.

**Comment by sjwarner-bp** [comment]
Yes please - make sure that the reference solution passes all the new tests!!

If the reference solution doesn't pass the tests, you'll know because the build will fail.

**Comment by jssander** [comment]
Ok. I added all the tests in the canonical file, updated the .meta solution to throw exceptions, and added the version file. Could you take a look at it before I submit a pull request?

Thank you.

**Comment by sjwarner-bp** [comment]
I'll have a quick look, but you are welcome to open a PR for it even if you think it might not be right - that gives all of the Java members a way to look at it and provides us with some nice tools to give you feedback :slightly_smiling_face:

**Comment by sjwarner-bp** [comment]
At a quick glance, I think it's looking pretty good so far!

There are a couple of lines that could be broken up that might help the code to read easier. For example, where you throw exceptions in the reference solution could be split over several lines.

I'd suggest opening a PR for better feedback though, as we'll get diffs etc :slightly_smiling_face:

**Comment by jssander** [comment]
Ok I submitted a PR. I think I threw the exceptions on the same line because that is how it is done in the collatz test which you gave me as an example.
