### ISSUE TITLE
Builds timing out

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1199]
We've had quite a few builds failing recently because of timeout issues (for example see PR #1194 and #1184). I don't think I've seen our builds failing with those errors before so I'm not sure what's causing it. There's a [travis support page](https://docs.travis-ci.com/user/common-build-problems/#My-builds-are-timing-out) with suggestions for what to do when builds fail because of timeouts. It looks like we might be able to add a retry parameter to avoid these issues. What do you think @exercism/java?

**Comment by FridaTveit** [comment]
Another build failed because it didn't receive any output and timed out:
```
$ export PATH=$JAVA_HOME/bin:$PATH
Setting up build cache
$ export CASHER_DIR=$HOME/.casher
31.79s$ Installing caching utilities
0.00s
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by sjwarner-bp** [comment]
I am not too sure what is causing these timeouts either.

In a previous issue we discussed getting master to build again, and changed a couple of settings in Travis, but I am not sure how that would increase build times (please feel free to correct me if I am wrong though 🙂).

If you think that adding the retry parameter might help us out, then I say we go for it, and if it causes issues we can always revert it!

**Comment by sjwarner-bp** [comment]
Master build failed [here](https://travis-ci.org/exercism/java/builds/325012469) too.

**Comment by sjwarner-bp** [comment]
Just noticed the [most recent build](https://travis-ci.org/exercism/java/builds/325357856) of master ran for 42 min 26 sec, about 15 minutes longer than pretty much any other build...

Not sure if it is related, or I am simply worrying too much!

**Comment by FridaTveit** [comment]
Another [strange build failure](https://travis-ci.org/exercism/java/jobs/325849620):
```
------------------------------------------------------------
Gradle 4.0.1
------------------------------------------------------------
Build time:   2017-07-07 14:02:41 UTC
Revision:     38e5dc0f772daecca1d2681885d3d85414eb6826
Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_151 (Oracle Corporation 25.151-b12)
OS:           Linux 4.9.6-040906-generic amd64
>>> Running configlet...
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by FridaTveit** [comment]
It had some connection errors earlier in the output as well:
```
W: The repository 'https://packagecloud.io/computology/apt-backport/ubuntu trusty Release' does not have a Release file.
W: The repository 'https://packagecloud.io/github/git-lfs/ubuntu trusty Release' does not have a Release file.
W: The repository 'https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu trusty Release' does not have a Release file.
W: Failed to fetch http://www.apache.org/dist/cassandra/debian/dists/39x/InRelease  Unexpected type excepted 21 != 5
W: Failed to fetch http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/InRelease  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
W: Failed to fetch http://ppa.launchpad.net/git-core/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://dl.google.com/linux/chrome/deb/dists/stable/InRelease  Could not connect to dl.google.com:80 (172.217.13.238), connection timed out
W: Failed to fetch http://repo.mongodb.org/apt/ubuntu/dists/trusty/mongodb-org/3.4/InRelease  Could not connect to repo.mongodb.org:80 (52.84.122.216), connection timed out
W: Failed to fetch http://ppa.launchpad.net/openjdk-r/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/pollinate/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/webupd8team/java/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/main/binary-amd64/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/main/binary-i386/Packages  Unable to connect to ppa.launchpad.net:http:
W: Some index files failed to download. They have been ignored, or old ones used instead
```

**Comment by sjwarner-bp** [comment]
That is strange - if there are connection errors as well as timeouts, will the retry flag suggested above still be of use?

**Comment by FridaTveit** [comment]
Not sure... It seems strange that the build is suddenly failing relatively often but nearly always in a different place. The only recent change that I can think of that has anything to do with the build is turning build branch updates on. We could try turning that off again and see if that changes it at all?

**Comment by sjwarner-bp** [comment]
That is the only thing that has recently failed...

I'll go back in and flick the switches if you think that could help? If I remember correctly, 'Build branch updates' was off and 'Build pull request updates' was on?

**Comment by FridaTveit** [comment]
Yup, I think so 🙂 It doesn't seem like that should have caused any problems, but I can't think of anything else that could be causing these seemingly random failures...

**Comment by sjwarner-bp** [comment]
Ok, I've put it back to how it was before 🙂

**Comment by sjwarner-bp** [comment]
There were just some similar issues on the bash track's master build...

```
W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/InRelease  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
W: Failed to fetch http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/git-core/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://dl.google.com/linux/chrome/deb/dists/stable/InRelease  Could not connect to dl.google.com:80 (172.217.12.238), connection timed out
W: Failed to fetch http://toolbelt.heroku.com/ubuntu/./InRelease  Could not connect to toolbelt.heroku.com:80 (54.225.166.120), connection timed out [IP: 54.225.166.120 80]
W: Failed to fetch http://repo.mongodb.org/apt/ubuntu/dists/trusty/mongodb-org/3.4/InRelease  Could not connect to repo.mongodb.org:80 (54.230.194.100), connection timed out
W: Failed to fetch http://ppa.launchpad.net/openjdk-r/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/pollinate/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/webupd8team/java/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by FridaTveit** [comment]
Strange....

**Comment by sjwarner-bp** [comment]
And another one...

```
41.54s$ rvm install 2.2.5
Searching for binary rubies, this might take some time.
No binary rubies available for: ubuntu/14.04/x86_64/ruby-2.2.5.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for ubuntu.
Requirements installation successful.
Installing Ruby from source to: /home/travis/.rvm/rubies/ruby-2.2.5, this may take a while depending on your cpu(s)...
ruby-2.2.5 - #downloading ruby-2.2.5, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:15 --:--:--     0curl: (7) Failed to connect to cache.ruby-lang.org port 443: Connection timed out
There was an error(7).
Checking fallback: https://ftp.ruby-lang.org/pub/ruby/2.2/ruby-2.2.5.tar.bz2
No fallback URL could be found, try increasing timeout with:
    echo "export rvm_max_time_flag=20" >> ~/.rvmrc
There has been an error fetching the ruby interpreter. Halting the installation.
The command "rvm install 2.2.5" failed and exited with 7 during .
Your build has been stopped.
```

Was in #1215

**Comment by FridaTveit** [comment]
Looks like turning off branch builds didn't help then 😞 Do you know if the bash track maintainers are doing anything about it if their builds are failing in the same way @sjwarner-bp?

**Comment by sjwarner-bp** [comment]
There are only about three of us over at the bash track - the main focus at the moment is getting the track launched, and I've only seen it once over there, so we've not discussed it properly yet :slightly_frowning_face:

**Comment by sjwarner-bp** [comment]
What do you think of trying out that retry parameter? I'm not sure if it will work when the issue is a failed connection, but I'd be happy for us to try it out if others think it would help :slightly_smiling_face:

**Comment by FridaTveit** [comment]
Sure, it's worth a try. Feel free to try setting it up if you like 🙂

**Comment by sjwarner-bp** [comment]
This last change might have helped out... I've not seen failing builds for a while now :crossed_fingers:

**Comment by FridaTveit** [comment]
Me neither, hopefully that change was all that was needed! 🙂 Should we close this issue for now and reopen it if we start seeing problems again?

**Comment by sjwarner-bp** [comment]
Sounds good to me! :slightly_smiling_face:

**Comment by sjwarner-bp** [comment]
A build timed out today after 50 minutes!

https://travis-ci.org/exercism/java/jobs/340156687

They're definitely far more infrequent, and I think many branches were building at the time (5 or so). I'm not sure if this affects it.

**Comment by sjwarner-bp** [comment]
Looks like two of the concurrent builds timed out. The following ran at the same time as the above!

https://travis-ci.org/exercism/java/jobs/340189363

**Comment by sjwarner-bp** [comment]
More timeouts...

https://travis-ci.org/exercism/java/jobs/340324683
