### ISSUE TITLE
sum-of-multiples: update tests

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1253]
The sum-of-multiples tests should be updated to exactly match the canonical data. Also the version file should be updated to match the canonical data version.

**Comment by hgvanpariya** [comment]
@FridaTveit , can you please provide me the sample of the existing tests ?

**Comment by hgvanpariya** [comment]
Hi @FridaTveit , @exercism/java,

Please review the changes ... and suggest if there is any update needed.

**Comment by sjwarner-bp** [comment]
Closed via #1255
