### ISSUE TITLE
raindrops: update version file (1.0.0 -> 1.1.0)

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1264]
Please update the version specified in the [raindrops version file](https://github.com/exercism/java/blob/master/exercises/raindrops/.meta/version) from 1.0.0 to 1.1.0.

Background info: each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. The version can be found at the top of [the canonical data file for that exercise](https://github.com/exercism/problem-specifications/blob/master/exercises/raindrops/canonical-data.json).

**Comment by jssander** [comment]
I would like to work on this, but I don't quite see where the canonical data is different. It still seems to be using the same numbers as input with the same expected results. What am I missing?

**Comment by sjwarner-bp** [comment]
[The most recent change](https://github.com/exercism/problem-specifications/commit/99de15d6c896c9b6d2cbce31a3cddd3cb169cf10#diff-0f739d44ce21401b16e016fecb78e166) shows that the update from 1.0.0 -> 1.1.0 was caused by updating the canonical data to the new 'input' policy.

This means that the actual test data probably isn't any different. I think all you'll need to do is update the version number 🙂

**Comment by FridaTveit** [comment]
One of the changes I picked up on was that the canonical data was in a different order to our tests. Normally we'd like to maintain the same order. However since the raindrops tests are parameterized I guess it doesn't really matter, they'll all get run every time anyway. Which is one of the reasons I don't really like using parameterized tests for exercism...

So @sjwarner is right, all you have to do it update the version number 🙂

**Comment by sjwarner-bp** [comment]
We could always open a new issue to separate them out into individual tests. This would be more consistent with the rest of our test suites, and allows for a more TDD-style approach! :slightly_smiling_face:

**Comment by FridaTveit** [comment]
Opened issue #1293 🙂

**Comment by FridaTveit** [comment]
And I've updated the description of this issue to more accurately describe what needs to be updated 🙂
