### ISSUE TITLE
isbn-verifier: update tests and version file (2.0.0 -> 2.2.0)

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1266]
One extra test has been added to [the canonical data for isbn-verifier](https://github.com/exercism/problem-specifications/blob/master/exercises/isbn-verifier/canonical-data.json). Please add this test (it's the last test in the canonical data fil with description `"empty isbn"`) to the [isbn-verifier test suite](https://github.com/exercism/java/blob/master/exercises/isbn-verifier/src/test/java/IsbnVerifierTest.java) and update the number in the [version file](https://github.com/exercism/java/blob/master/exercises/isbn-verifier/.meta/version) from 2.0.0 to 2.2.0.

**Comment by LuLechuan** [comment]
Hi, I am a new contributor here. Can I work on this issue? Thanks
