### ISSUE TITLE
matrix: update tests and add version file

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1267]
The [canonical data for matrix](https://github.com/exercism/problem-specifications/blob/master/exercises/matrix/canonical-data.json) has diverged from our test suite. Please update the tests and the reference implementation if necessary, and add a version file.

**Comment by jssander** [comment]
I would like to work on this.

**Comment by FridaTveit** [comment]
That's great that you want to work on this @jssander! 🙂 Yes, please remove any tests that aren't present in the canonical data 🙂

**Comment by jssander** [comment]
Ok, I submitted a pull request.

**Comment by sjwarner-bp** [comment]
@jssander Cool! I'll check it out when I get a second :slightly_smiling_face:

**Comment by FridaTveit** [comment]
Closed in PR #1297. Thanks @jssander! 🙂
