### ISSUE TITLE
collatz-conjecture: update version file (1.1.1 -> 1.2.0)

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1273]
Please update the version specified in the [collatz-conjecture version file](https://github.com/exercism/java/blob/master/exercises/collatz-conjecture/.meta/version) from 1.1.1 to 1.2.0.

Background info: each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. The version can be found at the top of [the canonical data file for that exercise](https://github.com/exercism/problem-specifications/blob/master/exercises/collatz-conjecture/canonical-data.json).

**Comment by kingmob81** [comment]
Hi

**Comment by sjwarner-bp** [comment]
Hi @kingmob81, would you like to fix this issue for us? 🙂

**Comment by kingmob81** [comment]
Done

**Comment by kingmob81** [comment]
No thanks
