### ISSUE TITLE
Error executing journey-test.sh

### ISSUE THREAD

**Issue by Haozhe321** [exercism/java#1291]
When I run `sh bin/journey-test.sh`, the script hangs at 
`tar xz -C <EXERCISE DIRECTORY> -f /var/folders/jn/qv3phvjd2w7cm9hh6tg4nstc0000gn/T/tmp.7ozkskTD` in the terminal.

When I terminate the script, the following error shows up. 
```
tar: Unrecognized archive format

tar: /var/folders/jn/qv3phvjd2w7cm9hh6tg4nstc0000gn/T/tmp.7ozkskTD: Not found in archive
tar: -f: Not found in archive
tar: oss/java/build/exercism: Not found in archive
tar: Error exit delayed from previous errors.
```

Assistance is greatly appreciated!!

**Comment by sjwarner-bp** [comment]
Did you find out the problem here @Haozhe321 ?

**Comment by Haozhe321** [comment]
@sjwarner-bp turns out I didn't do `brew install exercism` and configure the API key.
