### ISSUE TITLE
Remove use of parameterized tests

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1293]
We have some exercises that use parameterized tests. This makes it harder to do TDD since you can't ignore tests. We should convert these test suites to use individual tests instead of one parameterized test.

The exercises that need to be changed are:
- [x] raindrops
- [x] matrix
- [x] binary
- [ ] octal
- [x] scrabble-score
- [x] roman-numerals
- [x] prime-factors
- [x] atbash-cipher
- [x] pig-latin

If you want to work on this issue please only fix one exercise per PR 🙂 And please don't put "fixes #1293" in the PR description (unless you're fixing the last exercise that needs to be changed) as [that will automatically close this issue when the PR is merged](https://github.com/blog/1506-closing-issues-via-pull-requests)! 🙂

**Comment by Kyle-P** [comment]
I'll take care of the raindrops class!

**Comment by LuLechuan** [comment]
I can take care of the last five

**Comment by sjwarner-bp** [comment]
Ok @LuLechuan! Please put each in to a separate PR so they may be merged and reviewed as quickly and simply as possible 🙂

**Comment by c-thornton** [comment]
I will try and take care of the binary and octal exercises tonight after I get home. Hopefully that will finish these all off.

**Comment by Haozhe321** [comment]
I can take octal!
