### ISSUE TITLE
raindrops: make tests more closely match canonical data

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1310]
In the [raindrops tests](https://github.com/exercism/java/blob/master/exercises/raindrops/src/test/java/RaindropConverterTest.java) we're currently testing the same cases as the [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/raindrops/canonical-data.json). However, we deviate from the canonical data by:

1. The order of the tests. This is important since the order in the canonical data has been carefully chosen so that no test is useless. That is, making one test pass shouldn't necessarily make any of  the subsequent tests pass. That way each test is useful 🙂 

2.  How many assertions there are in each test. In the canonical data there is only one assertion per test. I think we should stick to that since [it's good practice to make tests as granular as possible](https://softwareengineering.stackexchange.com/questions/7823/is-it-ok-to-have-multiple-asserts-in-a-single-unit-test). That way it's easy to track your progress by how many tests pass and you get the rewarding feeling of seeing a new test pass as often as possible. And it means that if a test fails then that should hopefully highlight only one specific issue, described in the test name.

So we should change the raindrops tests to have the same order and same number of assertions per test as the canonical data 🙂

**Comment by Kyle-P** [comment]
Oops. Sorry about that. I'll take care of this and fix everything up sometime soon 😊

**Comment by FridaTveit** [comment]
No problem, it's something that we only agreed in the last few days that should be a priority 🙂 

That's great, thank you! 😊
