### ISSUE TITLE
atbash-cipher: update versio file (1.0.0 -> 1.1.0)

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1319]
Please update the version specified in the [atbash-cipher version file](https://github.com/exercism/java/blob/master/exercises/atbash-cipher/.meta/version) from 1.0.0 to 1.1.0.

Background info: each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. The version can be found at the top of [the canonical data file for that exercise](https://github.com/exercism/problem-specifications/blob/master/exercises/atbash-cipher/canonical-data.json).

**Comment by sjwarner-bp** [comment]
Fixed by #1339
