### ISSUE TITLE
Alphametics Version File Issue

### ISSUE THREAD

**Issue by Kyle-P** [exercism/java#1352]
It looks like the alphametics version file issue at https://github.com/exercism/java/issues/1321 has a faulty link to the version file. The correct URL can be found at https://github.com/exercism/java/blob/master/exercises/alphametics/.meta/src/version.

@FridaTveit or @sjwarner-bp would you be able to fix this?

**Comment by FridaTveit** [comment]
That's actually a problem with the alphametics version file, not with the issue! The alphametics version file should be moved to https://github.com/exercism/java/blob/master/exercises/alphametics/.meta/version, it should not be inside a src directory. Thanks for pointing this out @Kyle-P! 🙂

**Comment by FridaTveit** [comment]
I've updated the issue (#1321) to include moving the file to the correct directory 🙂
