### ISSUE TITLE
roman-numerals: update version file and add test (1.0.0 -> 1.2.0)

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1355]
Please update the version specified in the [roman-numerals](https://github.com/exercism/java/blob/master/exercises/roman-numerals/.meta/version) version file from 1.0.0 to 1.2.0.

Please also include one extra test which is included in the canonical data but not in [our tests](https://github.com/exercism/java/blob/master/exercises/roman-numerals/src/test/java/RomanNumeralsTest.java); between the tests for converting 48 and converting 59 there should be a test for converting 49.

Background info: each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. The version can be found at the top of [the canonical data file for that exercise](https://github.com/exercism/problem-specifications/blob/master/exercises/roman-numerals/canonical-data.json).

**Comment by katmpatz** [comment]
@FridaTveit, if this issue is already open I would really want to contribute!

**Comment by sjwarner-bp** [comment]
Feel free to pick this one up @katmpatz ! :slightly_smiling_face:

**Comment by FridaTveit** [comment]
Yes, go for it @katmpatz 🙂
