### ISSUE TITLE
house: update tests

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1356]
The [house tests](https://github.com/exercism/java/blob/master/exercises/house/src/test/java/HouseTest.java) are slightly out of sync with the [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/house/canonical-data.json). Please update the tests, the reference solution and the version file (2.0.0 -> 2.2.0).

**Comment by tendaitt** [comment]
@FridaTveit I might work on this but I need some clarification.

1. What do you mean the tests are slightly out of sync with the canonical data?
2. What is the reference solution?

**Comment by FridaTveit** [comment]
@tendaitt great, thanks! 😃 

> What do you mean the tests are slightly out of sync with the canonical data?

I mean that the [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/house/canonical-data.json) is slightly different to our tests. In this case the difference is that our solution inserts more newlines than the canonical data. For example, our second test expects the output to be:
```
 "This is the malt\n" +
     "that lay in the house that Jack built."
```
whereas the canonical data expects it to be:
```
"This is the malt that lay in the house that Jack built."
```

We want our tests to match the canonical data as closely as possible so that the exercises are consistent across the different tracks 🙂 

I hope all of that makes sense, let me know if it doesn't! 🙂

**Comment by sjwarner-bp** [comment]
@tendaitt Also worth noting that the reason these our tests get out of sync with the canonical data is because that is where people review and discuss ways to improve the test suites.

Often these changes are to cover edge cases that had not previously been considered, or correcting errors.

By keeping our tests up to date, we encourage users to build more robust solutions! :fireworks:

**Comment by tendaitt** [comment]
@FridaTveit: your comment makes sense. I have begun working on this.
@sjwarner-bp: Thank you for the context.

Also, should the README.md file also resemble the canonical data?

**Comment by sjwarner-bp** [comment]
@tendaitt To some extent. We automatically generate the READMEs using a tool called `configlet`.

You can do this by:
* Downloading configlet and putting it somewhere in your PATH
* Clone the problem-specifications repository.
* Run `configlet generate . --only name_of_new_exercise --spec-path path_to_problem_specifications` from the root of this repository.

The main differences will be all the extra Java-specific stuff we add to it! For example the info about `gradle`. Optional hints may also be appended depending!

Does this make sense? :slightly_smiling_face:

**Comment by tendaitt** [comment]
Created a [pull request](https://github.com/exercism/java/pull/1392) for your review.
