### ISSUE TITLE
robot-simulator: update tests

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1358]
The [robot-simulator tests](https://github.com/exercism/java/blob/master/exercises/robot-simulator/src/test/java/RobotTest.java) are slightly out of sync with the [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/robot-simulator/canonical-data.json). Please update the tests, the reference solution (if needed) and the version file (1.0.0 -> 2.2.0).

**Comment by Kyle-P** [comment]
I'll see if I can tackle this one soon!
