### ISSUE TITLE
two-bucket: should the difficulty be increased?

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1360]
The two-bucket exercise currently has difficulty 5. However, it's relatively complicated and similar to the new exercise go-counting (PR #1351) which has been given difficulty 7.  I think two-bucket is definitely more complicated than other exercises with difficulty 5 such as bob or pascals-triangle. Should we increase the difficulty of two-bucket @exercism/java? 🙂

**Comment by Kyle-P** [comment]
Yeah, if it's relatively similar in difficulty and how complicated it is, we might want to consider increasing the level. But, I'm not too familiar with the rating system for difficulties so we might want some more people on this 👍

**Comment by Smarticles101** [comment]
I would vote to increase the difficulty 👍

**Comment by FridaTveit** [comment]
I've opened an issue for it: #1384 🙂
