### ISSUE TITLE
all-your-base: update version file (2.1.0 -> 2.3.0) and update one test

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1363]
Please update the version specified in the [all-your-base](https://github.com/exercism/java/blob/master/exercises/all-your-base/.meta/version) version file from 2.1.0 to 2.3.0.

Also please update the test with name `testFirstBaseIsOne` in [the all-your-base tests](https://github.com/exercism/java/blob/master/exercises/all-your-base/src/test/java/BaseConverterTest.java). The last line of this test should now be:
```
new BaseConverter(1, new int[]{1});
```
instead of:
```
new BaseConverter(1, new int[]{});
```

Background info: each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. The version can be found at the top of [the canonical data file for that exercise](https://github.com/exercism/problem-specifications/blob/master/exercises/all-your-base/canonical-data.json).

**Comment by katmpatz** [comment]
@FridaTveit if this issue is still open, I would really like to contribute!

**Comment by FridaTveit** [comment]
Go for it! 😃 

Any issue in the issues list is open and ready to be worked on 🙂 Just check whether someone else has put a comment on it to say that they're working on it and check the open pull requests to see if someone else has opened a pull request for it. If not, then you're fine to start working on it! 🙂
