### ISSUE TITLE
Track configuration contains improperly locked exercises

### ISSUE THREAD

**Issue by nywilken** [exercism/java#1366]
In the upcoming release of [Configlet v3.8.0](https://github.com/exercism/configlet/issues/121), the lint command will now verify that locked exercises meet the unlocked_by criteria, as defined by the track [configuration spec](https://github.com/exercism/docs/blob/master/language-tracks/configuration/exercises.md):

- Core exercises can not be unlocked by other exercises.
- Non-core exercises can only be unlocked by core exercises.

Before cutting a release of Configlet I am opening issues on all tracks found to contain one or more unlocked_by violations so that maintainers of the track can validate and remedy the violations.

```

-> The exercise 'protein-translation' is being unlocked by a non-core exercise. Non-core exercises can only be unlocked by core exercises.
```

**Comment by FridaTveit** [comment]
Thank you for raising this @nywilken! 🙂 

protein-translation is currently unlocked by rna-transcription which is not a core exercise. I suggest we make it unlocked by two-fer since they share some topics (string, conditionals). What do you think @exercism/java? 🙂

**Comment by Kyle-P** [comment]
Sounds good to me @FridaTveit! If the concepts are relatively similar, it should be fine.
