### ISSUE TITLE
two-bucket: increase difficulty from 5 to 7

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1384]
Please update the difficulty for the two-bucket exercise from 5 to 7 in [config.json](https://github.com/exercism/java/blob/master/config.json).

See issue #1360 for discussion.

**Comment by tendaitt** [comment]
I would like to work on this. Does the change entail only editing the `config.json` file?

**Comment by sjwarner-bp** [comment]
Hi @tendaitt - that's great!

Yes, for this issue I believe we are only looking for a change to the `config.json` :slightly_smiling_face:

**Comment by tendaitt** [comment]
Thanks for the clarification @sjwarner-bp! I have created at [pull request](https://github.com/exercism/java/pull/1390) for your review.
