### ISSUE TITLE
rail-fence-cipher: add version file (1.1.0)

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1405]
Please add a file in `/exercises/rail-fence-cipher/.meta` named `version` with content `1.1.0`. This will be the version file for rail-fence-cipher. See the [acronym version file](https://github.com/exercism/java/blob/master/exercises/acronym/.meta/version) for an example version file.

Background info: each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. The version can be found at the top of [the canonical data file for that exercise](https://github.com/exercism/problem-specifications/blob/master/exercises/rail-fence-cipher/canonical-data.json).

**Comment by hgvanpariya** [comment]
@FridaTveit , added version file for `rail-fence-cipher`, please provide your review comments.

**Comment by FridaTveit** [comment]
Fixed in PR #1457, thanks @hgvanpariya 🙂
