### ISSUE TITLE
minesweeper: remove `final` from tests

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1424]
According to our [policies](https://github.com/exercism/java/blob/master/POLICIES.md#avoid-using-final) we want to avoid using `final` in user facing code as it can be confusing to people new to Java.

Please remove all uses of `final` in the [minesweeper tests](https://github.com/exercism/java/blob/master/exercises/minesweeper/src/test/java/MinesweeperBoardTest.java).

**Comment by sjwarner-bp** [comment]
Closed via #1438
