### ISSUE TITLE
phone-number: remove `final` from tests

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1425]
According to our [policies](https://github.com/exercism/java/blob/master/POLICIES.md#avoid-using-final) we want to avoid using `final` in user facing code as it can be confusing to people new to Java.

Please remove all uses of `final` in the [phone-number tests](https://github.com/exercism/java/blob/master/exercises/phone-number/src/test/java/PhoneNumberTest.java).

**Comment by sjwarner-bp** [comment]
Closed via #1433
