### ISSUE TITLE
Kindergarten Garden - unused constructor in starter solution

### ISSUE THREAD

**Issue by jsertel** [exercism/java#1441]
In the starter solution for [Kindergarten Garden](https://github.com/exercism/java/tree/master/exercises/kindergarten-garden) there are two constructors, but it appears the test suite only uses one. Its possible to remove the first constructor and still pass the tests.

First constructor takes a string and an array:

`
    KindergartenGarden(String garden, String[] students) {
        throw new UnsupportedOperationException("Delete this statement and write your own implementation.");
    }
`

Second constructor takes just a string:  

`    
    KindergartenGarden(String garden) {
        throw new UnsupportedOperationException("Delete this statement and write your own implementation.");
    }
`

The problem specification states:
> There are 12 children in the class:
> - Alice, Bob, Charlie, David,
> - Eve, Fred, Ginny, Harriet,
> - Ileana, Joseph, Kincaid, and Larry.

The first constructor implies to me that the solution should be able to work with a list of students that could vary from the above list. That functionality does not get tested though. It would seem it would also be outside of the canonical test. So do we need the constructor that is never used?

**Comment by sjwarner-bp** [comment]
Looks like this is leftover from when the old tests used to ask for students to also be supplied to the constructor in a non-alphabetical order.

We seem to have moved away from that!

Good spot, this should probably be removed @jsertel :slightly_smiling_face:

**Comment by sjwarner-bp** [comment]
Closed via #1465 

Thanks @aadityakulkarni :open_hands:
