### ISSUE TITLE
robot-simulator: remove `final` from tests

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1453]
According to our [policies](https://github.com/exercism/java/blob/master/POLICIES.md#avoid-using-final) we want to avoid using `final` in user facing code as it can be confusing to people new to Java.

Please remove all uses of `final` in the [robot-simulator tests](https://github.com/exercism/java/blob/master/exercises/robot-simulator/src/test/java/RobotTest.java).

**Comment by hgvanpariya** [comment]
@FridaTveit : removed final from RobotTest.java, please provide code review comments.

**Comment by FridaTveit** [comment]
Fixed in PR #1459, thanks @hgvanpariya 🙂
