### ISSUE TITLE
error-handling: case `testThrowAnyUncheckedException` passes without user changes

### ISSUE THREAD

**Issue by cmccandless** [exercism/java#1460]
I'm new to the contributor side of the Java track, so this might be intentional. `UnsupportedOperationException` is an unchecked exception, so the following solution template is already a valid solution:

```Java
void handleErrorByThrowingAnyUncheckedException() {
    throw new UnsupportedOperationException("Delete this statement and write your own implementation.");
}
```

**Comment by FridaTveit** [comment]
Thanks for raising this @cmccandless, that's a good point! 🙂 

@Smarticles101 yes we could probably do that 🙂 But I'm not sure being more strict in the matcher would be ideal in this case. We already have a separate test and method for throwing a specific unchecked exception and any unchecked exception with a specific error message. So I think our options are:
* Remove the `UnsupportedOperationException` from the starter implementation and leave that method body empty. That would ensure the test fails. It might be a bit confusing why that method body is empty, we could maybe put a comment instead? But it's not the first thing they have to implement for this exercise so I think it would be okay.

* Accept that this specific test will pass without any implementation being required. Not ideal, but might prompt users to look at the starter implementation and realise that `UnsupportedOperationException` is an unchecked exception?

* Remove the test for any unchecked exception (and maybe also the one for any checked exception) and just keep the one for any unchecked exception with a specific message and the one for a specific unchecked exception.

* Any other suggestions @Smarticles101 @exercism/java?

**Comment by sjwarner-bp** [comment]
Nice summary @FridaTveit !

I think that either the first or third option @FridaTveit has outlined would make most sense :slightly_smiling_face: 

I'm probably leaning towards the first option as although it goes against our POLICIES, if we leave a meaningful comment then it'll probably be fine :slightly_smiling_face:

**Comment by FridaTveit** [comment]
I've raised good first patch issue #1509 to fix this so I think we can close this issue 🙂 Feel free to reopen (or put a comment on #1509) if anyone thinks that's not the case 🙂
