### ISSUE TITLE
isbn-verifier: update tests and version file (v2.2.0 -> v.2.5.0)

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1462]
The [isbn-verifier tests](https://github.com/exercism/java/blob/master/exercises/isbn-verifier/src/test/java/IsbnVerifierTest.java) aren't up to do date with the [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/isbn-verifier/canonical-data.json). Please update the tests so that they match the canonical data. Also update the [version file](https://github.com/exercism/java/blob/master/exercises/isbn-verifier/.meta/version) file so that it matches the version specified in the canonical data.

**Comment by sjwarner-bp** [comment]
Closed via #1466
