### ISSUE TITLE
kindergarten-garden: update version file (v1.1.0 -> v.1.1.1)

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1463]
Please update the version specified in the [kindergarten-garden](https://github.com/exercism/java/blob/master/exercises/kindergarten-garden/.meta/version) version file from 1.1.0 to 1.1.1.

Background info: each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. The version can be found at the top of [the canonical data file for that exercise](https://github.com/exercism/problem-specifications/blob/master/exercises/kindergarten-garden/canonical-data.json).

**Comment by RonakLakhotia** [comment]
@FridaTveit can I work on this? Thanks.

**Comment by sjwarner-bp** [comment]
@RonakLakhotia Go for it! :fireworks:

**Comment by RonakLakhotia** [comment]
PR created. ready for review

**Comment by sjwarner-bp** [comment]
Closed via #1469 

Thanks @RonakLakhotia :slightly_smiling_face:
