### ISSUE TITLE
series: update tests and add version file

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1471]
The [series tests](https://github.com/exercism/java/blob/master/exercises/series/src/test/java/SeriesTest.java) should be updated to exactly match the [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/series/canonical-data.json). Also a version file should be added to match the canonical data version.

**Comment by miranikaran01** [comment]
I would like to work on this one.

**Comment by hgvanpariya** [comment]
@FridaTveit : Test case  `slice length cannot be zero` is invalid in usecase in https://github.com/exercism/problem-specifications/blob/master/exercises/series/canonical-data.json 

When the slice is Zero it is not throwing Exception, Can you please confirm ?

**Comment by AndresAcuna** [comment]
If this is still open, I'd like to take care of it.

**Comment by FridaTveit** [comment]
@AndresAcuna thanks for wanting to contribute! 🙂 However, @hgvanpariya has got an open pull request for this issue. @hgvanpariya are you still working on it? 🙂

**Comment by hgvanpariya** [comment]
@FridaTveit : yes, I'll fix this ...

**Comment by FridaTveit** [comment]
Great, thanks @hgvanpariya! 🙂

**Comment by FridaTveit** [comment]
Fixed in PR #1504. Thanks @hgvanpariya 🙂
