### ISSUE TITLE
grade-school: update tests and add version file

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1472]
The [grade-school tests](https://github.com/exercism/java/blob/master/exercises/grade-school/src/test/java/SchoolTest.java) should be updated to exactly match the [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/grade-school/canonical-data.json). Also a version file should be added to match the canonical data version.

**Comment by miranikaran01** [comment]
@FridaTveit  I would like to work on this one

**Comment by alis0nc** [comment]
Duplicate of #1538, which I've opened PR #1572 for.

**Comment by FridaTveit** [comment]
Thanks for pointing that out @alis0nc! 🙂
