### ISSUE TITLE
word-search: update version file (v1.2.0 -> v1.2.1)

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1473]
Please update the version specified in the [word-search](https://github.com/exercism/java/blob/master/exercises/word-search/.meta/version) version file from 1.2.0 to 1.2.1.

Background info: each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. The version can be found at the top of [the canonical data file for that exercise](https://github.com/exercism/problem-specifications/blob/master/exercises/word-search/canonical-data.json).

**Comment by miranikaran01** [comment]
I would like to work on this one

**Comment by PTrottier** [comment]
Has this issue been resolved?

**Comment by FridaTveit** [comment]
No, I don't think so @PTrottier 🙂 @miranikaran01 are you still working on it? 🙂 

If @miranikaran01 isn't working on it anymore then feel free to work on it @PTrottier 🙂 However, we're currently trying to fix an issue with our build scripts to do with the exercism update. So we won't be able to merge any pull requests at the moment. But feel free to open a PR anyway and we'll get to it as soon as we can! 🙂

**Comment by FridaTveit** [comment]
Sure, go for it @PTrottier! 🙂

**Comment by FridaTveit** [comment]
Fixed in PR #1500. Thanks @PTrottier 🙂
