### ISSUE TITLE
diffie-hellman: update tests and add version file

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1474]
The [diffie-hellman tests](https://github.com/exercism/java/blob/master/exercises/diffie-hellman/src/test/java/DiffieHellmanTest.java) should be updated to exactly match the [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/diffie-hellman/canonical-data.json). Also a version file should be added to match the canonical data version.

**Comment by hgvanpariya** [comment]
@FridaTveit : I've raised the PR with the changes, please provide your feedback ...

**Comment by FridaTveit** [comment]
Fixed in PR #1503. Thanks @hgvanpariya! 🙂
