### ISSUE TITLE
forth: update version file (v1.5.0 -> v1.6.0) and add two new tests

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1477]
Please update the version specified in the [forth](https://github.com/exercism/java/blob/master/exercises/forth/.meta/version) version file from 1.5.0 to 1.6.0.

Please also add two new tests to the [forth tests](https://github.com/exercism/java/blob/master/exercises/forth/src/test/java/ForthEvaluatorTest.java). This should be the test "can use different words with the same name" and "can define word that uses word with the same name" as described in the [canonical data for forth](https://github.com/exercism/problem-specifications/blob/master/exercises/forth/canonical-data.json). See [this diff file](https://github.com/exercism/problem-specifications/commit/c85397312197906905c295ec7d026e53159d2fd4#diff-52c461e552f1acbd0a46e292fb439afc) to make it more obvious which tests have been added.

Please add them in the same place in the tests as they've been added in the canonical data (after the "can override built-in operators" test and before the "cannot redefine numbers" test).

Background info: each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. The version can be found at the top of the canonical data file for that exercise.

**Comment by jackattack24** [comment]
When I add the two new tests from the canonical data they both fail. Here are the stack traces that I get when I run the tests:
```java
ForthEvaluatorTest > testCanUseDifferentWordsWithTheSameName FAILED
    java.lang.AssertionError: expected:<[5, 6]> but was:<[6, 6]>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at ForthEvaluatorTest.testCanUseDifferentWordsWithTheSameName(ForthEvaluatorTest.java:293)

ForthEvaluatorTest > testCanDefineWordThatUsesWordWithTheSameName FAILED
    java.lang.IllegalArgumentException: Addition requires that the stack contain at least 2 values
        at ForthEvaluator$1.lambda$new$0(ForthEvaluator.java:11)
        at ForthEvaluator.evaluateOpToken(ForthEvaluator.java:148)
        at ForthEvaluator.evaluate(ForthEvaluator.java:133)
        at ForthEvaluator.evaluateProgram(ForthEvaluator.java:114)
        at ForthEvaluatorTest.testCanDefineWordThatUsesWordWithTheSameName(ForthEvaluatorTest.java:302)
```
And this is how I wrote the new tests. As far as I can tell, I've written them correctly according to their specifications in the [canonical data](https://github.com/exercism/problem-specifications/commit/c85397312197906905c295ec7d026e53159d2fd4#diff-52c461e552f1acbd0a46e292fb439afc) so maybe the reference solution needs to be updated?
```java
@Ignore("Remove to run test")
@Test
public void testCanUseDifferentWordsWithTheSameName() {
    assertEquals(
            Arrays.asList(5, 6),
            forthEvaluator.evaluateProgram(Arrays.asList(": foo 5 ;", ": bar foo ;", ": foo 6 ;", "bar foo")));
}

@Ignore("Remove to run test")
@Test
public void testCanDefineWordThatUsesWordWithTheSameName() {
    assertEquals(
            Collections.singletonList(11),
            forthEvaluator.evaluateProgram(Arrays.asList(": foo 10 ;", ": foo foo 1 + ;", "foo")));
}
```

**Comment by FridaTveit** [comment]
Thanks for tackling this @jackattack24! 🙂 Yes, in that case the reference solution probably needs to be updated. There's always a chance that will be needed when we update the tests 🙂
