### ISSUE TITLE
Document how to set up project in IntelliJ

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/java#1479]
While we have documentation that helps contributors set up and run the project from the command line, a large number of contributors also use IDEs to make changes to files.

IntelliJ seems to be the most popular IDE that is used (though others are mentioned [here](https://github.com/exercism/java/blob/master/docs/INSTALLATION.md), so we should update the [CONTRIBUTING file](https://github.com/exercism/java/blob/master/CONTRIBUTING.md) to include instructions to pull in the project.

**Comment by Smarticles101** [comment]
I'd be interested in writing documentation for this, I should be getting a new laptop tomorrow so I'll have to set up the project again which would be a good time to write this documentation.

**Comment by sjwarner-bp** [comment]
Sounds like a great time to get this one done! Go for it @Smarticles101 :tada:

**Comment by FridaTveit** [comment]
Great, thanks @Smarticles101! 😄

**Comment by Smarticles101** [comment]
I'll go ahead and work on this now. I need to make PR's for hacktoberfest lol

**Comment by delbertlegg** [comment]
I enjoy contributing to this project for Hacktoberfest...mind if I pick this one up and any others needing attention?

**Comment by delbertlegg** [comment]
Great! Just for clarification - how deep should we be getting as far as steps? Do you want to include using the built-in git tools in Intellij, or are we just talking about importing the project?

**Comment by lemoncurry** [comment]
@delbertlegg Whatever you think is best. The guide is aimed at coders just starting with IntelliJ and git, who want to know how they can set up their first project using IntelliJ. It would be great to also include screenshots for each step.

**Comment by delbertlegg** [comment]
Good deal - probably wouldn't hurt including it all. Thanks!
