### ISSUE TITLE
armstrong-numbers: add `unlocked_by:`

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/java#1485]
In v2 of exercism, completing 'core' exercises will unlock more optional exercises.

As part of this, all optional exercises should specify which core exercise unlocks it.

Please amend [config.json](https://github.com/exercism/java/blob/master/config.json) for the `armstrong-numbers` exercise to be `unlocked_by` an appropriate core exercise. Try and group it with a core exercise with similar topics! 🙂

**Comment by FridaTveit** [comment]
@sjwarner-bp as explained in issue #1481, I don't think this needs fixing. It was part of our intention when restructuring the track and as far as I'm aware it should be part of the structure of v2 🙂

**Comment by sjwarner-bp** [comment]
Closed as explained in #1481
