### ISSUE TITLE
Update docs and build with latest exercism cli changes

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1493]
There have been some exercism cli changes recently that need to be reflected in our build process and documentation. To do this it might be easiest to [download the latest version of exercism cli](https://github.com/exercism/cli/releases) and play around with it to find out what the changes are.

**Comment by sjwarner-bp** [comment]
There are some notes in the nextercism Slack group - I'll condense and copy over here :tada:

**Comment by sjwarner-bp** [comment]
Basic guide:

1) Download it here: http://bit.ly/2tuyoI1
2) Grab your token from https://mentors-beta.exercism.io/my/settings
3) Configure it using `mentorcism configure --token=TOKEN`
4) Using the UI, find the exercise you want to try. Note the download link
5) Run the download command like `mentorcism download hello-world --track=ruby`
6) Make the tests pass and refactor
7) Submit using `mentorcism submit DIR` (edited)

This is from a month ago though - there doesn't seem to be much more detailed right this second. I guess now it is live that new info will begin to come out?

**Comment by FridaTveit** [comment]
Thanks! 🙂 That release is tagged as `pre-release` and `alpha` though, so has it really been released? Is that really what our CI build will be using? I thougth this was the link to getting the latest exercism cli release: https://github.com/exercism/cli/releases?

Obviously it's good to be prepared anyway, even if it's just with a list of things that will need changing once we start using the new cli. But I'm still a bit confused as to whether that has happened yet or not...

**Comment by sjwarner-bp** [comment]
Me either... The new version of the site went live a few days ago though, so I would have imaged that the new cli would be used now too? Not sure - I'll have to do some digging :slightly_smiling_face:

**Comment by FridaTveit** [comment]
That makes sense, I'll try to look into it to 🙂 Working on the needed updates to journey-test now! 🙂

**Comment by FridaTveit** [comment]
Okay the issues I'm currently seeing with the update:
- It doesn't seem to be possible to run `exercism configure` without a token anymore. My current workaround is to use my own token but that's probably not a good longterm solution.

- The script doesn't appear to be able to reach x-api. I get the error `The base API URL 'http://localhost:9292' cannot be reached`, even though just before then the script logs:
```
Puma 2.15.3 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:9292
+ echo 'x-api is running (pid=54961).'
x-api is running (pid=54961).
```

@sjwarner-bp @exercism/java @kytrinyx any ideas for how to solve these issues?

Happy to push my current changes to a WIP PR if you think that will help 🙂 You never know, it might run better on travis than on my laptop...

**Comment by sjwarner-bp** [comment]
Hi @FridaTveit! Looks like a couple of other tracks are experiencing the same problems. Kotlin has this morning reported similar build failures.

I agree that using your own token is probably not a great long-term solution, so hopefully we should be able to come up with some other way (maybe @kytrinyx will know)!

Pushing the changes up to a WIP branch sounds like a good plan, I'd love to see what you've edited so far and how we can tweak it further :slightly_smiling_face: :tada:

**Comment by kytrinyx** [comment]
Would you please open an issue on https://github.com/exercism/exercism.io? I'd like to get everyone who has journey tests together to discuss how best to solve this.

**Comment by FridaTveit** [comment]
Sure! I see you've commented on https://github.com/exercism/exercism.io/issues/3955, hopefully that'll be a good issue to use to discuss it? 🙂

**Comment by kytrinyx** [comment]
That's perfect, thank you.

**Comment by FridaTveit** [comment]
The build is passing now, yay 🙂 We should still probably look through documentation to check if anything needs updating, I'll try to find time to do that over the next few days 🙂

**Comment by FridaTveit** [comment]
I'm still a bit confused about which version of the exercism cli people should be using at the moment though @kytrinyx. Is it the one from here as usual: https://github.com/exercism/cli/releases, or the mentorcism one from here: https://github.com/exercism/cli/releases/tag/v3.0.0-alpha.9.mentors? They are a bit different and so it would be good to know which should be used so that our documentation is correct 🙂

**Comment by kytrinyx** [comment]
> The build is passing now, yay

Yay, congrats 🎉 

Definitely the one from https://github.com/exercism/cli/releases!

**Comment by FridaTveit** [comment]
Great, thanks for clarifying! 🙂
