### ISSUE TITLE
protein-translation: Codons/Acids table not rendering properly

### ISSUE THREAD

**Issue by Mavelous** [exercism/java#1508]
This is what the "protein-translation" problem page looks like on the Exercism site when I'm logged in (OSX, latest Chrome browser):

<img width="879" alt="screen shot 2018-09-10 at 20 17 35" src="https://user-images.githubusercontent.com/1540661/45331055-a079d300-b536-11e8-8570-3dec025516c6.png">

(I'd provide a direct link, but it's a link to /my/solutions/hash which I think won't translate well to others who aren't me.)

When I view the [same page on GitHub](https://github.com/exercism/java/tree/master/exercises/protein-translation), it looks like this:

<img width="550" alt="screen shot 2018-09-10 at 20 21 08" src="https://user-images.githubusercontent.com/1540661/45331146-1f6f0b80-b537-11e8-974e-f939ea547733.png">

**Comment by FridaTveit** [comment]
Thanks for raising this @Mavelous! 🙂 From looking into it this is a problem on all tracks so it's not something we can fix on this track unfortunately.

The READMEs are specified in the [problem specifications repo](https://github.com/exercism/problem-specifications/blob/master/exercises/protein-translation/description.md), so it might be worth raising an issue about it there? Or maybe in the [exercism.io repo](https://github.com/exercism/exercism)? What do you think @sjwarner-bp? 🙂

**Comment by FridaTveit** [comment]
It looks like you've opened an issue for this in problem-specifications so I'll close this for now @Mavelous. Feel free to ask us (on gitter or by opening a new issue) if you have any problems getting it resolved or you have other questions/suggestions! 🙂
