### ISSUE TITLE
Hacktoberfest Preparation

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/java#1511]
Last year, Hacktoberfest was a hit! I suggest that we maintainers set up the Java repository to allow maximum contributions and ease-of-access for this year too.

A quick (but by no means exhaustive) list of tasks to do before October is:
- [x] Ensure all exercises that are not up to date have open issues
- [ ] Ensure all issues are as granular as possible
- [ ] Add hacktoberfest tag to relevant issues

There are going to be _way_ more things than just these, but this is probably a good start.

What do you think @exercism/java

**Comment by FridaTveit** [comment]
I've opened issues for updating any exercises that aren't up to date 🙂

I've also added the hacktoberfest tag to any issues I thought might be suitable, though feel free to remove it from any issues you don't think are suitable or add it to any other issues you think should have it 🙂

**Comment by FridaTveit** [comment]
We can probably close this now. Thanks for making sure we were prepared @sjwarner-bp! 🙂
