### ISSUE TITLE
gigasecond: rename method

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/java#1513]
A recent discussion in the exercism mentors #track-java Slack channel suggested:

> About `Gigasecond` exercise: why is the method called `getDate`?  Shouldn't it rather be called `getTime` if we talk about seconds?

After some further discussion, `getDateTime` was suggested as a sensible method name, and was decided to be in keeping with the JavaAPI.

Please rename the `getDate` method to `getDateTime`, including useage in reference solutions and tests if applicable.

**Comment by LukBukkit** [comment]
I would take care of this 👍

**Comment by LukBukkit** [comment]
I've also got another question: Is it possible for you to raise the gradle version to 4.7 or higher to support Java 10?

**Comment by FridaTveit** [comment]
Fixed in PR #1549. Thanks @LukBukkit! 🙂

I've raised issue #1556 to discuss your question @LukBukkit, thanks for raising it! 🙂
