### ISSUE TITLE
pangram: update version file (v1.4.0 -> v1.4.1)

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1517]
Please update the version specified in the [pangram](https://github.com/exercism/java/blob/master/exercises/pangram/.meta/version) version file from 1.4.0 to 1.4.1.

Background info: each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. The version can be found at the top of the [canonical data file for that exercise](https://github.com/exercism/problem-specifications/blob/master/exercises/pangram/canonical-data.json).

**Comment by IpshitaC** [comment]
Hi @FridaTveit 
Can I take this up for hacktoberfest?
