### ISSUE TITLE
acronym: update version file (v1.3.0 -> v1.4.0) and add test

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1518]
Please update the version specified in the [acronym](https://github.com/exercism/java/blob/master/exercises/acronym/.meta/version) version file from 1.2.0 to 1.3.0.

Please also add one test to the [acronym tests](https://github.com/exercism/java/blob/master/exercises/acronym/src/test/java/AcronymTest.java). This should be the test "consecutive delimiters" as described in the [canonical data for acronym](https://github.com/exercism/problem-specifications/blob/master/exercises/acronym/canonical-data.json). See [this diff file](https://github.com/exercism/problem-specifications/commit/787d24eabfc82757e1c0c9998244ba6ca1eb4e32#diff-d57bcd2a74447181c8e003b4d373deaf) to make it more obvious which test has been added.

After the new test has been added make sure that the [reference solution](https://github.com/exercism/java/blob/master/exercises/acronym/.meta/src/reference/java/Acronym.java) still passes the tests. If it doesn't then please update the reference solution so that it passes the new test.

Background info: each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. The version can be found at the top of the canonical data file for that exercise.

**Comment by beatbrot** [comment]
Please assign this one to me :)

**Comment by FridaTveit** [comment]
Fixed in PR #1577. Thanks @lemoncurry  and @beatbrot 🙂
