### ISSUE TITLE
isbn-verifier: update version file (v2.5.0 -> v2.7.0) and update tests

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1520]
Please update the version specified in the [isbn-verifier](https://github.com/exercism/java/blob/master/exercises/isbn-verifier/.meta/version) version file from 2.5.0 to 2.7.0.

Please also make sure the [isbn-verifier tests](https://github.com/exercism/java/blob/master/exercises/isbn-verifier/src/test/java/IsbnVerifierTest.java) are up to date with the [canonical data for isbn-verifier](https://github.com/exercism/problem-specifications/blob/master/exercises/isbn-verifier/canonical-data.json). They should contain the same tests in the same order.

After any new tests have been added make sure that the [reference solution](https://github.com/exercism/java/blob/master/exercises/isbn-verifier/.meta/src/reference/java/IsbnVerifier.java) still passes the tests. If it doesn't then please update the reference solution so that it passes all the tests.

Background info: each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. The version can be found at the top of the canonical data file for that exercise.

**Comment by PritamSangani** [comment]
Can I be assigned this issue, please?

**Comment by FridaTveit** [comment]
Fixed in PR #1550. Thanks @PritamSangani! 🙂
