### ISSUE TITLE
isogram: update version file (v1.3.0 -> v1.6.0) and update tests

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1523]
Please update the version specified in the [isogram](https://github.com/exercism/java/blob/master/exercises/isogram/.meta/version) version file from 1.3.0 to 1.6.0.

Please also make sure the [isogram tests](https://github.com/exercism/java/blob/master/exercises/isogram/src/test/java/IsogramCheckerTest.java) are up to date with the [canonical data for isogram](https://github.com/exercism/problem-specifications/blob/master/exercises/isogram/canonical-data.json). They should contain the same tests in the same order.

After any new tests have been added make sure that the [reference solution](https://github.com/exercism/java/blob/master/exercises/isogram/.meta/src/reference/java/IsogramChecker.java) still passes the tests. If it doesn't then please update the reference solution so that it passes all the tests.

Background info: each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. The version can be found at the top of the canonical data file for that exercise.

**Comment by LukBukkit** [comment]
I also would work on this one, if it's okay.
