### ISSUE TITLE
bob: update version file (v1.2.0 -> v1.4.0) and minor changes to tests

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1525]
Please update the version specified in the [bob](https://github.com/exercism/java/blob/master/exercises/bob/.meta/version) version file from 1.2.0 to 1.3.0.

Please also make two minor changes to the [bob tests](https://github.com/exercism/java/blob/master/exercises/bob/src/test/java/BobTest.java) to make them up to date with the [canonical data for bob](https://github.com/exercism/problem-specifications/blob/master/exercises/bob/canonical-data.json):
- The test `shoutingWithNoExclamationMark` should use `bob.hey("I HATE THE DMW")` instead of `bob.hey("I HATE YOU")`. [This diff file](https://github.com/exercism/problem-specifications/commit/a64ef344efc7677e2058e8ee52e6c3edf37238e3#diff-dc41ba274d2b92436918160694c5dbdd) describes the change to the canonical data.

- The test `multipleLineQuestion` should use `bob.hey("\nDoes this cryogenic chamber make me look fat?\nNo")` instead of `bob.hey("\nDoes this cryogenic chamber make me look fat?\nno")`. [This diff file](https://github.com/exercism/problem-specifications/commit/ca7994385d78154e91e85c88ae2d28ef11850ad0#diff-dc41ba274d2b92436918160694c5dbdd) describes the change to the canonical data.

Background info: each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. The version can be found at the top of the canonical data file for that exercise.

**Comment by anurag-rai** [comment]
Hey, if this one is still up for grabs, I'd like to take it on.

**Comment by anurag-rai** [comment]
I've changed the version to 1.4.0 instead of the mentioned 1.3.0 because [this](https://github.com/exercism/problem-specifications/blob/master/exercises/bob/canonical-data.json) specifies so. Same with a test case.

**Comment by FridaTveit** [comment]
Fixed in PR #1576. Thanks @anurag-rai! 🙂
