### ISSUE TITLE
atbash-cipher: update version file (v1.1.0 -> v1.2.0) and update tests

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1527]
Please update the version specified in the [atbash-cipher](https://github.com/exercism/java/blob/master/exercises/atbash-cipher/.meta/version) version file from 1.1.0 to 1.2.0.

Please also make sure the [atbash-cipher tests](https://github.com/exercism/java/blob/master/exercises/atbash-cipher/src/test/java/AtbashTest.java) are up to date with the [canonical data for atbash-cipher](https://github.com/exercism/problem-specifications/blob/master/exercises/atbash-cipher/canonical-data.json). They should contain the same tests in the same order.

After any new tests have been added make sure that the [reference solution](https://github.com/exercism/java/blob/master/exercises/atbash-cipher/.meta/src/reference/java/Atbash.java) still passes the tests. If it doesn't then please update the reference solution so that it passes all the tests.

Background info: each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. The version can be found at the top of the canonical data file for that exercise.

**Comment by mirkoperillo** [comment]
I'm starting to work on this
