### ISSUE TITLE
anagram: update version file (v1.2.0 -> v1.3.0)

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1528]
Please update the version specified in the [anagram](https://github.com/exercism/java/blob/master/exercises/anagram/.meta/version) version file from 1.2.0 to 1.3.0.

Background info: each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. The version can be found at the top of [the canonical data file for that exercise](https://github.com/exercism/problem-specifications/blob/master/exercises/anagram/canonical-data.json).

**Comment by Akash4927** [comment]
I'd like to work on it
