### ISSUE TITLE
clock: update version file (v2.2.1 -> v2.3.0) and add one test

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1530]
Please update the version specified in the [clock](https://github.com/exercism/java/blob/master/exercises/clock/.meta/version) version file from 2.2.1 to 2.3.0.

Please also add one test to the [clock tests](https://github.com/exercism/java/tree/master/exercises/clock/src/test/java). This should be the test "full clock and zeroed clock" as described in the [canonical data for clock](https://github.com/exercism/problem-specifications/blob/master/exercises/clock/canonical-data.json). See [this diff file](https://github.com/exercism/problem-specifications/commit/1680779c0649d05ca895f98fbe913c7c23b55767#diff-1d358f38198325e72002dffc7194ec01) to make it more obvious which test has been added.

Please add the test as the last test in the [`ClockEqualTest.java` file](https://github.com/exercism/java/blob/master/exercises/clock/src/test/java/ClockEqualTest.java).

Background info: each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. The version can be found at the top of the canonical data file for that exercise.

**Comment by sjwarner-bp** [comment]
Closed via #1563
