### ISSUE TITLE
book-store: update version file (v1.3.0 -> v1.4.0) and update tests

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1531]
Please update the version specified in the [book-store](https://github.com/exercism/java/blob/master/exercises/book-store/.meta/version) version file from 1.3.0 to 1.4.0.

Please also make sure the [book-store tests](https://github.com/exercism/java/blob/master/exercises/book-store/src/test/java/BookStoreTest.java) are up to date with the [canonical data for book-store](https://github.com/exercism/problem-specifications/blob/master/exercises/book-store/canonical-data.json). They should contain the same tests in the same order.

After any new tests have been added make sure that the [reference solution](https://github.com/exercism/java/blob/master/exercises/book-store/.meta/src/reference/java/BookStore.java) still passes the tests. If it doesn't then please update the reference solution so that it passes all the tests.

Background info: each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. The version can be found at the top of the canonical data file for that exercise.

**Comment by LukBukkit** [comment]
I'll work on this too 👍
