### ISSUE TITLE
twelve-days: update version file (v1.1.0 -> v1.2.0) and make minor change to tests

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1533]
Please update the version specified in the [twelve-days](https://github.com/exercism/java/blob/master/exercises/twelve-days/.meta/version) version file from 1.1.0 to 1.2.0.

Please also make some minor changes to the [twelve-days tests](https://github.com/exercism/java/blob/master/exercises/twelve-days/src/test/java/TwelveDays.java) to make them up to date with the [canonical data for twelve-days](https://github.com/exercism/problem-specifications/blob/master/exercises/twelve-days/canonical-data.json):
- Every time `On the first day of Christmas my true love gave to me` is repeated it should end with a colon instead of a comma: `On the first day of Christmas my true love gave to me:`. [This diff file](https://github.com/exercism/problem-specifications/commit/84aa47979df7f526bdcb777cacc2c2cc9647dcaa#diff-dcda8ef37a4982f40c53174662e64ebd) describes the change to the canonical data.

Background info: each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. The version can be found at the top of the canonical data file for that exercise.

**Comment by i-vikash** [comment]
I would like to work on this

**Comment by alis0nc** [comment]
I'm working on this

**Comment by alis0nc** [comment]
Nope, looks like this issue is a duplicate of #1514, fixed in PR #1515. I don't see twelve-days 1.3.0 in the canonical data, so I assume 1.2.0 is the current version.

**Comment by FridaTveit** [comment]
Thanks for picking that up @alis0nc! Must have got a bit confused while opening lots of issues in a rush! 😄
