### ISSUE TITLE
variable-length-quantity: update version file (v1.1.0 -> v1.2.0)

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1534]
Please update the version specified in the [variable-length-quantity](https://github.com/exercism/java/blob/master/exercises/variable-length-quantity/.meta/version) version file from 1.1.0 to 1.2.0.

Background info: each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. The version can be found at the top of [the canonical data file for that exercise](https://github.com/exercism/problem-specifications/blob/master/exercises/variable-length-quantity/canonical-data.json).

**Comment by vpondala** [comment]
Let me work on this.

**Comment by FridaTveit** [comment]
Fixed in PR #1552. Thanks @vpondala! 🙂
