### ISSUE TITLE
phone-number: update version file (v1.4.0 -> v1.6.0) and update tests

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1535]
Please update the version specified in the [phone-number](https://github.com/exercism/java/blob/master/exercises/phone-number/.meta/version) version file from 1.4.0 to 1.6.0.

Please also make sure the [phone-number tests](https://github.com/exercism/java/blob/master/exercises/phone-number/src/test/java/PhoneNumberTest.java) are up to date with the [canonical data for phone-number](https://github.com/exercism/problem-specifications/blob/master/exercises/phone-number/canonical-data.json). They should contain the same tests in the same order.

After any new tests have been added make sure that the [reference solution](https://github.com/exercism/java/blob/master/exercises/phone-number/.meta/src/reference/java/PhoneNumber.java) still passes the tests. If it doesn't then please update the reference solution so that it passes all the tests.

Background info: each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. The version can be found at the top of the canonical data file for that exercise.

**Comment by mirkoperillo** [comment]
Hi @FridaTveit, can I help on this ?

**Comment by FridaTveit** [comment]
Hi @mirkoperillo 🙂 Feel free to start working on it! 😄

In general you don't need to ask before working on as issue, just make sure no one else has commented on the ticket recently to say they're working on it and that there are no open pull requests for the issue 🙂

If there are old comments on the issue from someone saying they're working on it, then it's worth adding your own comment to check if they're still working on it 🙂 

Hope that helps, let us know if you have any issues! 🙂
