### ISSUE TITLE
pascals-triangle: update version file (v1.3.0 -> v1.5.0) and remove one test

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1536]
Please update the version specified in the [pascals-triangle](https://github.com/exercism/java/blob/master/exercises/pascals-triangle/.meta/version) version file from 21.3.0 to 1.5.0.

Please also remove the last test from the [pascals-triangle tests](https://github.com/exercism/java/tree/master/exercises/pascals-triangle/src/test/java). This should be the test `testValidatesNotNegativeRows`. See [this diff file](https://github.com/exercism/problem-specifications/commit/ad21beef89c3dcdba2b898b39d91aade7db369c7#diff-4355b236c6ba8355c589624ef3760d8b) to make it more obvious which test has been removed.

Background info: each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. The version can be found at the top of [the canonical data file for that exercise](https://github.com/exercism/problem-specifications/blob/master/exercises/pascals-triangle/canonical-data.json).

**Comment by Akash4927** [comment]
I'd like to work on it.
