### ISSUE TITLE
queen-attack: update version file (v2.1.0 -> v2.2.0)

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1537]
Please update the version specified in the [queen-attack](https://github.com/exercism/java/blob/master/exercises/queen-attack/.meta/version) version file from 2.1.0 to 2.2.0.

Background info: each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. The version can be found at the top of [the canonical data file for that exercise](https://github.com/exercism/problem-specifications/blob/master/exercises/queen-attack/canonical-data.json).

**Comment by princerachit** [comment]
I am working on this.

**Comment by sjwarner-bp** [comment]
Closed via #1564
