### ISSUE TITLE
grade-school: add version file (v1.0.0) and update tests

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1538]
Please add  a version file at https://github.com/exercism/java/blob/master/exercises/grade-school/.meta/version containing version number 1.0.0. See [the phone-number version file](https://github.com/exercism/java/blob/master/exercises/phone-number/.meta/version) for an example version file.

Please also make sure the [grade-school tests](https://github.com/exercism/java/blob/master/exercises/grade-school/src/test/java/SchoolTest.java) are up to date with the [canonical data for grade-school](https://github.com/exercism/problem-specifications/blob/master/exercises/grade-school/canonical-data.json). They should contain the same tests in the same order.

After any new tests have been added, removed or changed make sure that the [reference solution](https://github.com/exercism/java/blob/master/exercises/grade-school/.meta/src/reference/java/School.java) still passes the tests. If it doesn't then please update the reference solution so that it passes all the tests.

Background info: each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. The version can be found at the top of the canonical data file for that exercise.

**Comment by alis0nc** [comment]
I'm working on this issue.

**Comment by FridaTveit** [comment]
Fixed in PR #1572. Thanks @alis0nc 🙂
