### ISSUE TITLE
robot-simulator: update version file (v2.2.0 -> v2.3.0) and update tests

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1539]
Please update the version specified in the [robot-simulator](https://github.com/exercism/java/blob/master/exercises/robot-simulator/.meta/version) version file from 2.2.0 to 2.3.0.

Please also make sure the [robot-simulator tests](https://github.com/exercism/java/blob/master/exercises/robot-simulator/.meta/src/reference/java/Robot.java) are up to date with the [canonical data for robot-simulator](https://github.com/exercism/problem-specifications/blob/master/exercises/robot-simulator/canonical-data.json). They should contain the same tests in the same order.

After any new tests have been added make sure that the [reference solution](https://github.com/exercism/java/blob/master/exercises/robot-simulator/.meta/src/reference/java/Robot.java) still passes the tests. If it doesn't then please update the reference solution so that it passes all the tests.

Background info: each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. The version can be found at the top of the canonical data file for that exercise.

**Comment by mirkoperillo** [comment]
Hi,
I'm starting to work on this
