### ISSUE TITLE
binary-search: update version file (v1.1.0 -> v1.2.0) and update error handling

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1540]
Please update the version specified in the [binary-search](https://github.com/exercism/java/blob/master/exercises/binary-search/.meta/version) version file from 1.1.0 to 1.2.0.

Please also make sure that the expected error handling in the [robot-simulator tests](https://github.com/exercism/java/blob/master/exercises/binary-search/src/test/java/BinarySearchTest.java) is up to date with the [canonical data for binary-search](https://github.com/exercism/problem-specifications/blob/master/exercises/binary-search/canonical-data.json). Currently we expect a solution to binary-search to return -1 if the value searched for is not present. However the canonical data now indicates that this should cause an error in a way that is idiomatic to the language. I suggest throwing an exception in that case. Thoughts @exercism/java? 🙂 

After any changes have been made to the tests make sure that the [reference solution](https://github.com/exercism/java/blob/master/exercises/binary-search/.meta/src/reference/java/BinarySearch.java) still passes the tests. If it doesn't then please update the reference solution so that it passes all the tests.

Background info: each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. The version can be found at the top of the canonical data file for that exercise.

**Comment by chungngoops** [comment]
I am working on this issue.

**Comment by anurag-rai** [comment]
Had implemented this earlier with a new Exception. Made a PR regarding the same.

**Comment by anurag-rai** [comment]
@chungngoops Hey, I'm so sorry I didn't see your comment before making my PR. We had the same idea to use Exception though :)

**Comment by chungngoops** [comment]
@anurag-rai, no problem bro! Happy to work on other issues!

**Comment by RonakLakhotia** [comment]
@FridaTveit is this issue still valid?

**Comment by FridaTveit** [comment]
@RonakLakhotia Yes, it is 🙂

**Comment by RonakLakhotia** [comment]
I will attempt this issue and submit a PR. 👍
