### ISSUE TITLE
Should we increase the gradle version?

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1556]
As posted by @LukBukkit on issue #1513:
> Is it possible for you to raise the gradle version to 4.7 or higher to support Java 10?

What do we think @exercism/java? 🙂

**Comment by Smarticles101** [comment]
Increasing the gradle version get's my vote 😄

**Comment by FridaTveit** [comment]
Fixed in PR #1551. Thanks @vpondala and @LukBukkit! 😄
