### ISSUE TITLE
Travid build showing as pending

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1579]
For a few PRs the Travis build appears to get stuck at pending. However when you click through to the build it has actually finished. Examples:

- PR #1562 https://travis-ci.org/exercism/java/builds/435738107?utm_source=github_status&utm_medium=notification
- PR #1567 https://travis-ci.org/exercism/java/builds/435727735?utm_source=github_status&utm_medium=notification
- PR #1570 https://travis-ci.org/exercism/java/builds/435738118?utm_source=github_status&utm_medium=notification

Any ideas what's going on @exercism/java?

**Comment by sjwarner-bp** [comment]
That's really odd. Some kind of display issue?

I fixed the CI on Kotlin's track last night and used mostly the same as what we have over here...

I'll keep an eye out if the same issue appears in Kotlin track too :+1:

**Comment by FridaTveit** [comment]
I restarted them all and they then worked fine (though one of them first failed with a timeout error and needed to be restarted again...). Possibly it's because so many PRs were openened around the same time?
