### ISSUE TITLE
Should we use a test generator?

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1580]
As suggested by @beatbrot:
> How do you think about creating Unit-Tests out of the canonical-data.json?
I could work on that, If you want me to :)

What do we think about creating an automatic test generator @exercism/java? 🙂

**Comment by sjwarner-bp** [comment]
That would be interesting. I think the F# track have had good success with this.

Depends how much we already deviate from the current suites though :thinking:

**Comment by beatbrot** [comment]
Question is also: Do we want to have a generator that generates actual Java Code with @Test methods? 

Or would we rather want to have a @Test-Method that processes the json-File?

**Comment by jmrunkle** [comment]
Closing this as an abandoned idea. Since we can often create better assertions ourselves manually for each test class, I am generally against this approach anyway (it is also likely to require more work from the maintainers).
