### ISSUE TITLE
scrabble-score: remove instance variable

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#1595]
In the [scrabble-score tests](https://github.com/exercism/java/blob/master/exercises/scrabble-score/src/test/java/ScrabbleScoreTest.java) a private instance variable is used. However it's constructed with different parameters in each test therefore it doesn't need to be an instance variable. Having it as a local variable in each test will make it clear that it's different for each test and not shared between them.

Therefore please remove the private variable and change each test from, e.g. 

```
scrabble = new Scrabble("a");
```

to

```
Scrabble scrabble = new Scrabble("a");
```

**Comment by PierrePIRONIN** [comment]
My little contribution ;)
