### ISSUE TITLE
Java: Pig Latin & Anagram

### ISSUE THREAD

**Issue by mycahmason** [exercism/java#1624]
It seems that the Pig Latin & Anagram lessons under the Java track are missing the main java files in the /src/main/java directories.

Thanks.

**Comment by FridaTveit** [comment]
Hi @mycahmason, thanks for raising this issue 🙂 Pig latin has difficulty 5 and anagram has difficulty 7. According to our [policies](https://github.com/exercism/java/blob/master/POLICIES.md#starter-implementations) we don't provide starter implementation for exercises with difficulty 5 or above. So the files aren't missing, they're intentionally not provided 🙂 Does that make sense?

**Comment by mycahmason** [comment]
Thanks for the explanation @FridaTveit that does make sense and I do see the explanation in the Pig Latin exercise. I think I must have mixed myself up while working on Anagram and missed it, oops :innocent:

Thanks again.
