### ISSUE TITLE
Missing file from the pig-latin exercise

### ISSUE THREAD

**Issue by dangoth** [exercism/java#1638]
Not sure if this is intended, but the \src\main\java\ class file is missing.

**Comment by FridaTveit** [comment]
This is intended. As you can see for our [policies doc](https://github.com/exercism/java/blob/master/POLICIES.md#starter-implementations) only exercises with difficulty 4 or lower should have starter implementations. And pig-latin is difficulty 5 as you can see in [config.json](https://github.com/exercism/java/blob/master/config.json) 🙂
