### ISSUE TITLE
Exercise benchmarks

### ISSUE THREAD

**Issue by Smarticles101** [exercism/java#1647]
I propose adding benchmarks to each exercise.

I've been working on the [java analyzer](https://github.com/exercism/java-analyzer), and decided to share about it [on reddit, where a discussion was started](https://www.reddit.com/r/programming/comments/b915x3/static_analysis_for_exercismio_in_java/ek3437f/?utm_source=share&utm_medium=web2x).

The "optimal solution" the analyzer looks for for two-fer is this:
```java
import java.util.Optional;

class Twofer {
  String twofer(String name) {
    return String.format("One for %s, one for me.", Optional.ofNullable(name).orElse("you"));
  }
}
```

I've come to find out, based off of the reddit discussion, that [`String.format` is incredibly slow](https://redfin.engineering/java-string-concatenation-which-way-is-best-8f590a7d22a8).

I think that, if we add benchmarks to exercises, it would add discussion points about speed, with actual data to back it up.

**Comment by jmrunkle** [comment]
This issue never got much attention, so I'm going to close it.

I think that it is infeasible to add it to all exercises, but if someone wanted to make a pull request for one or two exercises where performance matters (I'm thinking the list implementations could be interesting) then I'd be happy to review those.
