### ISSUE TITLE
binary-search: integer overflow is possible in solution

### ISSUE THREAD

**Issue by wolf99** [exercism/java#1658]
https://github.com/exercism/java/blob/580118a3a555fad422b9a7fdf5042e1533a2f389/exercises/binary-search/.meta/src/reference/java/BinarySearch.java#L24

It's possible for the sum to cause integer overflow.
The expression should be changed to safer `middle = (int) Math.floor(left + (right - left) / 2);`

**Comment by lemoncurry** [comment]
@wolf99 Thank you for your suggestion!
If in the next few days no other maintainer objects feel free to open a pull request if you want 🙂
