### ISSUE TITLE
Change label 'good first patch' to GitHub default 'good first issue'

### ISSUE THREAD

**Issue by lemoncurry** [exercism/java#1669]
I propose to change the label `good first patch` to the [GitHub default](https://help.github.com/en/articles/about-labels#using-default-labels) `good first issue` for consistency.
Since the label `good first issue`is a default label, it is most likely the standard label searched by (first time) contributors.

What do you think, @exercism/java ?

If no one objects to this change, the [policy for first patches](https://github.com/exercism/java/blob/a0f91066641f672d1d77b2a3f07df3732c9096b4/POLICIES.md#good-first-patches) will need an update (wording).

**Comment by FridaTveit** [comment]
I'm happy with that 🙂

**Comment by Smarticles101** [comment]
I've thought about this before and am happy with the change. 👍
