### ISSUE TITLE
Create script for automated issue submission for new exercises and test updates

### ISSUE THREAD

**Issue by lemoncurry** [exercism/java#1670]
I suggest to create a script that opens up new issues for needed test updates or new exercises entered into the [problem specification repo](https://github.com/exercism/problem-specifications).

GitHub offers [query parameters](https://help.github.com/en/articles/about-automation-for-issues-and-pull-requests-with-query-parameters) to open up new issues and fill it with title, body, labels...
Existing issues could be checked via the [GitHub API](https://api.github.com/) to avoid duplicates.

I would gladly work on that if you would welcome such a tool for maintaining this track.
What do you think @exercism/java?

**Comment by FridaTveit** [comment]
Sounds like a great idea! 😄

**Comment by Smarticles101** [comment]
This would be nice to have!
