### ISSUE TITLE
saddle-points: update tests and version file (v1.3.0 -> v1.5.0)

### ISSUE THREAD

**Issue by lemoncurry** [exercism/java#1683]
The tests for the [saddle-points exercise](https://github.com/exercism/java/tree/master/exercises/saddle-points/src/test/java) are not up-to-date with the [canonical data](https://github.com/exercism/problem-specifications/tree/master/exercises/saddle-points/canonical-data.json).
To check what has changed and if new tests have been added to the canonical data, please have a look at the [commit history](https://github.com/exercism/problem-specifications/commits/master/exercises/saddle-points/canonical-data.json) of the canonical data file for the exercise saddle-points.
Please update version and/or test file, and, if the new test(s) fail, fix the reference implementation.
Feel free to leave a comment if you have any questions. 

Background info: each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. The version can be found at the top of the [canonical data file](https://github.com/exercism/problem-specifications/tree/master/exercises/saddle-points/canonical-data.json) for that exercise.

**Comment by hgvanpariya** [comment]
@lemoncurry : Please share your review comments for the PR...

**Comment by hgvanpariya** [comment]
@lemoncurry : the Testcase and the canonical-data has same test cases.


https://github.com/exercism/java/blob/master/exercises/saddle-points/src/test/java/MatrixTest.java

https://github.com/exercism/problem-specifications/blob/master/exercises/saddle-points/canonical-data.json

**Comment by lemoncurry** [comment]
@hgvanpariya Yes, but there was a [massive change (from 1.3.0 -> 1.4.0)](https://github.com/exercism/problem-specifications/commit/a792d210024d8d5765663e685429fe885c81c201#diff-529456e916d0421033a0e79d3e96f03b) concerning indexing that affects all expected values for the tests and likely a fix to the reference implementation may be warranted.

These values need to be changed to the values provided in the [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/saddle-points/canonical-data.json) for this exercise.
