### ISSUE TITLE
triangle: update tests and version file (v1.2.0 -> v1.2.1)

### ISSUE THREAD

**Issue by lemoncurry** [exercism/java#1685]
The tests for the [triangle exercise](https://github.com/exercism/java/tree/master/exercises/triangle/src/test/java) are not up-to-date with the [canonical data](https://github.com/exercism/problem-specifications/tree/master/exercises/triangle/canonical-data.json).
To check what has changed and if new tests have been added to the canonical data, please have a look at the [commit history](https://github.com/exercism/problem-specifications/commits/master/exercises/triangle/canonical-data.json) of the canonical data file for the exercise triangle.
Please update version and/or test file, and, if the new test(s) fail, fix the reference implementation.
Feel free to leave a comment if you have any questions. 

Background info: each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. The version can be found at the top of the [canonical data file](https://github.com/exercism/problem-specifications/tree/master/exercises/triangle/canonical-data.json) for that exercise.

**Comment by ThiagoSousaSantana** [comment]
Hi, i would like to fix this issue and will be my first contribution. To fix, I need to update the class test with new data and new test cases that are in the canonical data and update the version in the file version. The files are in the `.meta` folder, right?

**Comment by ThiagoSousaSantana** [comment]
One more question, method names have to be the same as the description in canonical data?

**Comment by lemoncurry** [comment]
Thank you @ThiagoSousaSantana  for wanting to contribute.
The changes that happened from 1.2.0 to 1.2.1 were changes in the description of each test. You are free to decide if you want to change some method names for the tests or not (e.g. change to shorter descriptions now provided int he canonical data). We don't have to copy the description text of the test in the canonical data to our test method names 1:1.

**Comment by ThiagoSousaSantana** [comment]
Thanks @lemoncurry for helping me, I will open my pull request.
