### ISSUE TITLE
yacht: update tests and version file (v1.1.0 -> v1.2.0)

### ISSUE THREAD

**Issue by lemoncurry** [exercism/java#1687]
The tests for the [yacht exercise](https://github.com/exercism/java/tree/master/exercises/yacht/src/test/java) are not up-to-date with the [canonical data](https://github.com/exercism/problem-specifications/tree/master/exercises/yacht/canonical-data.json).
To check what has changed and if new tests have been added to the canonical data, please have a look at the [commit history](https://github.com/exercism/problem-specifications/commits/master/exercises/yacht/canonical-data.json) of the canonical data file for the exercise yacht.
Please update version and/or test file, and, if the new test(s) fail, fix the reference implementation.
Feel free to leave a comment if you have any questions. 

Background info: each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. The version can be found at the top of the [canonical data file](https://github.com/exercism/problem-specifications/tree/master/exercises/yacht/canonical-data.json) for that exercise.

**Comment by hgvanpariya** [comment]
@lemoncurry : Please share your review comments for the PR ...
