### ISSUE TITLE
Typo in test for Java Pig Latin Problem

### ISSUE THREAD

**Issue by McEileen** [exercism/java#1692]
Hi, there are two small typos in the tests for the java track's Pig Latin problem.  One test is titled [`testYtTreatedLikeAConsonantAtTheBeginningOfAWord`](https://github.com/exercism/java/blob/master/exercises/pig-latin/src/test/java/PigLatinTranslatorTest.java#L112) when as the instructions note, Yt should be treated like a vowel.  The test itself is correct, but the title appears to be a typo.  Similarly, a test for the word yellow is titled [`testYTreatedLikeAConsonantAtTheBeginningOfAWord`](https://github.com/exercism/java/blob/master/exercises/pig-latin/src/test/java/PigLatinTranslatorTest.java#L124)

I'd be happy to submit a small PR to fix this.

Also, I wasn't sure if I should open the issue in this repo or in the `exercism/java` repo.  I went with this repo because it's the one linked to from exercism's [contribute page](https://exercism.io/contribute).  Let me know what's best for the future, thanks.

**Comment by iHiD** [comment]
Hello. Thank you for opening the issue. Regarding which repository, exercism/exercism is always good because I can move it to the correct place if needed. In this case I'll move it to Java and let @exercism/java guide you further. I suspect a PR would be welcome but I'll let them confirm :)

**Comment by iHiD** [comment]
Also worth noting that the second example seems to be in the [canonical problem-specification](https://github.com/exercism/problem-specifications/blob/master/exercises/pig-latin/canonical-data.json#L173) so may be wrong on all tracks.

**Comment by McEileen** [comment]
Ok, thanks!  I'll wait to hear from exercism/java.

**Comment by lemoncurry** [comment]
Thank you @McEileen for bringing this to our attention.
It appears that [testYtTreatedLikeAConsonantAtTheBeginningOfAWord()](https://github.com/exercism/java/blob/master/exercises/pig-latin/src/test/java/PigLatinTranslatorTest.java#L112) and the following test [testXrTreatedLikeAConsonantAtTheBeginningOfAWord()](https://github.com/exercism/java/blob/master/exercises/pig-latin/src/test/java/PigLatinTranslatorTest.java#L118) have a wrong method name and should refer to single vowels, as noticed by you.
You may open a PR to fix this if you want 👍 or we do it as soon as possible. 

Why do you think the test name [testYTreatedLikeAConsonantAtTheBeginningOfAWord](https://github.com/exercism/java/blob/master/exercises/pig-latin/src/test/java/PigLatinTranslatorTest.java#L124) is wrong?
