### ISSUE TITLE
Not all non-core exercises are unlocked

### ISSUE THREAD

**Issue by wolf99** [exercism/java#1695]
According to the config.json, some exercises should be unlocked by completing linked-list, but they are not (in fact they should be all unlocked by that stage as it appears to be the last core exercise).
e.g. diffie-hellman
https://github.com/exercism/java/blob/c5132d3a955556699c1e8e353c085039d1c3b619/config.json#L1264

linked-list completed:
![image](https://user-images.githubusercontent.com/281700/58510975-cb25bd80-8191-11e9-823d-305ab33c3c4f.png)

But remaining non-core exercises not unlocked:
![image](https://user-images.githubusercontent.com/281700/58511031-e5f83200-8191-11e9-842e-b61931beee04.png)

Unsure why this would occur, so could actually be an Exercism issue rather than a Java track issue.

**Comment by lemoncurry** [comment]
Thank you @wolf99 for bringing this issue to our attention.
Could you access the locked exercises in the meantime?

If not, I think this might be an issue with the website.
On the website, I see there are community solutions as recent as May 27, 2019 for exercises unlocked by "linked-list".
So I would suggest to open your issue at [exercism/exercism](https://github.com/exercism/exercism).

**Comment by lemoncurry** [comment]
[Resolved](https://github.com/exercism/exercism/issues/4881), so this issue can be closed.
