### ISSUE TITLE
Allow leap, grains, and say exercise to be implemented

### ISSUE THREAD

**Issue by lemoncurry** [exercism/java#1712]
The issue opened by @jmrunkle had an [interesting side discussion](https://github.com/exercism/exercism/issues/4932) about the reasoning of not allowing the three exercises `leap`, `grain`and `say` to be implemented in the Java track.
Back in 2014, it [was decided](https://github.com/exercism/java/issues/3) out of caution to not allow an implementation of these exercises in Java.
It appears now that [there are no longer concerns](https://github.com/exercism/exercism/issues/4932#issuecomment-511625328) about licensing issues, as long as we provide attribution and add our own description of the exercise.

JavaRanch as source for these exercises is mentioned in exercism/problem-specifications.
I checked the problem descriptions by JavaRanch for each exercise and the descriptions in exercism/problem-specifications and they differ, in the case of the exercise `grains` only slightly (the description is almost identical).
'grains' is the only exercise where I don't know if [the problem description](https://github.com/exercism/problem-specifications/blob/master/exercises/grains/description.md) might be too close to the [original exercise description](https://javaranch.com/grains.jsp) on JavaRanch.

So I would propose to remove `leap`and `say` from the list of foregone exercises in the config.json and allow implementations.
Concerning `grains`, I think there needs to be more discussion and/or a change in the exercise description.

What do you think @exercism/java ?

**Comment by FridaTveit** [comment]
I think that sounds like a great plan 🙂

**Comment by Smarticles101** [comment]
I say let's do it!
