### ISSUE TITLE
etl: update tests and version file (v1.0.0 -> v2.0.1)

### ISSUE THREAD

**Issue by lemoncurry** [exercism/java#1716]
The tests for the [etl exercise](https://github.com/exercism/java/tree/master/exercises/etl/src/test/java) are not up-to-date with the [canonical data](https://github.com/exercism/problem-specifications/tree/master/exercises/etl/canonical-data.json).
To check what has changed and if new tests have been added to the canonical data, please have a look at the [commit history](https://github.com/exercism/problem-specifications/commits/master/exercises/etl/canonical-data.json) of the canonical data file for the exercise etl.
Please update version and/or test file, and, if the new test(s) fail, fix the reference implementation.
Feel free to leave a comment if you have any questions. 

Background info: each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. The version can be found at the top of the [canonical data file](https://github.com/exercism/problem-specifications/tree/master/exercises/etl/canonical-data.json) for that exercise.

**Comment by tr808axm** [comment]
As far as I can see, the updates to the canonical data file only involved changes in description, formatting and structure of the file. Should I add a pull request for bumping the version in `.meta/`?
