### ISSUE TITLE
pangram: update tests and version file (v1.4.1 -> v2.0.0)

### ISSUE THREAD

**Issue by lemoncurry** [exercism/java#1717]
The tests for the [pangram exercise](https://github.com/exercism/java/tree/master/exercises/pangram/src/test/java) are not up-to-date with the [canonical data](https://github.com/exercism/problem-specifications/tree/master/exercises/pangram/canonical-data.json).
To check what has changed and if new tests have been added to the canonical data, please have a look at the [commit history](https://github.com/exercism/problem-specifications/commits/master/exercises/pangram/canonical-data.json) of the canonical data file for the exercise pangram.
Please update version and/or test file, and, if the new test(s) fail, fix the reference implementation.
Feel free to leave a comment if you have any questions. 

Background info: each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. The version can be found at the top of the [canonical data file](https://github.com/exercism/problem-specifications/tree/master/exercises/pangram/canonical-data.json) for that exercise.

**Comment by barisozcanli** [comment]
@lemoncurry 
Hi! May I fix this?
As far as I see, test inputs haven't changed since last version but descriptions are slimmed down. So, renaming tests (method names in PangramCheckerTest) might be a good idea? 
I'm a beginner. Should I assign the issue to myself?

**Comment by lemoncurry** [comment]
@barisozcanli Thank you for wanting to contribute!
Yes, of course you may work on this issue.

As you already have said, it appears that the descriptions were changed so that the method names may be shorter and easier to read. You don't have to stick 100% to the new descriptions and may decide on shorter method names.
