### ISSUE TITLE
Transition from travis to actions

### ISSUE THREAD

**Issue by Smarticles101** [exercism/java#1726]
Would it be worth it to transition the ci tests from travis over to github actions? I'd be willing to work on transferring it over if we want to

**Comment by lemoncurry** [comment]
I'm not sure if we should transfer, but I also have not familiarized myself with  possible advantages of using github actions vs. travis for ci. I just know that travis is just working fine right now.
Do you know of any advantages @Smarticles101 ?

**Comment by lemoncurry** [comment]
@Smarticles101 Recently I used GitHub Actions for a university project and I really liked the brevity of the description of some action and the user interface. I would now say it is worth to transfer to Github Actions.
Would you still be interested?

**Comment by dector** [comment]
I think that in Kotlin track we are also interested in moving to github actions. Should we discuss implementation details?

**Comment by jmrunkle** [comment]
Well, this experiment is going well. I like the GitHub actions better than Travis CI, so I'll throw together a PR to turn down travis.

**Comment by jmrunkle** [comment]
@dector - feel free to copy what I did here over to Kotlin: https://github.com/exercism/java/blob/master/.github/workflows/gradle.yml

**Comment by dector** [comment]
@jmrunkle Thanks!
