### ISSUE TITLE
word-count: update tests and version file (v1.3.0 -> v1.4.0)

### ISSUE THREAD

**Issue by lemoncurry** [exercism/java#1731]
The tests for the [word-count exercise](https://github.com/exercism/java/tree/master/exercises/word-count/src/test/java) are not up-to-date with the [canonical data](https://github.com/exercism/problem-specifications/tree/master/exercises/word-count/canonical-data.json).
To check what has changed and if new tests have been added to the canonical data, please have a look at the [commit history](https://github.com/exercism/problem-specifications/commits/master/exercises/word-count/canonical-data.json) of the canonical data file for the exercise word-count.
Please update version and/or test file, and, if the new test(s) fail, fix the reference implementation.
Feel free to leave a comment if you have any questions. 

Background info: each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. The version can be found at the top of the [canonical data file](https://github.com/exercism/problem-specifications/tree/master/exercises/word-count/canonical-data.json) for that exercise.

**Comment by RushikeshSawant** [comment]
Hi, I would like to work on this for Hacktoberfest. Please assign to me.

**Comment by lemoncurry** [comment]
> Hi, I would like to work on this for Hacktoberfest. Please assign to me.

Of course. Thank you for wanting to contribute!

**Comment by androidmason** [comment]
Is anyone working on this? I can raise my pull request otherwise.

**Comment by lemoncurry** [comment]
@RushikeshSawant Are you currently working on this issue?

**Comment by RushikeshSawant** [comment]
Hi, yes, I am on this one-  will have a PR soon

**Comment by lemoncurry** [comment]
@RushikeshSawant Ok, great!

@androidmason This issue is still assigned to @RushikeshSawant .

**Comment by lemoncurry** [comment]
@RushikeshSawant It has now been 15 days since this issue was assigned to you. I will now open up again for other interested contributors to work on.

**Comment by monil** [comment]
I would take it up
