### ISSUE TITLE
Incorrectly binded nodes still pass the tests in Linked list exercise for the java track

### ISSUE THREAD

**Issue by Ppapierski** [exercism/java#1734]
Hello, 

during implementing the exercise it hit me that even though I've wrongly implemented binding the nodes the tests still pass.
`public T pop() {
        T value = tail.getValue();
        tail = tail.getPrev();

        if (tail != null) {
            tail.setPrev(null); // should be  -> tail.setNext(null)
        }
        return value;
    }

    public T shift() {
        T value = head.getValue();
        head = head.getNext();

        if (head != null) {
            head.setPrev(null);
        }
        return value;
    }`
 It can be fixed pretty easily by adding a third element to the list in each test.

**Comment by lemoncurry** [comment]
Hi @Ppapierski , thank you for submitting this issue, I will have a closer look until the end of this week.
