### ISSUE TITLE
matrix: update tests and version file (v1.1.0 -> v1.3.0)

### ISSUE THREAD

**Issue by lemoncurry** [exercism/java#1736]
The tests for the [matrix exercise](https://github.com/exercism/java/tree/master/exercises/matrix/src/test/java) are not up-to-date with the [canonical data](https://github.com/exercism/problem-specifications/tree/master/exercises/matrix/canonical-data.json).
To check what has changed and if new tests have been added to the canonical data, please have a look at the [commit history](https://github.com/exercism/problem-specifications/commits/master/exercises/matrix/canonical-data.json) of the canonical data file for the exercise matrix.
Please update version and/or test file, and, if the new test(s) fail, fix the reference implementation.
Feel free to leave a comment if you have any questions. 

Background info: each exercise which has canonical data should have a version file. This file states which version of the canonical data the exercise implements. The version can be found at the top of the [canonical data file](https://github.com/exercism/problem-specifications/tree/master/exercises/matrix/canonical-data.json) for that exercise.

**Comment by sonapraneeth-a** [comment]
@lemoncurry , Shall I pick this up?

**Comment by lemoncurry** [comment]
> @lemoncurry , Shall I pick this up?

@sonapraneeth-a Yes, you can work on it :smile:

**Comment by sonapraneeth-a** [comment]
@lemoncurry , I seem to get some check style issues in the PR. Not sure what are they? Could you please help me understand them, so that I can ensure a clean build?
