### ISSUE TITLE
linked-list: fix test cases for pop() method

### ISSUE THREAD

**Issue by lemoncurry** [exercism/java#1737]
Description of the bug is described in issue #1734.

Please add an additional element to the [test cases](https://github.com/exercism/java/blob/master/exercises/linked-list/src/test/java/DoublyLinkedListTest.java) "testPushPop()" and "testUnshiftPop()" to uncover a faulty implementation of the pop() method.

**Comment by ericbalawejder** [comment]
Do you think that the method names (push, pop, shift, unshift) are ambiguous with the current test coverage? It doesn't seem that `shift()` removes a node from the list, only returns a value. Only until you reach the last test can you conclude it removes a node. If you implement all the methods backwards, you can pass all the tests except for the last 3 lines of the last test:
```
assertThat(list.shift(), is("forty"));
assertThat(list.pop(), is("fifty"));
assertThat(list.shift(), is("thirty"));
```
Do you think it is better to name them based on their actions such as `addFront()`, `addAtEnd()`, `removeFront()`, `removeEnd()` or `removeTail()` etc?

**Comment by myluco** [comment]
I can work on it

**Comment by lemoncurry** [comment]
> Do you think it is better to name them based on their actions such as `addFront()`, `addAtEnd()`, `removeFront()`, `removeEnd()` or `removeTail()` etc?

Thank you for your suggestion.
The test names should be equal to the method names specified in the README.md of the exercise. In the [README.md](https://github.com/exercism/java/tree/master/exercises/linked-list) there is also a short explanation about what the method should do next to the method names.

If you think other method names could improve the exercise, please submit an issue concerning the instructions (README.md) of this exercise [here](https://github.com/exercism/problem-specifications).

**Comment by lemoncurry** [comment]
> I can work on it

@myluco Thank you for wanting to contribute! There is already an open PR that fixes this issue.
