### ISSUE TITLE
Simple question (adding new exercise)

### ISSUE THREAD

**Issue by laritzalba** [exercism/java#1740]
Hi ,
I’would like to add a new exercise, in CONTRIBUTING.md is said that you need to open a pull request in “exercism/problem-specifications”, but for the moment they allow us to open a pull request directly in the track,
“If you would like to add a new exercise to your track, please do it as a track-specific exercise for now, and we can discuss generalising it into this repository further down the line” (exercism/problem-specifications#1560). 
My question is, can I open a pull request (with a new exercise) directly in the this (java) track or not?

If the answer is positive, can I add any exercise that I want or there is a list of exercise to be implemented?

**Comment by lemoncurry** [comment]
@laritzalba We have over 15 exercises that are not yet implemented in the Java language. Issues concerning these exercises will be opened at the beginning of October. So there will be a lot of possibilities to contribute :smile:

**Comment by laritzalba** [comment]
This is good news. But I’ve already implemented a completely new exercise (readme, instruction, test, hint, etc.). It’s about Object Oriented Programming (class creation, heritance, polymorphism, etc.) and If I can add it, it would be nice 🙂 .
So, may I create a pull request, or do I only have to implement the upcoming issues?

**Comment by lemoncurry** [comment]
In that case, if you have already created a completely new exercise, you may open a PR, and we will review it and decide whether to add that exercise to the Java track.

**Comment by laritzalba** [comment]
Thanks a lot 😃
