### ISSUE TITLE
Some nice feedback

### ISSUE THREAD

**Issue by iHiD** [exercism/java#1741]
@exercism/java We just received this lovely email :)

(Feel free to close this when everyone's had chance to read it)

---

I'm not one to do this, but:

I'd just like to personally thank whoever wrote the docs on how to install Java with the JDK and everything on Windows. 
I'm mainly used to Linux installations without having any Java experience, so going through tons of shitty websites with confusing articles from Java pro's that expect you to know what every 3-lettered term means was about as fun as eating glass, finding your simple 3 command copy paste tutorial was a breath of fresh air. 
Thank you so much from the bottom of my heart.

Cheers
Luke

**Comment by Smarticles101** [comment]
That's awesome! Doesn't look like that info has been changed much recently, I believe @jtigger wrote most of what's current in #136

**Comment by jtigger** [comment]
Hey @iHiD!  Thanks for taking the time to express your gratitude.  It delights me to know that the effort in crafting those instructions weren't just to satisfy my own OCD... but brought someone real practical value. 😃

Cheers!

**Comment by jtigger** [comment]
Thanks for @-mentioning me, @Smarticles101 in this ticket.  I wouldn't have seen it otherwise. 🙏🏻
