### ISSUE TITLE
grains: implement exercise

### ISSUE THREAD

**Issue by lemoncurry** [exercism/java#1744]
The exercise **grains** has not been implemented yet for the Java track. 
The description of the exercise can be found in the [problem specification repository](https://github.com/exercism/problem-specifications/tree/master/exercises/grains). 

How to implement a new exercise for the Java track is described in detail in [CONTRIBUTING.md](https://github.com/exercism/java/blob/master/CONTRIBUTING.md#adding-a-new-exercise). Please have a look there first before starting working on the exercise. 
Also please make sure it is clear that you are currently working on this issue, either by asking to be assigned to it, or by opening an empty PR. 

When opening an PR, please reference this issue using any of the [closing keywords](https://help.github.com/en/articles/closing-issues-using-keywords). 

If you have had a look at the exercise description and you concluded that the exercise might not be possible to implement in the Java language, please leave a comment and describe the problem. 

In case you have any further questions, feel free to ask here.

**Comment by Kineolyan** [comment]
Hello @lemoncurry, I'd like to work on this one. Cheers

**Comment by Kineolyan** [comment]
Hello @lemoncurry I forgot about the reference implementation, which I now added to the PR.
I am waiting to see if the tests are passing.

**Comment by Kineolyan** [comment]
The PR is now ready and passing all integration tests on TravisCI. I let you review it.
