### ISSUE TITLE
hangman: implement exercise

### ISSUE THREAD

**Issue by lemoncurry** [exercism/java#1745]
The exercise **hangman** has not been implemented yet for the Java track. 
The description of the exercise can be found in the [problem specification repository](https://github.com/exercism/problem-specifications/tree/master/exercises/hangman). 

How to implement a new exercise for the Java track is described in detail in [CONTRIBUTING.md](https://github.com/exercism/java/blob/master/CONTRIBUTING.md#adding-a-new-exercise). Please have a look there first before starting working on the exercise. 
Also please make sure it is clear that you are currently working on this issue, either by asking to be assigned to it, or by opening an empty PR. 

When opening an PR, please reference this issue using any of the [closing keywords](https://help.github.com/en/articles/closing-issues-using-keywords). 

If you have had a look at the exercise description and you concluded that the exercise might not be possible to implement in the Java language, please leave a comment and describe the problem. 

In case you have any further questions, feel free to ask here.

**Comment by Kineolyan** [comment]
Hello @lemoncurry I will try this one tomorrow.
I plan to do it with RxJava, but I don't completely understand how I am supposed to detail that in the "language/track specific files for this exercise". Do you have an example?

Cheers

**Comment by Kineolyan** [comment]
Hello @lemoncurry , I have a nice exercise for hangman, based on RxJava.
It is passing locally when I use gradle on the right folder but it is not passing with the script _unit-tests.sh_ as the dependency to RxJava is never installed.
I haven't found how to specify that this dependency must be installed. I lookt at the other projects but I haven't found something similar. Can you lead me in the right direction?

**Comment by Kineolyan** [comment]
Hello again, I don't really know how to continue this issue. I have a problem following the exercise statement and I have tests passing locally.
The issue is that the exercise requires the use of an external library and I can't find how to install that dependency for the CI. Can you help? I have looked at other exercises but I couldn't find anything similar.

**Comment by lemoncurry** [comment]
@Kineolyan See my comment in your PR #1758
