### ISSUE TITLE
high-scores: implement exercise

### ISSUE THREAD

**Issue by lemoncurry** [exercism/java#1746]
The exercise **high-scores** has not been implemented yet for the Java track. 
The description of the exercise can be found in the [problem specification repository](https://github.com/exercism/problem-specifications/tree/master/exercises/high-scores). 

How to implement a new exercise for the Java track is described in detail in [CONTRIBUTING.md](https://github.com/exercism/java/blob/master/CONTRIBUTING.md#adding-a-new-exercise). Please have a look there first before starting working on the exercise. 
Also please make sure it is clear that you are currently working on this issue, either by asking to be assigned to it, or by opening an empty PR. 

When opening an PR, please reference this issue using any of the [closing keywords](https://help.github.com/en/articles/closing-issues-using-keywords). 

If you have had a look at the exercise description and you concluded that the exercise might not be possible to implement in the Java language, please leave a comment and describe the problem. 

In case you have any further questions, feel free to ask here.

**Comment by JeffMartian** [comment]
Hi @lemoncurry I would like to take on this exercise if possible.

**Comment by andrerfcsantos** [comment]
@CodeMartian still interested in working on this?

**Comment by vorenusCoA** [comment]
@andrerfcsantos Hi, if it is possible I would like to work on this one. I was thinking on using the already existing code and making the necessary changes based on the suggestions posted on the last PR.

**Comment by andrerfcsantos** [comment]
@vorenusCoA Sorry for the delay in replying. I've been away from exercism the last couple of months.

Are you still interested in working on this?

**Comment by vorenusCoA** [comment]
@andrerfcsantos Yes! I will review the branch and if everything is in place I will open a PR

**Comment by andrerfcsantos** [comment]
@vorenusCoA Cool! Take your time. Feel free to ping me if you need help with anything.
