### ISSUE TITLE
resistor-color-trio: implement exercise

### ISSUE THREAD

**Issue by lemoncurry** [exercism/java#1750]
The exercise **resistor-color-trio** has not been implemented yet for the Java track. 
The description of the exercise can be found in the [problem specification repository](https://github.com/exercism/problem-specifications/tree/main/exercises/resistor-color-trio). 

How to implement a new exercise for the Java track is described in detail in [CONTRIBUTING.md](https://github.com/exercism/java/blob/main/CONTRIBUTING.md). Please have a look there first before starting working on the exercise. 
Also please make sure it is clear that you are currently working on this issue, either by asking to be assigned to it, or by opening an empty PR. 

When opening an PR, please reference this issue using any of the [closing keywords](https://help.github.com/en/articles/closing-issues-using-keywords). 

If you have had a look at the exercise description and you concluded that the exercise might not be possible to implement in the Java language, please leave a comment and describe the problem. 

In case you have any further questions, feel free to ask here.

**Comment by HuskyNator** [comment]
I'd like to be assigned to this issue.

**Comment by andrerfcsantos** [comment]
@HuskyNator Still interested in working on this?

**Comment by GhostCoderz** [comment]
I would like to be assigned to this issue

**Comment by andrerfcsantos** [comment]
@GhostCoderz Sorry for taking some time to reply. Are you still interested in working on this?

**Comment by manumafe98** [comment]
@sanderploegsma there is someone working on this one? I would like to try on if not

**Comment by sanderploegsma** [comment]
> @sanderploegsma there is someone working on this one? I would like to try on if not

Fair question, I think the latest PR referencing this issue was closed for inactivity. IMO it's fine if you want to work on this! 👍
