### ISSUE TITLE
scale-generator: implement exercise

### ISSUE THREAD

**Issue by lemoncurry** [exercism/java#1753]
The exercise **scale-generator** has not been implemented yet for the Java track. 
The description of the exercise can be found in the [problem specification repository](https://github.com/exercism/problem-specifications/tree/main/exercises/scale-generator). 

How to implement a new exercise for the Java track is described in detail in [CONTRIBUTING.md](https://github.com/exercism/java/blob/main/CONTRIBUTING.md). Please have a look there first before starting working on the exercise. 
Also please make sure it is clear that you are currently working on this issue, either by asking to be assigned to it, or by opening an empty PR. 

When opening an PR, please reference this issue using any of the [closing keywords](https://help.github.com/en/articles/closing-issues-using-keywords). 

If you have had a look at the exercise description and you concluded that the exercise might not be possible to implement in the Java language, please leave a comment and describe the problem. 

In case you have any further questions, feel free to ask here.

**Comment by lpegoraro** [comment]
hey can I work on this?

**Comment by jmrunkle** [comment]
@lpegoraro - I don't see a pull request linked to this. Are you still trying to implement this?

**Comment by andrerfcsantos** [comment]
@lpegoraro still interested in working on this?

**Comment by BNAndras** [comment]
This exercise was recently deprecated (see https://github.com/exercism/problem-specifications/pull/2343) so this issue can probably be closed.

**Comment by sanderploegsma** [comment]
Thanks for the heads up!
