### ISSUE TITLE
Gradle test should show system streams (out, err)

### ISSUE THREAD

**Issue by bmuskalla** [exercism/java#1773]
When running unit tests for an exercise with Gradle, system out and system err are suppressed (Gradle default). Especially for beginners this might be very confusing behavior.

Happy to take this on if others agree

**Comment by lemoncurry** [comment]
I think this would be a very sensible change and I would be happy about it.
Other opinions @exercism/java ?

**Comment by FridaTveit** [comment]
Sounds good 🙂
