### ISSUE TITLE
Naming scheme in Grains exercise. 

### ISSUE THREAD

**Issue by ViralTaco** [exercism/java#1778]
Hi, 

I was trying to solve an exercise today in the java course. Namingly: "grains".
In the tests source file I was greeted by this line: `BigInteger result = grains.computeNumberOfGrainsOnSquare(1);` (cf: [source](https://github.com/exercism/java/blob/8b7f8def3e0761457bb3d0c4a26d49e2db230207/exercises/grains/src/test/java/GrainsTest.java#L28)) and frankly I was left demotivated and appalled. 

What this line should say is: `BigInteger result = Grains.onSquare(1);` 
And don't even begin to pretend that it's not _just as clear_. "Grains on square" I mean you'd have to be… I'll just stop myself there. 

Sloppy overly explicit names like that tell a message to students. It screams "I don't care, you know what I mean." it says "don't try". 

Honestly whoever pushed that should be ashamed not to have taken 10 minutes of their time to think "how can I make that simpler and/or cleaner?". 

If you need my help to refactor the code I'd love to help. 

Thank you for your time.

**Comment by FridaTveit** [comment]
Thanks for wanting to improve this exercise @ViralTaco 🙂I'm sorry that this made you demotivated. We always want to make sure our code is as clear as possible, so suggestions for improvements are always welcome 🙂However, in this case I think `computeNumberOfGrainsOnSquare` is more descriptive than just `onSquare`. I'm happy to discuss this further, however please try and keep your tone friendly and bear in mind that opinions other than your own are also valid 🙂

**Comment by ViralTaco** [comment]
Ok. Your opinion is invalid. But I understand the misunderstanding. 
I agree that `computeNumberOfGrainsOnSquare` is more descriptive than `onSquare`.
That is true. `Grains grains = new Grains;` followed by `grains.computeNumberOfGrainsOnSquare`
is not more descriptive than `Grains.onSquare` where `onSquare` is a static method of the class `Grains`. 

- There is no reason to instantiate a class with no state. 
- "Compute" what else? What else can you do in Java on a computer than to compute something? 
If you call a method that doesn't compute then you have a serious problem and I'm afraid I'm not qualified to give medical advice. 
- "Number" because `BigInteger` might be a potato. 
- "ofGrains"… "Grains.ofGrains…"

`Grains.onSquare()` a bit like… [This.](https://github.com/exercism/java/blob/8b7f8def3e0761457bb3d0c4a26d49e2db230207/exercises/space-age/src/main/java/SpaceAge.java#L11)

At this point if you think `Grains.onSquare` is not descriptive enough I'd like to recommend a more accurate name instead: "calculateTheNumberOfGrainsOnASingleSquareOfAnHypotheticalChessBoardGivenThatTheSquareIsTheOneMatchingThisMethodParameterAssumingAStandardChessBoardAndCountingFromTheNumberOneAsTheTopLeftMostSquareOfSaidChessBoard". 
It's more descriptive.

**Comment by FridaTveit** [comment]
I'm sorry @ViralTaco but if you can't discuss this without being rude then I don't think we can keep this issue open.

**Comment by ViralTaco** [comment]
I understand that you believe I'm rude. I'm being quite deadpan. So you're not wrong per say. 
In my opinion you are showing exactly the same attitude as whomever wrote that code, which is frustrating. You don't care therefore it's irrelevant. 

I don't believe "code smell" is irrelevant. (as opposed to my attitude) 
But if you truly believe that I must respect your opinion. 
You have the right to be wrong. (Still deadpan, not personal)
