### ISSUE TITLE
The last exercise "Knapsack" can't be accessed

### ISSUE THREAD

**Issue by charles-wangkai** [exercism/java#1780]
The last exercise "Knapsack" shows in locked status, though I passed all the other exercises in Java track. So I guess there is something wrong with the exercise dependency setting.

Could any staff please help to check? Thanks!

<img width="1063" alt="Screen Shot 2019-11-05 at 13 38 53" src="https://user-images.githubusercontent.com/8757419/68181258-a439a600-ffd1-11e9-8758-28144e8fd212.png">

**Comment by lemoncurry** [comment]
@charles-wangkai Thank you for notifying us about this problem. I changed the exercise that should unlock `knapsack`. Are you now able to access `knapsack`?

**Comment by charles-wangkai** [comment]
@lemoncurry Thanks for your quick reply! But it is still locked now.

**Comment by lemoncurry** [comment]
@charles-wangkai Are you in Mentored Mode or in Practice Mode?

**Comment by charles-wangkai** [comment]
I'm not a mentor, just to practise.

**Comment by lemoncurry** [comment]
@charles-wangkai Were you able to access other new exercises such as 'Resistor Color Duo' or 'Leap'? Have you tried switching to Mentored Mode and back to Practice Mode?

**Comment by charles-wangkai** [comment]
I can access all other exercises including "Resistor Color Duo" and "Leap". I never did the switch and am always in practice mode for Extra exercises.

**Comment by charles-wangkai** [comment]
I find that it can be accessed now :-)

**Comment by charles-wangkai** [comment]
And I just understood what "Mentored Mode" and "Practice Mode" really means. In fact, I have been always in the "Mentored Mode" all the time.

**Comment by lemoncurry** [comment]
I am glad that you can now access `knapsack` 😄
