### ISSUE TITLE
Two-fer exercise in java track, no unit test for when the input is empty 

### ISSUE THREAD

**Issue by xinri** [exercism/java#1783]
Hello,

I am a mentor for the java track. When I do the review, I always see that people forgot the empty string. When I check the unit tests, there is no test for this case and in the instructions, it is mentioned.

**Comment by jmrunkle** [comment]
I know that this discussion is old, but the topic has been left open. Since we (the maintainers) have apparently decided to have the empty string case explicitly return "One for , one for me.", I'm actually debating opening up a PR to have a custom test case that specifically tests for *that*. If there are no complaints, I'll at least make the simple PR.

**Comment by jmrunkle** [comment]
As a note, here is the official contributing policy on adding non-canonical tests:

> Check if there is canonical data for the exercise you're adding. This can be found at https://github.com/exercism/problem-specifications/tree/master/exercises/EXERCISE-SLUG/canonical-data.json. If there is canonical data for your exercise then you should follow this when making the tests. We aim to follow the canonical data as closely as possible in our tests to ensure thorough test coverage. If there is canonical data available you also need to create a file at exercises/exercise-slug/.meta/version specifying the canonical data version you have implemented (e.g. 1.0.0). The canonical data version can be found at the top of the canonical data file for that exercise. See other exercises, e.g. acronym, for an example version file.

This says nothing about adding extra track-specific tests and this feels like a good case where we should enshrine a decision that we specifically made.

**Comment by jmrunkle** [comment]
Closing this issue since we now have an official test for the empty input case - clarifying the exact behavior we expect.
