### ISSUE TITLE
Gradle Kotlin DSL

### ISSUE THREAD

**Issue by dector** [exercism/java#1784]
We gonna use [Gradle Kotlin DSL](https://github.com/exercism/kotlin/issues/340) for Kotlin track.

File `bin/README.md` says:
```
Many of these scripts are shared between the Java and Kotlin tracks. If you make an update to a script in one of these tracks, please also update the same script in the other track if appropriate.
```

Should I open PR to update these scripts in Java track as well?

**Comment by jmrunkle** [comment]
Looks like that was reverted:

> Reverted because unit-tests agains reference don't work with Gradle Kotlin DSL.

I'm closing this - please reopen if we still need to consider this. Likely, we do not care specifically about that one, but I could be mistaken.

**Comment by dector** [comment]
@jmrunkle Nope, its [used in v3](https://github.com/exercism/v3/blob/master/languages/kotlin/.templates/exercise/build.gradle.kts).

**Comment by jmrunkle** [comment]
@dector - even if you all plan to use it in v3, I still don't think the Java track cares about the gradle version used on the Kotlin track (and it is probably for the best to keep it that way). The README comment is more about things like bin/fetch-configlet and that sort of thing.
