### ISSUE TITLE
hints.md of isogram exercise seems old

### ISSUE THREAD

**Issue by mirkoperillo** [exercism/java#1786]
Hi,

File [hints.md](https://github.com/exercism/java/blob/master/exercises/isogram/.meta/hints.md) of isogram exercise seems old.

It refers to possible issues with `testWorksWithGermanLetters` but this test doesn't exist

Can I propose a PR removing these lines in `hints.md` ?

**Comment by jmrunkle** [comment]
It seems you are correct, it was removed in PR #1162. Please send a PR removing the stale lines.
