### ISSUE TITLE
dot-dsl: implement exercise

### ISSUE THREAD

**Issue by jmrunkle** [exercism/java#1809]
The exercise **dot-dsl** has not been implemented yet for the Java track. 
The description of the exercise can be found in the [problem specification repository](https://github.com/exercism/problem-specifications/tree/main/exercises/dot-dsl). 

How to implement a new exercise for the Java track is described in detail in [CONTRIBUTING.md](https://github.com/exercism/java/blob/main/CONTRIBUTING.md). Please have a look there first before starting working on the exercise. 
Also please make sure it is clear that you are currently working on this issue, either by asking to be assigned to it, or by opening an empty PR. 

When opening an PR, please reference this issue using any of the [closing keywords](https://help.github.com/en/articles/closing-issues-using-keywords). 

If you have had a look at the exercise description and you concluded that the exercise might not be possible to implement in the Java language, please leave a comment and describe the problem. 

In case you have any further questions, feel free to ask here.

**Comment by jaahay** [comment]
Greetings,
Would it be O.K. if I take this?
Best,
James

**Comment by CliffRoberson** [comment]
Sure, go ahead. Work has been a little more busy than i thought lately so I’ll find a different one.

Thanks

Cliff

**Comment by manumafe98** [comment]
@sanderploegsma it is still required to add this exercise? If yes, I would like to give it a try!

**Comment by sanderploegsma** [comment]
In general: yes. One reason not to add this exercise is if it covers concepts that don't really exist in Java. For example: one of the problem specifications (Lens Person) is really oriented towards functional programming languages, so we decided not to add it to the Java track.

I'm not familiar with the specifics of this exercise, so it could be that it's not a good fit for the Java track. I am open to suggestions from both sides, so if you have a cool idea on how to implement the exercise then go for it.
