### ISSUE TITLE
lens-person: implement exercise

### ISSUE THREAD

**Issue by jmrunkle** [exercism/java#1811]
The exercise **lens-person** has not been implemented yet for the Java track. 
The description of the exercise can be found in the [problem specification repository](https://github.com/exercism/problem-specifications/tree/main/exercises/lens-person). 

How to implement a new exercise for the Java track is described in detail in [CONTRIBUTING.md](https://github.com/exercism/java/blob/main/CONTRIBUTING.md). Please have a look there first before starting working on the exercise. 
Also please make sure it is clear that you are currently working on this issue, either by asking to be assigned to it, or by opening an empty PR. 

When opening an PR, please reference this issue using any of the [closing keywords](https://help.github.com/en/articles/closing-issues-using-keywords). 

If you have had a look at the exercise description and you concluded that the exercise might not be possible to implement in the Java language, please leave a comment and describe the problem. 

In case you have any further questions, feel free to ask here.

**Comment by sougat818** [comment]
I had a look at this and this concept seems to be very specific to functional programming languages and not present in Java. I can raise a PR to  forego this as they have done in the python stream . 

https://github.com/exercism/python/pull/1299

**Comment by sanderploegsma** [comment]
Yes I think I agree with you. IMO it's fine to forego this exercise for the Java track, so a PR is welcome!
