### ISSUE TITLE
react: implement exercise

### ISSUE THREAD

**Issue by jmrunkle** [exercism/java#1815]
The exercise **react** has not been implemented yet for the Java track. 
The description of the exercise can be found in the [problem specification repository](https://github.com/exercism/problem-specifications/tree/master/exercises/react). 

How to implement a new exercise for the Java track is described in detail in [CONTRIBUTING.md](https://github.com/exercism/java/blob/master/CONTRIBUTING.md#adding-a-new-exercise). Please have a look there first before starting working on the exercise. 
Also please make sure it is clear that you are currently working on this issue, either by asking to be assigned to it, or by opening an empty PR. 

When opening an PR, please reference this issue using any of the [closing keywords](https://help.github.com/en/articles/closing-issues-using-keywords). 

If you have had a look at the exercise description and you concluded that the exercise might not be possible to implement in the Java language, please leave a comment and describe the problem. 

In case you have any further questions, feel free to ask here.

**Comment by Kineolyan** [comment]
I liked this one a lot when I tested it on the Rust track. I am ok to implement it for the Java track, though it may not be ready really fast - tell me if it is an issue.
To your knowledge, is there one version of the exercise in any other language that I should use as an inspiration?

**Comment by jmrunkle** [comment]
It's all yours. This is implemented in the Kotlin track which has a lot of similarity with the Java track anyway so feel free to take inspiration from there: https://github.com/exercism/kotlin/tree/master/exercises/react

**Comment by Kineolyan** [comment]
Though I still liked the exercise, I am letting it to someone else. Sorry and good luck.

**Comment by kahgoh** [comment]
If you're still looking for someone to implement this exercise, I'd like to work on this one.

**Comment by andrerfcsantos** [comment]
@kahgoh That'd be great, go for it :)

**Comment by kahgoh** [comment]
@andrerfcsantos PR #2266 raised for this one
