### ISSUE TITLE
Java version required to build the project

### ISSUE THREAD

**Issue by antonmry** [exercism/java#1828]
In `CONTRIBUTING.md` is stated JDK 1.8+ is required. But in this commit https://github.com/exercism/java/commit/913b3d3d1b9a6b9a6760868bf87a1dab8cbc8982 it was introduced Map.of (Java 9) so some tests are failing with Java 8.

All tests are green with Java 11 so it's probably a good idea just to update the CONTRIBUTING.md to use that LTS version.

**Comment by jmrunkle** [comment]
I agree... Java 8 is already 6 years old. I think we can update to Java 11.
