### ISSUE TITLE
micro-blog not showing up

### ISSUE THREAD

**Issue by jmrunkle** [exercism/java#1834]
https://github.com/exercism/java/pull/1805#issuecomment-620226842

@ericbalawejder can you confirm that this does not show up in your side exercises list? There should be a link to side exercises that I can point you towards (once I'm back at my laptop). If you can send me a screenshot showing your side exercises page that might help.

I'm wondering if there's a bug for newly created exercises not showing up if the exercise is added after you completed the pre-reqs. Or there could be a display bug of just not showing them on the core path in mentored mode.

**Comment by jmrunkle** [comment]
This page: https://exercism.io/my/tracks/java#side-exercises

**Comment by ericbalawejder** [comment]
![image](https://user-images.githubusercontent.com/4513001/80436432-1928d100-88cd-11ea-8cc2-f442ef69c5a2.png)

**Comment by ericbalawejder** [comment]
I believe this has popped up before in the Slack channel. It might have something to do with mentor mode as you pointed out.

**Comment by jmrunkle** [comment]
Possible workaround (if you are willing to try this). Leave mentored mode and then go back into mentored mode. See what happens? In the meantime, let me ask on the slack channel.

**Comment by ericbalawejder** [comment]
It seems the only way to leave mentor mode is to e-mail the admin: 
https://exercism.io/mentoring-faqs

I'll head to the Slack as well.

**Comment by SleeplessByte** [comment]
Hi there! This exercise is so new, it hasn't yet been enabled through a script we need to run. Jeremy has been pinged and he'll probably take care of it tomorrow morning. You'll magically see the exercise unlocked.

Leaving mentored mode is not the same as "stop being a mentor". You can leave mentored mode on the bottom right of the track page.

**Comment by jmrunkle** [comment]
> Hi there! This exercise is so new, it hasn't yet been enabled through a script we need to run. Jeremy has been pinged and he'll probably take care of it tomorrow morning. You'll magically see the exercise unlocked.
> 
> Leaving mentored mode is not the same as "stop being a mentor". You can leave mentored mode on the bottom right of the track page.

Thanks!
