### ISSUE TITLE
Add a gitpod configuration for all

### ISSUE THREAD

**Issue by Kineolyan** [exercism/java#1835]
[Gitpod](https://www.gitpod.io/) is a tool integrating with Github that lets users develop in an online IDE whitin a docker-configured environment.
It is getting traction and offering more and more support of languages and tools.

Having such an environment configured for _exercism/java_ - and surely other languages - would help a lot any contibutors.
For newcomers, it saves the installation process - that may vary from installing java, gradle or only configlet. For seasoned contributors, it saves from maintaining the development environment into many personal machines.

Because exercism problems are often simple projects, there are no real need for a full-blown IDE, making Gitpod a good fit. I don't know if this could be applied to users, offering them a working environment for practice.

**Comment by jmrunkle** [comment]
As a user of gitpod myself, I have no problem with this.

**Comment by mirkoperillo** [comment]
Hi,
the v3 of exercism, that, I think, will be shipped at the beginning of summer, will provide an online editor

**Comment by Kineolyan** [comment]
Then, no need for gitpod for users.
