### ISSUE TITLE
Idea for a new very-hard exercise with concurrency

### ISSUE THREAD

**Issue by Kineolyan** [exercism/java#1836]
I am writing a exercise about concurrency for my colleagues and I was thinking that it could be a good addition to the list of exercism. I checked the ones labelled "concurrency" and found only two in that category.

I was thinking about playing with `Semaphore`, with the idea of a dynamically resizable car parking.
In the parking, there is a configured number of spots and cars arriving will try to reserve one spot, for any duration. This is a simple use of Semaphore. It gets harder - and that is the goal of the exercise - to support increasing or decreasing the size of the parking at any time, particularly while cars are still parked.

I already have a working implementation for this, that is not very complex. In my opinion, it is only hard because you have to consider all use-cases to pass the tests.

Cheers

**Comment by jmrunkle** [comment]
Per our contributing guide:

> To add a completely new exercise you need to open a pull request to the [problem specifications repository](https://github.com/exercism/problem-specifications/tree/master/exercises). Any completely new exercise needs to be added and accepted there before it can be added to the Java track.

Once added there, feel free to take a stab at implementing it here in Java.
