### ISSUE TITLE
Broken tests in Nucleotide Count exercise

### ISSUE THREAD

**Issue by johnnybaloney** [exercism/java#1843]
[NucleotideCounterTest.java](https://github.com/exercism/java/blob/31c1c266cbf2df7fc70b38f74210055184cfe318/exercises/nucleotide-count/src/test/java/NucleotideCounterTest.java) contains invisible characters that break tests.

Calls to `containsExactlyInAnyOrderEntriesOf`have invisible characters just before the opening parenthesis.

```
@@ -23,7 +23,7 @@ public class NucleotideCounterTest {
         NucleotideCounter nucleotideCounter = new NucleotideCounter("G");
 
         assertThat(nucleotideCounter.nucleotideCounts())
-            .containsExactlyInAnyOrderEntriesOf<U+200B>(
+            .containsExactlyInAnyOrderEntriesOf(
                 Map.of('A', 0, 'C', 0, 'G', 1, 'T', 0));
     }
```

**Comment by mirkoperillo** [comment]
@johnnybaloney thank you for signaling this.

Can you tell us your OS, java and gradle version please ?

**Comment by ericbalawejder** [comment]
<img width="706" alt="Screen Shot 2020-10-14 at 1 46 37 PM" src="https://user-images.githubusercontent.com/4513001/96025895-cc599800-0e23-11eb-9745-e639d56fce30.png">

```
------------------------------------------------------------
Gradle 6.4
------------------------------------------------------------

Build time:   2020-05-05 19:18:55 UTC
Revision:     42f7c3d0c3066b7b38bd0726760d4881e86fd19f

Kotlin:       1.3.71
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.1 (Oracle Corporation 11.0.1+13)
OS:           Mac OS X 10.14.6 x86_64

```
