### ISSUE TITLE
Markdown Side Exercise - Code Missing

### ISSUE THREAD

**Issue by juan-castrillon** [exercism/java#1844]
In the Markdown side exercise, the task is defined as 

> a refactoring exercise

, where there is some code that needs to be improved. However, after downloading the files, the `Markdown.java` file, only contains the following : 

```
/*

Since this exercise has a difficulty of > 4 it doesn't come
with any starter implementation.
This is so that you get to practice creating classes and methods
which is an important part of programming in Java.

Please remove this comment when submitting your solution.

*/
```

Am I expected to code from scratch? Because that would contradict the description of the task. 

Thanks in advance 😄

**Comment by brownmike** [comment]
It looks like this commit removed the implementation https://github.com/exercism/java/commit/b2818e484d9b9badf4130e060fcfe06c6198544a#diff-83b893441096ed6cc3647b0c8759928372c9214df9d244a76bc7f63d30a54667

**Comment by iHiD** [comment]
@jmrunkle Could you take a look at this pls 🙂

**Comment by masahx** [comment]
I noticed this too... I could use this commit later

**Comment by iHiD** [comment]
(cc @exercism/java)

**Comment by mirkoperillo** [comment]
it seems an error maybe not considering the refactor nature of this exercise.
I think we can recover the initial implementation (to permit the refactor exercise) using the commit signaled by @brownmike

**Comment by iHiD** [comment]
Thanks :)

**Comment by juan-castrillon** [comment]
Thanks a lot 😊

**Comment by iHiD** [comment]
One thing to note is that this won't sync until v3 is launched now as the repos are disconnected from the website.
