### ISSUE TITLE
Gradle: replace testCompile configuration with testImplementation?

### ISSUE THREAD

**Issue by muzimuzhi** [exercism/java#1853]
Running `gradle --warning-mode all test` gives

> \> Configure project :
The testCompile configuration has been deprecated for dependency declaration. This will
fail with an error in Gradle 7.0. Please use the testImplementation configuration instead.
Consult the upgrading guide for further information: https://docs.gradle.org/6.7.1/userguide/upgrading_version_5.html#dependencies_should_no_longer_be_declared_using_the_compile_and_runtime_configurations

It seems simply replacing `testCompile` with `testImplementation` in `build.gradle` does the work, for example for `hello-world`,

```diff
diff --git a/exercises/hello-world/build.gradle b/exercises/hello-world/build.gradle
index 7a681943..76a54c49 100644
--- a/exercises/hello-world/build.gradle
+++ b/exercises/hello-world/build.gradle
@@ -11,7 +11,7 @@ repositories {
 }
 
 dependencies {
-  testCompile "junit:junit:4.13"
+  testImplementation "junit:junit:4.13"
   testImplementation "org.assertj:assertj-core:3.15.0"
 }
```

I'm new to `gradle`, hence not sure if the above proposal is right.

**Comment by mirkoperillo** [comment]
Hi @muzimuzhi sorry to the late answer.
Thank for your suggestion. Currently all maintainers effort is dedicated to ship the new version of the track (v3). (More details #1854 )

We will test this suggestion ASAP or if you are interested you can try to test it on the current main repo and then provide a PR

**Comment by muzimuzhi** [comment]
Is https://github.com/exercism/v3 the current main repo?

**Comment by muzimuzhi** [comment]
@mirkoperillo I've made the required change in https://github.com/muzimuzhi/v3/tree/java/gradle. But since [`exercism/v3`](https://github.com/exercism/v3) is archived, PRs are read-only and I could not open any new ones.

**Comment by mirkoperillo** [comment]
@muzimuzhi  yes, the correct repo is this one.

Thank you for the contribution I'll give it a look ASAP
