### ISSUE TITLE
Dead link 

### ISSUE THREAD

**Issue by Joker018** [exercism/java#1857]
Hi, 
Just to signal that there is a dead link on the website in Java track > Useful Java Resources. The link that is dead is the "Java Programming Books" (see screen).
The link "Free Programming Books - java" in Java Track > Learning Java. is also dead 

![Capture d’écran 2021-01-16 à 12 49 05](https://user-images.githubusercontent.com/19249942/104811106-900a4f00-57f9-11eb-9e60-d6453cdb5c7c.png)
![Capture d’écran 2021-01-16 à 12 49 50](https://user-images.githubusercontent.com/19249942/104811114-96003000-57f9-11eb-926f-39b1f1ddc428.png)

![Capture d’écran 2021-01-16 à 12 54 07](https://user-images.githubusercontent.com/19249942/104811196-45d59d80-57fa-11eb-81a0-effd6b5da302.png)

**Comment by mirkoperillo** [comment]
Hi @Joker018  sorry to the late answer.
Thank for your suggestion. Currently all maintainers effort is dedicated to ship the new version of the track (v3). (More details #1854 ).

We will fix it ASAP
