### ISSUE TITLE
[CI] Adding `gradle check` to github actions

### ISSUE THREAD

**Issue by himanshugoyal1065** [exercism/java#1860]
@mirkoperillo, thank you! I have updated the PR and now it's passing the `gradle check`
Also, I suggest adding this check in the actions directly, so that you or any other maintainer don't have to tell everyone personally :)

_Originally posted by @himanshugoyal1065 in https://github.com/exercism/v3/pull/2278#issuecomment-704445876_

**Comment by mirkoperillo** [comment]
fixed by #1988
