### ISSUE TITLE
Suggest new exercise: <exception-handling>

### ISSUE THREAD

**Issue by himanshugoyal1065** [exercism/java#1861]
In this issue, a new concept exercise for the <JAVA> track is suggested. The exercise's name is `<exception-handling>`.

## Rationale

Exception handling is a core concept of java and is used extensively in development. Someone working/ learning Java, should know the basics of Exception handling.

## Concepts

Exception handling consists of the following main concepts:
- try and catch blocks
- finally block
- throws and throw keywords.
- Types of exceptions
- Why use exception handling in the first place.

For example:

The goal of this exercise is to teach the student how the concept `exception-handlig` is implemented in <JAVA>. We will teach `exception-handling` through Java's classes and arrays mainly (can include more concepts also).

**Comment by rv02** [comment]
@mirkoperillo I would like to work on this issue! 
This will be my first issue. I read the docs on adding a new exercise.
I will port the exercise from C# track.

**Comment by ericbalawejder** [comment]
There is a similar exercise titled `error-handling` but it doesn't have the `try, catch, finally` functionality. Not sure if it's valuable to combine/update the exercise or create a new one?

**Comment by mirkoperillo** [comment]
@rv02 thank you, you are welcome and feel free to ask with a comment in this issue for every doubt.
We will try to help you.
My proposal it is to start with the C# one as guideline and understand where to update it to be aligned with concept of handling the exceptions defined in Java.

**Comment by dbc2201** [comment]
Hi @rv02, are you still working on this? I'd like to help if possible.

**Comment by rv02** [comment]
@jmrunkle I think we can close this issue. We launched Calculator Conundrum exercise.

**Comment by mirkoperillo** [comment]
@rv02 you are right. Issue resolved by https://github.com/exercism/java/pull/2022
