### ISSUE TITLE
Move gradle wrapper to a newer version

### ISSUE THREAD

**Issue by mirkoperillo** [exercism/java#1881]
Currently the version of gradle installed by the wrapper is very old and it doesn't work with the last versions of Java

https://github.com/exercism/java/blob/main/gradle/wrapper/gradle-wrapper.properties

It should be moved to the last gradle version (6.8.2)

**Comment by ericbalawejder** [comment]
It looks like the latest release is `gradle-6.8.3-bin.zip`. Is there a way to test this once it's changed...say like picking and running one exercise vs running them all?

**Comment by mirkoperillo** [comment]
following the Gradle documentation for the wrapper usage, https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:using_wrapper

Have I answer to your doubt ?

**Comment by ericbalawejder** [comment]
Yes, thank you.

**Comment by mirkoperillo** [comment]
Fixed from #1896
