### ISSUE TITLE
Discussion about what are the Java key features

### ISSUE THREAD

**Issue by mirkoperillo** [exercism/java#1883]
Ref to #1865 we have to define 6 key features of Java that will be shown in the new v3 track page.
Time to discuss about it

**Comment by ericbalawejder** [comment]
Key features that allow easy comparisons of other server side languages? Multi-paradigm (object oriented, functional, contains primitives), platform independent, supports generics, (Go doesn't), garbage collected, multi-threaded (might not be important when learning the language), statically typed (forced type assignment).

I always find the terms "interpreted language" or "compiled language" a gray area depending how you describe languages.

**Comment by mirkoperillo** [comment]
Yes, I think the approach can be to describe the 6 key features of Java for someone coming from other languages.
I like:
* Multi-paradigm
* platform independent,
* garbage collected
* statically typed

I think it can be interesting:
* supports generics

@msomji  any other suggestions ?

**Comment by ericbalawejder** [comment]
```
"key_features": [
    {
      "icon": "",
      "title": "Modern",
      "content": "Java is a modern, fast-evolving language with releases every 6 months."
    },
    {
      "icon": "features-typed",
      "title": "Statically-typed",
      "content": "Every expression has a type known at compile time."
    },
    {
      "icon": "features-functional",
      "title": "Multi-paradigm",
      "content": "Java is primarily an object-oriented language, but has many functional features introduced in v1.8."
    },
    {
      "icon": "",
      "title": "General purpose",
      "content": "Java is used for a variety of workloads like web, cloud, mobile and game applications."
    },
    {
    "icon": "features-portable",
    "title": "Portable",
    "content": "Java was designed to be cross-platform with the slogan \"Write once, run anywhere\"."
    },
    {
      "icon": "",
      "title": "Documentation",
      "content": "Documentation is excellent with a large community making it easy to get started with Java."
    }
],

```
Initial content. It appears other tracks only have 6 key features so I'm not sure if there is a hard limit or not. I left out generics if anyone feels that would be a better choice in place of something. The `content` field has to be <= 100 characters. I left some `icon` fields blank because there doesn't appear to be a list to choose from. It says `TODO` in the docs. https://github.com/exercism/docs/blob/main/anatomy/tracks/config-json.md#key-features. Any other suggestions or input @msomji @mirkoperillo ?

**Comment by mirkoperillo** [comment]
From the documentation
> Exactly 6 key features must be specified.

So, yes it seems there is an hard limit

In my opinion your proposal is good.
Maybe I think that "Garbage Collected" could be a interesting key features of Java in comparison with other languages

**Comment by ericbalawejder** [comment]
```
"key_features": [
    {
      "icon": "",
      "title": "Modern",
      "content": "Java is a modern, fast-evolving language with releases every 6 months."
    },
    {
      "icon": "features-typed",
      "title": "Statically-typed",
      "content": "Every expression has a type known at compile time."
    },
    {
      "icon": "features-functional",
      "title": "Multi-paradigm",
      "content": "Java is primarily an object-oriented language, but has many functional features introduced in v1.8."
    },
    {
      "icon": "",
      "title": "General purpose",
      "content": "Java is used for a variety of workloads like web, cloud, mobile and game applications."
    },
    {
      "icon": "features-portable",
      "title": "Portable",
      "content": "Java was designed to be cross-platform with the slogan \"Write once, run anywhere\"."
    },
    {
      "icon": "",
      "title": "Garbage Collection",
      "content": "Java programs perform automatic memory management for their lifecycles."
    }
],
```
I replaced `Documentation` with `Garbage Collection`. I agree that it is a more valuable descriptive feature.  
This docs have moved from: 
https://github.com/exercism/docs/blob/main/anatomy/tracks/config-json.md#key-features 
to: 
https://github.com/exercism/docs/blob/main/building/tracks/config-json.md#key-features
Still no update for the `icon` field.

**Comment by mirkoperillo** [comment]
I think that we could merge this and open an issue to trace that absence of icon for the moment
