### ISSUE TITLE
Organization: adding prerequisites to practice exercises

### ISSUE THREAD

**Issue by mirkoperillo** [exercism/java#1923]
One of the v3 migration requirements is to add what concepts are prerequisites for face with the practice exercise.
[here](https://github.com/exercism/java/issues/1867) more details

The goal of this issue is to give a sort of general overview on this task.
We should improve the configuration of 120 exercise.
The idea is to claim in a comment of this issue a set of exercise to work on, to avoid some overlapping of work.
We will tick every exercise already revisited.

- [ ] accumulate
- [ ] acronym
- [ ] affine-cipher
- [x] allergies
- [ ] all-your-base
- [ ] alphametics
- [x] anagram
- [ ] armstrong-numbers
- [ ] atbash-cipher
- [x] bank-account
- [x] beer-song
- [ ] binary
- [x] binary-search
- [ ] binary-search-tree
- [x] bob
- [ ] book-store
- [x] bowling
- [ ] change
- [ ] circular-buffer
- [ ] clock
- [ ] collatz-conjecture
- [ ] complex-numbers
- [ ] crypto-square
- [ ] custom-set
- [x] darts
- [x] diamond
- [x] difference-of-squares
- [ ] diffie-hellman
- [x] dnd-character
- [ ] dominoes
- [ ] error-handling
- [ ] etl
- [x] flatten-array
- [x] food-chain
- [ ] forth
- [x] gigasecond
- [ ] go-counting
- [ ] grade-school
- [x] grains
- [ ] grep
- [x] hamming
- [ ] hangman
- [x] hello-world
- [ ] hexadecimal
- [x] house
- [x] isbn-verifier
- [x] isogram
- [ ] kindergarten-garden
- [x] knapsack
- [x] largest-series-product
- [ ] leap
- [x] linked-list
- [ ] list-ops
- [x] luhn
- [ ] markdown
- [ ] matching-brackets
- [x] matrix
- [x] meetup
- [x] micro-blog
- [x] minesweeper
- [ ] nth-prime
- [x] nucleotide-count
- [ ] ocr-numbers
- [ ] octal
- [ ] palindrome-products
- [ ] pangram
- [ ] parallel-letter-frequency
- [ ] pascals-triangle
- [ ] perfect-numbers
- [x] phone-number
- [x] pig-latin
- [ ] poker
- [ ] prime-factors
- [x] protein-translation
- [x] proverb
- [ ] pythagorean-triplet
- [ ] queen-attack
- [ ] rail-fence-cipher
- [x] raindrops
- [ ] rational-numbers
- [ ] rectangles
- [x] resistor-color
- [x] resistor-color-duo
- [ ] rest-api
- [x] reverse-string
- [ ] rna-transcription
- [x] robot-name
- [ ] robot-simulator
- [x] roman-numerals
- [x] rotational-cipher
- [ ] run-length-encoding
- [x] saddle-points
- [ ] satellite
- [ ] say
- [x] scrabble-score
- [x] secret-handshake
- [x] series
- [ ] sieve
- [ ] simple-cipher
- [ ] simple-linked-list
- [ ] space-age
- [ ] spiral-matrix
- [ ] strain
- [ ] sublist
- [ ] sum-of-multiples
- [ ] tournament
- [ ] transpose
- [ ] tree-building
- [x] triangle
- [ ] trinary
- [x] twelve-days
- [ ] two-bucket
- [x] two-fer
- [ ] variable-length-quantity
- [x] word-count
- [ ] word-search
- [ ] wordy
- [x] yacht
- [ ] zebra-puzzle
- [ ] zipper

**Comment by ericbalawejder** [comment]
This check list is a huge help. I started this issue a few weeks ago and stalled. I started with the first two exercises in the `practice` array of the `config.json` file to help understand the requirements.

```
"practice": [
      {
        "slug": "hello-world",
        "name": "Hello World",
        "uuid": "f77dc7e3-35a8-4300-a7c8-2c1765e9644d",
        "practices": [],
        "prerequisites": [],
        "difficulty": 1,
        "topics": [
          "strings"
        ]
      },
      {
        "slug": "two-fer",
        "name": "Two Fer",
        "uuid": "74515d45-565b-4be2-96c4-77e58efa9257",
        "practices": [],
        "prerequisites": [],
        "difficulty": 1,
        "topics": [
          "conditionals",
          "strings"
        ]
      },
```

I used the `topics` for `practices`. How should we go about adding more to the `practices` array?

From the [docs](https://github.com/exercism/java/issues/1867): "Each prerequisite concept should have its own entry in the top-level "concepts" array."

I'm confused. Does this mean only one concept slug should be in the `prerequisites` array? Maybe I'm confusing concept (general) with the actual Concept exercise?

```
"practice": [
      {
        "slug": "hello-world",
        "name": "Hello World",
        "uuid": "f77dc7e3-35a8-4300-a7c8-2c1765e9644d",
        "practices": ["strings"],
        "prerequisites": ["lasagna"],
        "difficulty": 1
      },
      {
        "slug": "two-fer",
        "name": "Two Fer",
        "uuid": "74515d45-565b-4be2-96c4-77e58efa9257",
        "practices": ["conditionals", "strings"],
        "prerequisites": ["squeaky-clean"],
        "difficulty": 1
      },
```

**Comment by mirkoperillo** [comment]
> I'm confused. Does this mean only one concept slug should be in the prerequisites array? 

No, a practice exercise could have more than one Concept prerequisite.
This is the example in the documentation
```
{
  "exercises": {
    "practice": [
      {
        "uuid": "8ba15933-29a2-49b1-a9ce-70474bad3007",
        "slug": "leap",
        "name": "Leap",
        "practices": ["if-statements", "numbers", "operator-precedence"],
        "prerequisites": ["if-statements", "numbers"],
        "difficulty": 1
      }
    ]
  }
}
```
There are 2 concepts as prerequisites of the practice exercise.
I hope to understand right your doubts
