### ISSUE TITLE
New test for isbn-verifier

### ISSUE THREAD

**Issue by scmbradley** [exercism/java#1936]
My [solution to this exercise](https://exercism.io/tracks/java/exercises/isbn-verifier/solutions/398139213ab845b08e9d2d972fbf7e3e) passes all the tests, but obviously validates a bunch of non-ISBN strings (namely, any string that has just enough digits in the right order to be a valid ISBN). The code I used just strips out everything that isn't in `[0-9X]` and then works with that filtered array of 1 character strings. This was my first stab at filtering out hypens.

So it fails on the following additional test:

```
    @Test
    public void inputIsNonsenseButContainsAValidIsbn() {
	assertFalse(isbnVerifier.isValid("ABCDEFG3-598-21507-XQWERTYUI"));
    }
```

**Comment by ericbalawejder** [comment]
Fixed via #1968
