### ISSUE TITLE
Junit on Gradle not working

### ISSUE THREAD

**Issue by guimsmendes** [exercism/java#1948]
I've followed the steps to install gradle, but when I run the tests in any Java exercise, I receive the following error:

```
* What went wrong:
A problem occurred evaluating root project 'two-fer'.
> Could not find method testCompile() for arguments [junit:junit:4.13] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

**Comment by mirkoperillo** [comment]
Hi @guimsmendes 
this is a known bugs and we are waiting the v3 version to fix it in production
https://github.com/exercism/java/issues/1944#issuecomment-855791756 here some possible workarounds

Let we know if the problem still remains

**Comment by mirkoperillo** [comment]
I think this issue can be closed
