### ISSUE TITLE
Check docs are up to date

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/java#1971]
Please check if your documentation files are still up-to-date.

The key documentation files to check are:

- `docs/ABOUT.md`
- `docs/INSTALLATION.md`
- `docs/LEARNING.md`
- `docs/RESOURCES.md`
- `docs/TESTS.md`
- `exercises/shared/.docs/help.md`
- `exercises/shared/.docs/tests.md`

There might be more.

## Link check report

To help identify invalid links, we've automatically checked the links of _all_ `*.md` files in this repo.
This is the report of that check:

<pre style="color:#bbb;white-space:pre-wrap;word-wrap:break-word;overflow-wrap:break-word">📝 Summary
---------------------
🔍 Total..........374
✅ Successful.....372
⏳ Timeouts.........0
🔀 Redirected.......0
👻 Excluded.........0
🚫 Errors...........2

Errors in ./README.md
<span style="color:#ff5555">✗ https://gitter.im/exercism/xjava (HTTP status client error (404 Not Found) for url (https://gitter.im/exercism/xjava))</span>

Errors in ./exercises/practice/hello-world/TUTORIAL.md
<span style="color:#ff5555">✗ file:///home/ (builder error for url (file:///home/): URL scheme is not allowed)</span>

</pre>
## Tracking

https://github.com/exercism/v3-launch/issues/54

**Comment by ericbalawejder** [comment]
For the broken link in the README.md, the only functioning page I can find for contributing is: https://github.com/exercism/docs/blob/main/community/contributors.md

The v3 beta page looks great.
https://exercism.lol/contributing
Should this be ignored until v3 is launched?


The other error is a sample gradle output for viewing the report: 
`file:///home/<username>/hello-world/build/reports/tests/index.html`
```
:test

GreeterTest > testThatGreeterReturnsTheCorrectGreeting FAILED
    java.lang.UnsupportedOperationException: Delete this statement and write your own implementation.
        at getGreeting(Greeter.java:4)
        at GreeterTest.testThatGreeterReturnsTheCorrectGreeting(GreeterTest.java:9)

1 tests completed, 1 failed
:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///home/<username>/hello-world/build/reports/tests/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 12.361 secs
```
Should this be ignored?

**Comment by ErikSchierboom** [comment]
@ericbalawejder I'd update the docs to point to https://exercism.org/contributing, which will be operational tomorrow :)

**Comment by mirkoperillo** [comment]
@ericbalawejder  I think we can ignore the `file:///home/<username>/hello-world/build/reports/tests/index.html` link warning for the moment.

If this link reference will break other times some checker in the future we will remove it
