### ISSUE TITLE
Introduce assertj in resistor-color exercise

### ISSUE THREAD

**Issue by mirkoperillo** [exercism/java#1982]
Some time ago Java track decided to move assertions from JUnit one to assertj

The goal of this issue is to introduce assertj assertions in this exercise
https://github.com/exercism/java/blob/main/exercises/practice/resistor-color/src/test/java/ResistorColorTest.java

**Comment by thtroyer** [comment]
I'd love to take a stab at this. Give me a few days to implement.

**Comment by mirkoperillo** [comment]
@thtroyer thank you, feel free to ask for every doubt

**Comment by thtroyer** [comment]
PR added, #1984

My only question is for converting other exercises to AssertJ -- does an issue need to be made before a PR for updating that exercise?

**Comment by jmrunkle** [comment]
> PR added, #1984
> 
> My only question is for converting other exercises to AssertJ -- does an issue need to be made before a PR for updating that exercise?

While common, I do not think it is strictly necessary.

Got any preferences @mirkoperillo ?

**Comment by mirkoperillo** [comment]
@thtroyer I don't think it is necessary for this case
 thank you for your contribution
