### ISSUE TITLE
football-match-reports tests are not correct

### ISSUE THREAD

**Issue by incendium** [exercism/java#2013]
I was mentoring a solution for this exercise and found that the tests are calling `contentEquals` directly on the result instead of `isEqualTo` on the assertion.  This is causing the tests to pass despite receiving invalid input.

**Comment by jmrunkle** [comment]
Lol, this is hilariously broken. They just call assertThat(...) but never actually make an assertion.

For example:

```java
    @Test
    public void test_goal() {
        assertThat(FootballMatchReports.onField(1).contentEquals("goalie"));
    }
```

Should have been:

```java
    @Test
    public void test_goal() {
        assertThat(FootballMatchReports.onField(1)).isEqualTo("goalie");
    }
```

Yep... basically every test in that suite is broken. Let me fix that.
