### ISSUE TITLE
Support Java 17 LTS

### ISSUE THREAD

**Issue by FranklinChen** [exercism/java#2034]
I suggest supporting Java 17 LTS now that it's out.

**Comment by jmrunkle** [comment]
Sure, but we have to wait for Gradle to support it first: https://docs.gradle.org/current/userguide/compatibility.html#java

**Comment by ericbalawejder** [comment]
I'm excited about Java 17. It's the next LTS version as you mentioned but we are waiting for Gradle support to catch up. The entire project uses this build tool. Upgrading to a later version of Gradle has broken some deprecated features in the past. These issues were fixed for the release of V3 but involved making changes to every exercise. See https://github.com/exercism/java/pull/1875.

**Comment by ericbalawejder** [comment]
It looks like Gradle 7.3 was recently released on 11/9. https://docs.gradle.org/7.3/release-notes.html
It supports the Java 17 LTS version. I believe there are still issues with the test-runner so we may want to get a better understanding of those before upgrading Gradle and Java. Thoughts?

**Comment by FranklinChen** [comment]
What problems are there currently with the test runner?

**Comment by ericbalawejder** [comment]
The test runner currently runs on Maven to help address performance issues. We have to test the JDK-17 in the test runner as well as the exercism/java project, which uses gradle.

**Comment by ErikSchierboom** [comment]
> @ErikSchierboom I'm not sure where the Java 17 JDK lives in the the file system hierarchy? The test runner uses a docker file but I'm not sure about how the root of all the exercises are configured for the Java version?

I'm not sure. @andreaTP is much more knowledgeable on the Java test runner than I am.

**Comment by andreaTP** [comment]
For the test-runner it should be as easy as updating the base image:
https://github.com/exercism/java-test-runner/blob/7c732758aec43d0b490287a6afeee338cb1e61fa/Dockerfile#L25

to something like `maven:3.8.4-openjdk-17`.

**Comment by ericbalawejder** [comment]
Right, I assumed it was simply changing the image in the docker file. What I'm unsure of, is there some kind of configuration that specifies the java version in the base repository? For example, sometimes you will see `sourceCompatibility = '11'` in `build.gradle` files. The root of `exercism/java` doesn't have a `build.gradle` file. I'm just curious how I can test that there aren't dependency issues if we update both Gradle and Java?

**Comment by andreaTP** [comment]
@ericbalawejder I briefly checked and it looks to me that everything is fine, `sourceCompatibility` is not in Gradle, `gradlew` files are not committed ... everything should be fine!
