### ISSUE TITLE
Add test to robot name exercise - ensure robot names are unique

### ISSUE THREAD

**Issue by cdpaiva** [exercism/java#2056]
Hello everyone, 

In the [robot name exercise](https://github.com/exercism/java/blob/main/exercises/practice/robot-name), the instructions require unique names:

> Using random names means a risk of collisions. Your solution must ensure that every existing robot has a unique name.

There is currently a `differentRobotsHaveDifferentNames()` test, but that doesn't ensure collisions won't happen.

There is no [canonical data for the tests](https://github.com/exercism/problem-specifications/tree/main/exercises/robot-name) of this exercise, but other tracks implement a specific test for unique names, like the [javascript track](https://github.com/exercism/javascript/blob/main/exercises/practice/robot-name/robot-name.spec.js).

I'm completely new in here and don't know the impact of changing the tests of an existing exercise. If that is ok, I would like to add this test to the exercise.

**Comment by jmrunkle** [comment]
Yeah, we should probably have a test that proves they can generate all of the names: https://github.com/exercism/javascript/blob/main/exercises/practice/robot-name/robot-name.spec.js#L100-L109

By all means, make a PR adding such a test.

**Comment by cdpaiva** [comment]
Hello @jmrunkle, thanks for the reply! 

I wanted to create a test to confirm that names must be different every time they are created. This would be similar to [this test](https://github.com/exercism/javascript/blob/main/exercises/practice/robot-name/robot-name.spec.js#L59-L70) of the JS track.

A test to prove that all names can be generated might take some time to run, since the names are generated randomly. I think it is a good point, but it shouldn't be implemented.
