### ISSUE TITLE
Missing prerequisites for `bird-watcher`

### ISSUE THREAD

**Issue by ynfle** [exercism/java#2058]
A couple issues with `bird-watcher`
1. `hasDayWithoutBirds()` requires for loops or streams, and neither of them are a prerequisite
2. `getToday()` requires an if statement or the ternary operator and neither of them are a prerequisite

**Comment by jmrunkle** [comment]
> 1. `hasDayWithoutBirds()` requires for loops or streams, and neither of them are a prerequisite

This concept exercise is supposed to teach for loops so... yeah. Loops is the concept being taught, not a prerequisite.

> 2. `getToday()` requires an if statement or the ternary operator and neither of them are a prerequisite

The prerequisite here is "supposed" to be covered by `booleans`, but I can see the argument for having it be `conditionals-if` instead. Want to make that PR?

**Comment by ynfle** [comment]
> > 1. `hasDayWithoutBirds()` requires for loops or streams, and neither of them are a prerequisite
> 
> This concept exercise is supposed to teach for loops so... yeah. Loops is the concept being taught, not a prerequisite. 

I'm sorry, I can't believe that I missed that.

> > 2. `getToday()` requires an if statement or the ternary operator and neither of them are a prerequisite
> 
> The prerequisite here is "supposed" to be covered by `booleans`, but I can see the argument for having it be `conditionals-if` instead. Want to make that PR?

An `if` statement or ternary operation is needed, not boolean logic.

I will make a PR.
