### ISSUE TITLE
record support

### ISSUE THREAD

**Issue by 4joke** [exercism/java#2107]
Hello. Do you have any troubles with java record? I use records in my solution for "Queen attack" and it is processing about 9 hours for now. My guess this is related with records, though all tests are green.

**Comment by andrerfcsantos** [comment]
Sorry it took a while to get back to you.

Can you please post your solution here so we can check it?

**Comment by 4joke** [comment]
It's ok now. It worked a few days later.

**Comment by andrerfcsantos** [comment]
Happy to hear!
