### ISSUE TITLE
Verify contents and format of track documentation

### ISSUE THREAD

**Issue by kytrinyx** [exercism/java#213]
Each language track has documentation in the `docs/` directory, which gets included on the site
on each track-specific set of pages under [/languages](http://exercism.io/languages).

We've added some general guidelines about how we'd like the track to be documented in exercism/exercism.io#3315
which can be found at https://github.com/exercism/docs/blob/master/language-tracks/documentation/for-consumers.md

Please take a moment to look through the documentation about documentation, and make sure that
the track is following these guidelines. Pay particularly close attention to **how to use images**
in the markdown files.

Lastly, if you find that the guidelines are confusing or missing important details, then a pull request
would be greatly appreciated.

**Comment by FridaTveit** [comment]
I think the documentation looks okay :) Apart from that the images in the img folder don't appear to be used anywhere...

**Comment by kytrinyx** [comment]
Always happy to delete stuff. I think you're right that the docs look fine.

**Comment by stkent** [comment]
Is that image the one used e.g. here: http://exercism.io/languages?

**Comment by kytrinyx** [comment]
@stkent yepp, that one is used.

I think Frida means this image folder: https://github.com/exercism/java/tree/master/docs/img

**Comment by FridaTveit** [comment]
Yes, that was the folder I meant :)

**Comment by stkent** [comment]
D'oh! Makes sense... PR incoming!

**Comment by stkent** [comment]
I believe this is now complete!
