### ISSUE TITLE
darts: Unnecessary complication of exercise by using method without parameters

### ISSUE THREAD

**Issue by JanB1** [exercism/java#2145]
The exercise "Darts" is categorised in the "Conditionals If" exercises and is categorised as "easy". 

While the exercise itself is indeed easy, the use of a 'score' method without parameters and thus the necessity to write a constructor is making the exercise more complicated to understand than it needs to be.

Especially as other, similar exercises just expect the student to write a method that uses parameters given.

Is there a reason why this simple exercise uses an approach that differs from this?

**Comment by andrerfcsantos** [comment]
I agree we should simplify this.

So the task here is to have the exercise just require static methods instead of requiring the building of a new object and putting a method on it. Anyone is welcome to open a PR with this change.

**Comment by JanB1** [comment]
I think a different approach would be to instead let the user write a method that calculates the score using methods where the x and y position is passed as an argument, instead of pulling it from the object as a field.

The object creation and call of the methods with the proper arguments would more or less stay the same.

See the [bird watcher tests](https://github.com/exercism/java/blob/main/exercises/concept/bird-watcher/src/test/java/BirdWatcherTest.java) for example.

**Comment by andrerfcsantos** [comment]
@JanB1 I see, that works too :)

**Comment by jennylia** [comment]
is anyone working on this issue actively?

**Comment by andrerfcsantos** [comment]
@jennylia I don't think so, feel free to take this.

**Comment by jennylia** [comment]
yea I'll give it a try.

**Comment by jennylia** [comment]
https://github.com/exercism/java/pull/2180/files is my PR. Please also tag me for hacktoberfest thank you very much

**Comment by kerolloz** [comment]
@andrerfcsantos 

This issue should be closed.

**Comment by andrerfcsantos** [comment]
@kerolloz Indeed, thanks for the reminder.
