### ISSUE TITLE
hello-world: remove the reference to `UnsupportedOperationException` in instructions

### ISSUE THREAD

**Issue by andrerfcsantos** [exercism/java#2151]
The instructions for the "Hello World" exercise tell the student to remove an `UnsupportedOperationException`:

https://github.com/exercism/java/blob/9abbe2a744625d698691249714d992fbdc17662c/exercises/practice/hello-world/.docs/instructions.append.md?plain=1#L52-L59

However, currently neither the tests or the solution contain an exception, so these instructions are not relevant anymore and must be removed to reflect the current [stub files](https://github.com/exercism/java/tree/main/exercises/practice/hello-world/src) provided.

**Comment by unfirthman** [comment]
Hi @andrerfcsantos 

If this issue is still open, I'd love to try to tackle it.

**Comment by andrerfcsantos** [comment]
@unfirthman Go for it :)

**Comment by suraj-mandal** [comment]
Hi, is this issue open? I was getting updates of this issue being open, but it is stated that a fix has been merged. Can you close if this issue if the problem has been resolved.

**Comment by ShadowZone** [comment]
I just solved the exercise and the error is still there. Stated UnsupportedOperationException in text but is not found in initial code block

**Comment by andrerfcsantos** [comment]
I'll close this issue, as the main goal of fixing the instructions to not use the exception was achieved.

However, it seems there's a reference to the `UnsupportedOperationException` in the table of contents for the exercise, but I made a separate issue for that #2167

**Comment by andrerfcsantos** [comment]
The table of contents issue is now fixed by #2166 which was already merged.

@ShadowZone If there are other places where the instructions should be updated that I'm not seeing, please feel free to create a new issue or PR.
