### ISSUE TITLE
Secret Handshake exercise should have `Signal` class/enum visible/editable

### ISSUE THREAD

**Issue by artamonovkirill** [exercism/java#2157]
More context: https://exercism-team.slack.com/archives/CATD6MX62/p1661262277270479

For the online editor, it's not clear that the enum is already defined, so students might attempt to redefine it inside `HandshakeCalculator`. That causes deceiving compilation errors.

**Comment by andrerfcsantos** [comment]
Thanks for pointing this out.

The fix here is to add a `files.editor` key in `exercises/practice/secret-handshake/.meta/config.json` containing that extra file - this will make the editor aware of that file and show it in reading mode.

**Comment by artamonovkirill** [comment]
https://github.com/exercism/java/pull/2191
@andrerfcsantos is there any way I can test this change before merging?

**Comment by andrerfcsantos** [comment]
@artamonovkirill Unfortunately, no. I left a comment on the PR.

Thanks for doing this. I noticed this is a problem in a lot of other exercises too - they have extra files but are not declared in either the `files.solution` or `files.editor` key. I've meaning to write a little script to fix instances where this happens, but haven't find the time yet. In the meantime, feel free to create PRs about this for the exercises you are solving.

**Comment by andrerfcsantos** [comment]
It appears for me now 🎉

<img width="526" alt="image" src="https://user-images.githubusercontent.com/6928620/198849949-0da9e429-85fe-4611-979c-b67688ffa658.png">

**Comment by artamonovkirill** [comment]
> @artamonovkirill Unfortunately, no. I left a comment on the PR.
> 
> Thanks for doing this. I noticed this is a problem in a lot of other exercises too - they have extra files but are not declared in either the `files.solution` or `files.editor` key (#2170). I've meaning to write a little script to fix instances where this happens, but haven't find the time yet. In the meantime, feel free to create PRs about this for the exercises you are solving.

@andrerfcsantos I wrote the script and added missing files: https://github.com/exercism/java/pull/2195 😁
