### ISSUE TITLE
Can't run Pythagorean Triplet tests (compilation error)

### ISSUE THREAD

**Issue by Garfax** [exercism/java#2158]
PythagoreanTripletTest.java fails to compile due to duplicate method declarations:

> [ERROR] COMPILATION ERROR : 
[ERROR] /tmp/solution/src/test/java/PythagoreanTripletTest.java:[100,17] method tripletsWhoseSumIs840() is already defined in class PythagoreanTripletTest
[ERROR] /tmp/solution/src/test/java/PythagoreanTripletTest.java:[137,17] method tripletsWhoseSumIs30000() is already defined in class PythagoreanTripletTest

**Comment by AdwitiyaMishra** [comment]
Hi @Garfax, is the issue still available. I would like to work on it.

**Comment by Garfax** [comment]
> Hi @Garfax, is the issue still available. I would like to work on it.

It's not fixed yet. However, there is a mention just above your comment - someone has already created a pull request that is waiting for approval.

**Comment by andrerfcsantos** [comment]
The PR mentioned (#2160) was merged now. This issue should now be solved.
