### ISSUE TITLE
remote-control-competition instructions unclear

### ISSUE THREAD

**Issue by berson-andrew** [exercism/java#2164]
I was mentoring this problem, and the only places where the expected behavior of the drive method was specified were in comments in a code block in the instructions or through reverse engineering the test case. The code block says:
```java
ProductionRemoteControlCar prod = new ProductionRemoteControlCar();
TestTrack.race(prod);
ExperimentalRemoteControlCar exp = new ExperimentalRemoteControlCar();
TestTrack.race(exp);
prod.getDistanceTravelled();
// => 10
exp.getDistanceTravelled();
// => 20
```
Even then, it is only through indirect inference that the desired behavior can be understood.

I think it should be explicitly specified that `ProductionRemoteControlCar.drive()` should travel 10 units and `ExperimentalRemoteControlCar.drive()` should travel 20.

I would be happy to make these changes myself if this issue gets assigned to me.

**Comment by andrerfcsantos** [comment]
@berson-andrew Feel free to make the instructions more clear!

I agree this could use some more clarification.

**Comment by IAmLuisJ** [comment]
I was just looking at this exercise and thought the same, glad it's being worked on :)

One additional note - the HINTS.MD file could use some additional info as well. I like that it links to the Oracle documentation but I think there is an opportunity to add more context to implementing interfaces, and in general more hints for this exercise. 

@berson-andrew would this fall in scope with your enhancements or should I open a separate issue?

**Comment by berson-andrew** [comment]
That is definitely an expansion of scope, but seems reasonable, I'll include better hints in my PR

**Comment by mrbeardy** [comment]
Just chiming in to agree with this also, as I am in the same position and feel like I can't complete the exercise without fudging together a solution.

I feel like the number of tests can definitely be expanded, as at the moment there's far too much work to be done between tests and it's not letting the tests guide the work which is a big part of learning TDD.

**Comment by leitzke-andre** [comment]
Hey there!
I can see that the changes are already implemented and this has been quiet for a while, which indicates there is no further need of changes.
I believe it can be closed, then?

**Comment by sanderploegsma** [comment]
Yes I think you are right, thanks!

**Comment by leitzke-andre** [comment]
Thank you! :smiley:
