### ISSUE TITLE
Add exercises' extra files to files.editor or files.solution

### ISSUE THREAD

**Issue by andrerfcsantos** [exercism/java#2170]
Recently in my mentoring, I noticed that some exercises have some files that are part of the solution (but the student shouldn't modify them) that are not appearing on the online editor and they should. The reason for this is that these extra files are not in the `files.solution` or `files.editor` keys of `.meta/config.json` on each exercise.

An example of this is the [Triangle exercise](https://github.com/exercism/java/tree/main/exercises/practice/triangle). The file [TriangleException.java](https://github.com/exercism/java/blob/main/exercises/practice/triangle/src/main/java/TriangleException.java) is something the student must be aware it exists, although the file shouldn't be modified. This file should then be included in the `files.editor` key of `.meta/config.json` of this exercise just it shows up in the editor, both for students and mentors.

There are other exercises with a similar problem and ideally, we should identify and fix all the exercises that have these extra files that are not being acknowledged in the `files.editor` or `files.solution` keys of `.meta/config.json`.

## Contributing to this issue

If you want to contribute to this issue, comment below your intention!

Even though ideally we should fix this in all exercises that suffer from this issue, PRs that fix this in a single exercise or just a few exercises are welcome.

Some useful links:

- [Exercism docs: Practice exercises](https://exercism.org/docs/building/tracks/practice-exercises)

PS: I imagine it wouldn't be difficult to make a script that tries to identify exercises with this issue and try to fix the `.meta/config.json` manually. The script could read the exercises' folders and check for files that are not in `config.json` and add them to `files.editor` by default. If you create such script, feel free to share it with us and use it to create PR(s).

**Comment by AdarshPrasad02** [comment]
The coding playground could include the collapsible function for the student to view if he/she wants to. This will let them know about the present code beforehand.

**Comment by suraj-mandal** [comment]
@andrerfcsantos Hi, I was able to implement the script doing exactly what you have mentioned. I am creating a pull request in the meantime. Can you check if possible?

**Comment by suraj-mandal** [comment]
Hi, @andrerfcsantos I have created the pull request for the same.

**Comment by andrerfcsantos** [comment]
@suraj-mandal Thanks, added my review there.

**Comment by sanderploegsma** [comment]
I went through both the concept and practice exercises and as of right now it looks like all exercises have their files correctly referenced in `.meta/config.json`.

@andrerfcsantos unless you still want to add a script to automatically add unreferenced exercise files to their respective config files, perhaps this issue can be closed.
