### ISSUE TITLE
Calculator Conumdrum: finish implementation

### ISSUE THREAD

**Issue by jennylia** [exercism/java#2177]
settings.gradle doesn't include calculator conumdrum, it's not on the Java website either. but c# has this path available. Recommend to remove this from Java or add this to the settings.gradle and make it available to the public

**Comment by andrerfcsantos** [comment]
According to the `config.json` of the track, the exercise is marked as work in progress, that's the reason it has a directory, but it's not public facing.

https://github.com/exercism/java/blob/84f99ff672d1f2d600d9d790b2d77de99c68de51/config.json#L86-L97

If the exercise is WIP, means it wasn't finished, so finishing it could be the solution. If you want, feel free to compare the current state of the exercise in the Java track with the one in C# and see what's missing.
