### ISSUE TITLE
Broken links in the contributing file

### ISSUE THREAD

**Issue by zankyr** [exercism/java#2197]
In the [contributing](https://github.com/exercism/java/blob/main/CONTRIBUTING.md) file there are several links which are broken (404).

In [contributing with a minimal setup](https://github.com/exercism/java/blob/main/CONTRIBUTING.md#contributing-with-minimal-setup) section:
1.  [commit messages](https://github.com/exercism/docs/blob/master/contributing/git-basics.md#commit-messages)

In  [Adding a new exercise section](https://github.com/exercism/java/blob/main/CONTRIBUTING.md#adding-a-new-exercise)
1. [general Exercism guide for porting an exercise to a new language](https://github.com/exercism/docs/blob/master/you-can-help/implement-an-exercise-from-specification.md)
2. [here](https://github.com/exercism/docs/blob/master/language-tracks/configuration/exercises.md)

**Comment by andrerfcsantos** [comment]
Thanks for bringing this to our attention.

Feel free to submit a PR for this. Instead of linking to github documents, we should link to [Exercism docs](https://exercism.org/docs). For links that are broken and there is no replacement for them, it is ok to remove them.

**Comment by zankyr** [comment]
@andrerfcsantos I've opened https://github.com/exercism/java/pull/2200 but it still a draft because I want to ask for suggestions.

**Comment by andrerfcsantos** [comment]
Although the docs don't have a section specifically on porting exercises, it does have pages explaining the [parts of a concept exercise](https://exercism.org/docs/building/tracks/concept-exercises) and [parts of a practice exercise](https://exercism.org/docs/building/tracks/practice-exercises). I'd consider this the closest equivalent.
