### ISSUE TITLE
Tradução do codigo

### ISSUE THREAD

**Issue by DevBrunoo** [exercism/java#2198]
Quero traduzir algumas partes do cogido para o meu idioma portugues pelos comentários.

**Comment by kotp** [comment]
This is a request for internationalization, specifically to Portuguese.  And, presumably, an offer to do the work required.

**Comment by kotp** [comment]
Please see https://github.com/exercism/website-copy/issues/1421.

Por favor ese isso https://github.com/exercism/website-copy/issues/1421

**Comment by andrerfcsantos** [comment]
@DevBrunoo Agradecemos a disponibilidade, no entanto neste momento não aceitamos traduções. Ainda não temos forma de traduzir partes do site para outras línguas, embora isso seja algo que esteja planeado. Uma vez que ainda não temos plano de acção de como as traduções irão funcionar, neste momento não aceitamos ofertas de ajuda relativas a isto.

---

To everyone else: just replied thanking for the availability to help, but that we don't take translations at the moment, although it is something on our plans.
