### ISSUE TITLE
Seperate Three Domino Loops Test missing from DominoesTest.java

### ISSUE THREAD

**Issue by smcg468** [exercism/java#2207]
I was looking through the test cases outlined in problem-specifications, specifically the canonical-data json file and noticed that the 'Three seperate-domino loops' test case was not covered in the DominoesTest.java. I checked the C# repository and noticed the test was present there, I therefore have added in the test and will create a pull request for you to review.

Thanks.

**Comment by andrerfcsantos** [comment]
Merged in https://github.com/exercism/java/pull/2209
