### ISSUE TITLE
remote-control-competition test ensureCarsAreComparables not checking for Comparable

### ISSUE THREAD

**Issue by azurekca** [exercism/java#2228]
I may be misunderstanding the requirement but it seems to me that the test `ensureCarsAreComparables` should be checking that `Comparable.class` is assignable from `ProductionRemoteControlCar.class` rather than `RemoteControlCar.class`.

I'd be happy to open a PR to address this.

**Comment by andrerfcsantos** [comment]
@azurekca Sorry for not getting back to you sooner.

This seems like a good idea. If you are still interested, please do open a PR.
