### ISSUE TITLE
bug: wrong params at `practice/darts/src/main/java/Darts.java`

### ISSUE THREAD

**Issue by samyabrata-maji** [exercism/java#2256]
in `practice/darts/src/main/java/Darts.java` the function `score` accepts int values
but, in `practice/darts/src/test/java/Darts.java` at Line no 41, 47, 53 and so on, double values are given to the `score` function.

**Comment by samyabrata-maji** [comment]
I assume the `score(int, int)` function must be `score(double, double)` in `main/java/Darts.java`

**Comment by andrerfcsantos** [comment]
@samyabrata-maji This was fixed by https://github.com/exercism/java/pull/2213. Thanks for reporting.
