### ISSUE TITLE
Bird Watcher - Empty array scenario

### ISSUE THREAD

**Issue by vorenusCoA** [exercism/java#2257]
Hi,

This is the exercise: https://exercism.org/tracks/java/exercises/bird-watcher

One of the general tips of the exercise states that:

> The bird count per day is an array that contains exactly 7 integers.

But there is a test that contemplates an empty array scenario:

``` Java
    @Test
    public void itShouldReturnZeroIfBirdWatcherLastWeekIsEmpty() {
        int[] lastWeekEmpty = new int[0];
        birdWatcher = new BirdWatcher(lastWeekEmpty);
        assertThat(birdWatcher.getToday()).isEqualTo(0);
    }
```

My suggestion is to remove that test.

If testing the exercise against an empty array is desired I would suggest removing the hint and also implement the same case for other methods. But, in my opinion (since this is one of the first exercises), having a pre-condition of an existing array keep thing simple and seems the path to follow.

Please let me know if removing the test sounds good and I will submit a PR.

Thanks.

**Comment by andrerfcsantos** [comment]
@vorenusCoA Thanks for reporting this.

Please feel free to open a PR removing that test.
