### ISSUE TITLE
Submission by CLI example is missing in `hello-world` instructions

### ISSUE THREAD

**Issue by loziniak** [exercism/java#2263]
This line ends with "e.g.", but there is no example:

https://github.com/exercism/java/blob/37dba5fe2a363851bb3243da361d00e8a0aa88dd/exercises/practice/hello-world/.docs/instructions.append.md?plain=1#L79

There is no information what files to submit in Java track, so the example would be very helpful.

**Comment by andrerfcsantos** [comment]
@loziniak Thanks for reporting this.

Are you interested in opening a PR adding an example to those instructions?

**Comment by travis85904** [comment]
done. commit 6d9bef6
