### ISSUE TITLE
complex-numbers: naming inconsistencies

### ISSUE THREAD

**Issue by DWalz** [exercism/java#2317]
I am currently creating method stubs for Exercises and when working on the `compley-numbers` exercise I've noticed an inconsistency in the naming of some methods: The methods are sometimes named after the mathematical operators and sometimes after established function names in programming.

An example of that are the Operators `+` and `-`. `+` is named `add` while `-` is named `minus`.

With the method stubs it will be clear which method is responsible for which action but I still think that the naming convention should be unified for increased clarity.

Personally I like the usage of already established names, so I would propose the following name refactorings:

- `+`: `add` -> `add` (*no change*)
- `-`: `minus` -> `sub`
- `*`: `times` -> `mult` / `mul`
- `/`: `div` -> `div` (*no change*)
- `e^x`: `exponentialOf` -> `exp`

**Comment by sanderploegsma** [comment]
IMO using abbreviated method names like in your proposal is not idiomatic Java, and I believe we should set a correct example for students learning the language.

I agree with your reasoning, but personally I would name them:

- `+`: add
- `-`: subtract
- `*`: multiply
- `/`: divide
- `e^x`: exponentialOf
