### ISSUE TITLE
Update concept exercise tests with task identifiers

### ISSUE THREAD

**Issue by sanderploegsma** [exercism/java#2356]
## Introduction

Exercism's Java test runner recently got updated to support more features of the online editor. One of these features is the ability to show the information of each exercise task in the test result output ([reference](https://exercism.org/docs/building/tooling/test-runners/interface#h-task-id)). The `lasagna` concept exercise has been updated already to make use of these features, and the following screenshot shows the result:

<img width="555" alt="Screenshot 2023-09-19 at 08 23 01" src="https://github.com/exercism/java/assets/1564254/8ca5a60f-5252-4e8f-b95a-1be326375af5">

The goal of this issue is to convert the other concept exercise tests as well.

## Requirements

For each concept exercise:

- Make sure that each test in the test suite is linked to exactly one task in the exercise instructions. Do this by annotating the test with `@Tag("task:X")`, where `X` is the number of that task.
- Add the `@DisplayName` annotation to each test case and provide a human-readable and meaningful name for the test.

This requires the concept exercise to migrate from JUnit 4 to JUnit 5, since the `@Tag` and `@DisplayName` annotations are not supported by JUnit 4.

For reference, [check out the PR updating the `lasagna` concept exercise](https://github.com/exercism/java/pull/2354), which was updated to serve as an example.

## Exercises to be updated

- [x] `annalyns-infiltration`
- [x] `bird-watcher`
- [x] `blackjack`
- [x] `calculator-conundrum`
- [x] `cars-assemble`
- [x] `elons-toy-car`
- [x] `football-match-reports`
- [x] `karls-languages`
- [x] `lasagna`
- [x] `log-levels`
- [x] `need-for-speed`
- [x] `remote-control-competition`
- [x] `salary-calculator`
- [x] `squeaky-clean`
- [x] `wizards-and-warriors`

## Contributing guidelines

Before opening a Pull Request, make sure to check out the contributing guidelines in [CONTRIBUTING.md](https://github.com/exercism/java/blob/main/CONTRIBUTING.md).

When opening a Pull Request for this issue, make sure to reference this issue in its description so that we can keep track of the status.

In case you have any further questions regarding this issue, feel free to ask here.

**Comment by aldotele** [comment]
Hi there, I would like to take care of it! Thanks

**Comment by sanderploegsma** [comment]
Great! I’ll assign it to you.

Feel free to open multiple PRs to tackle the exercises one by one, that also makes it easier to review.

**Comment by sanderploegsma** [comment]
@aldotele thank you for all of your efforts, this really makes the experience of working on concept exercises a lot more pleasant! 😎

**Comment by aldotele** [comment]
@sanderploegsma thank you for your reviews, i'm glad I could help, hope to contribute again to exercism! :)
