### ISSUE TITLE
Implement new practice exercise: `bottle-song`

### ISSUE THREAD

**Issue by sanderploegsma** [exercism/java#2357]
The exercise `bottle-song` has not been implemented yet for the Java track, as it replaces the deprecated `beer-song` exercise  (https://github.com/exercism/problem-specifications/issues/2066).
The description of the exercise can be found in the [problem specification repository](https://github.com/exercism/problem-specifications/tree/main/exercises/bottle-song).

How to implement a new exercise for the Java track is described in detail in [CONTRIBUTING.md](https://github.com/exercism/java/blob/master/CONTRIBUTING.md#adding-a-new-exercise). Please have a look there first before starting working on the exercise.
Also please make sure it is clear that you are currently working on this issue, either by asking to be assigned to it, or by opening an empty PR.

When opening an PR, please reference this issue using any of the [closing keywords](https://help.github.com/en/articles/closing-issues-using-keywords).

If you have had a look at the exercise description and you concluded that the exercise might not be possible to implement in the Java language, please leave a comment and describe the problem.

In case you have any further questions, feel free to ask here.

**Comment by kahgoh** [comment]
I'd be happy to work on this one.

**Comment by sanderploegsma** [comment]
@kahgoh great! I’ll assign it to you.

**Comment by kahgoh** [comment]
Hey @sanderploegsma, I was wondering with `bottle-song` replacing `beer-song`, should I still be generating a UUID for the exercise (as if adding it as a new exercise) or reusing the `beer-song`'s UUID?

**Comment by sanderploegsma** [comment]
Generally uuids should _never_ be reused on Exercism, so definitely generate a new one! 👍
