### ISSUE TITLE
Implement new practice exercise: `state-of-tic-tac-toe`

### ISSUE THREAD

**Issue by sanderploegsma** [exercism/java#2360]
The exercise `state-of-tic-tac-toe` has not been implemented yet for the Java track.
The description of the exercise can be found in the [problem specification repository](https://github.com/exercism/problem-specifications/tree/main/exercises/state-of-tic-tac-toe).

How to implement a new exercise for the Java track is described in detail in [CONTRIBUTING.md](https://github.com/exercism/java/blob/master/CONTRIBUTING.md#adding-a-new-exercise). Please have a look there first before starting working on the exercise.
Also please make sure it is clear that you are currently working on this issue, either by asking to be assigned to it, or by opening an empty PR.

When opening an PR, please reference this issue using any of the [closing keywords](https://help.github.com/en/articles/closing-issues-using-keywords).

If you have had a look at the exercise description and you concluded that the exercise might not be possible to implement in the Java language, please leave a comment and describe the problem.

In case you have any further questions, feel free to ask here.

**Comment by AniketNS** [comment]
Hey @sanderploegsma, can you please assign this issue to me?
I'd love to work on this.

**Comment by sanderploegsma** [comment]
Done, have fun!

**Comment by AniketNS** [comment]
Sure, will be troubling you some times. Cause I'm a beginner.

**Comment by AniketNS** [comment]
Hey, @sanderploegsma is this `state-of-tic-tac-toe` practice exercise built in any other Lanugage(like python, go, c, etc.) track?

**Comment by sanderploegsma** [comment]
Searching code on GitHub on mobile is hard so I was only able to find the PR for the Go track since that was the only one linked to the original PR adding the exercise to the problem specifications.

https://github.com/exercism/go/pull/2284

You can search the Exercism organization on GitHub to see if there are other tracks, hope this one helps already.

**Comment by AniketNS** [comment]
Yeah, it helps @sanderploegsma. Thanks.

**Comment by AniketNS** [comment]
Hey @sanderploegsma, I created the [PR](https://github.com/exercism/java/pull/2607) can you please review that?

**Comment by manumafe98** [comment]
I would love to work on this one @sanderploegsma!
