### ISSUE TITLE
Implement new practice exercise: `killer-sudoku-helper`

### ISSUE THREAD

**Issue by sanderploegsma** [exercism/java#2361]
The exercise `killer-sudoku-helper` has not been implemented yet for the Java track.
The description of the exercise can be found in the [problem specification repository](https://github.com/exercism/problem-specifications/tree/main/exercises/killer-sudoku-helper).

How to implement a new exercise for the Java track is described in detail in [CONTRIBUTING.md](https://github.com/exercism/java/blob/master/CONTRIBUTING.md#adding-a-new-exercise). Please have a look there first before starting working on the exercise.
Also please make sure it is clear that you are currently working on this issue, either by asking to be assigned to it, or by opening an empty PR.

When opening an PR, please reference this issue using any of the [closing keywords](https://help.github.com/en/articles/closing-issues-using-keywords).

If you have had a look at the exercise description and you concluded that the exercise might not be possible to implement in the Java language, please leave a comment and describe the problem.

In case you have any further questions, feel free to ask here.

**Comment by providentapartment** [comment]
The goal of this problem is to check if the given Killer Sudoku board is valid; you don't need to solve the puzzle or provide a solution.

**Comment by ONOFF123** [comment]
Thương hiệu đồ lót ONOFF Underwear được ưa thích hàng đầu tại Việt Nam. Các sản phẩm [đồ lót nam](https://onoff.vn/do-lot-nam.html), đồ lót nữ, quần áo lót, áo thun, tất ... làm từ các chất liệu cao cấp và thiết kế hiện đại. ONOFF giúp mang lại sự thoải mái mỗi ngày cho bạn và gia đình bạn. Giúp bạn vận động dễ dàng, tập thể dục hiệu quả
Name: Công ty cổ phần ONOFF
Address: 121 Phan Đình Phùng, Phường 17, Quận Phú Nhuận, Thành phố Hồ Chí Minh
Hotline: 1800 1100
Website: [onoff.vn](https://onoff.vn/)
Blog: [Blogonoff](https://onoff.vn/blog/)

**Comment by sougat818** [comment]
I'd be happy to work on this one.

**Comment by sanderploegsma** [comment]
Great! I’ll assign it to you.
