### ISSUE TITLE
Update installation instructions to install latest Java LTS version

### ISSUE THREAD

**Issue by sanderploegsma** [exercism/java#2368]
Currently the [installation instructions shown to users](https://exercism.org/docs/tracks/java/installation) tell them to install Java 11. However, active support for Java 11 is going to end soon ([source](https://endoflife.date/java)), so we should probably update the instructions to point to the latest LTS release instead. At the time of writing this is Java 21.

**Comment by sanderploegsma** [comment]
Note: this is probably not a good idea until we support Java 21 in the test runner: https://github.com/exercism/java-test-runner/issues/65

**Comment by JGdevsmx** [comment]
Good joob

**Comment by sanderploegsma** [comment]
The Java test runner has been updated to support Java 21.

**Comment by himanshucip** [comment]
if it's acceptable to proceed with the direct documentation update or if there are specific guidelines or procedures for making such changes in the project. @sanderploegsma

**Comment by sanderploegsma** [comment]
> if it's acceptable to proceed with the direct documentation update or if there are specific guidelines or procedures for making such changes in the project. @sanderploegsma

In general make sure you read the contribution guidelines, both the Exercism guides as well as the track-specific guides are linked in the project’s README. 

Other than that feel free to open a PR addressing this issue. The Java installation instructions on Exercism are sourced from this file: https://github.com/exercism/java/blob/main/docs/INSTALLATION.md
