### ISSUE TITLE
Remove nested test classes from practice exercise `rest-api`

### ISSUE THREAD

**Issue by sanderploegsma** [exercism/java#2539]
Due to a [bug in the Java test runner](https://github.com/exercism/java-test-runner/issues/69) the current tests for the `rest-api` exercise fail to run on Exercism. 
Since this bug is not easily fixed, the best workaround is to refactor the exercise tests into a single class containing all of the test methods, instead of using nested classes. 

## Contribution notes

As always, make sure to follow the [Exercism contributing guidelines](https://exercism.org/docs/building) and the [Java track contributing guidelines](https://github.com/exercism/java/blob/0e1f0088c7fd4580cb7d8f93dd4771743624c802/CONTRIBUTING.md).

Don't hesitate to ask here in case you can't find answers to your questions!

**Comment by Yordaniss** [comment]
@sanderploegsma hey 🙂 

Are the tests for `rest-api` not already in one single class `RestApiTest`? Or do you mean not to use static classes like `UserManagementTest` and move the tests under main class?

**Comment by sanderploegsma** [comment]
> Or do you mean not to use static classes like `UserManagementTest` and move the tests under main class?

Yes, that is what I mean. Apologies if this wasn’t clear from the issue description. I updated it a bit, perhaps now it’s more clear?

**Comment by Yordaniss** [comment]
> > Or do you mean not to use static classes like `UserManagementTest` and move the tests under main class?
> 
> Yes, that is what I mean. Apologies if this wasn’t clear from the issue description. I updated it a bit, perhaps now it’s more clear?
> 
> 

Thanks for an answer. I would like to work than on this issue 🙂

**Comment by sanderploegsma** [comment]
Great, I assigned it to you!
