### ISSUE TITLE
Add concept: `nullability`

### ISSUE THREAD

**Issue by sanderploegsma** [exercism/java#2553]
# Design

## Learning Objectives

- Know of the existence of the `null` literal.
- Know what a `NullPointerException` is and when it is thrown.
- Know how to compare a value to `null`.

## Out of scope

- `java.util.Optional`

## Concepts

- `nullability`

## Prerequisites

- `strings`: strings will be compared to null and basic methods from strings will be called.
- `if-else-statements`: using a conditional statement.

---

The goal of this issue is to add a new concept to the Java track that introduces `nullability`. The corresponding concept exercise can be based on the [Name Badges story](https://exercism.org/docs/building/tracks/stories/nullability-name-badges). We suggest porting the ["Tim From Marketing" exercise from the C# track](https://github.com/exercism/csharp/tree/main/exercises/concept/tim-from-marketing).

Instructions on how to contribute to the Java track and how to implement concept exercises can be found in the [contributing guide](https://github.com/exercism/java/blob/main/CONTRIBUTING.md).

As always, leave a comment here if you want to work on this exercise, and we'll assign it to you. In case you have any further questions, feel free to ask here.

**Comment by smcg468** [comment]
I'd be happy to work on this.

**Comment by sanderploegsma** [comment]
Great! I'll assign you to it.

Make sure to check out the contributing guide in this repository if you haven't already, and feel free to comment here in case you have any questions!
