### ISSUE TITLE
Add concept: `method-overloading`

### ISSUE THREAD

**Issue by sanderploegsma** [exercism/java#2554]
The goal of this issue is to add a new concept to the Java track that introduces `method-overloading`. The corresponding concept exercise can probably be based on the ["Wizards and Warriors 2" exercise from the C# track](https://github.com/exercism/csharp/tree/main/exercises/concept/wizards-and-warriors-2).

Instructions on how to contribute to the Java track and how to implement concept exercises can be found in the [contributing guide](https://github.com/exercism/java/blob/main/CONTRIBUTING.md).

As always, leave a comment here if you want to work on this exercise, and we'll assign it to you. In case you have any further questions, feel free to ask here.

**Comment by sougat818** [comment]
I'd be happy to work on this one.

**Comment by sanderploegsma** [comment]
@sougat818 great, I assigned you to it.
