### ISSUE TITLE
Add concept: `sets`

### ISSUE THREAD

**Issue by sanderploegsma** [exercism/java#2557]
The goal of this issue is to add a new concept to the Java track that introduces `sets`. The corresponding concept exercise can be probably be based on one the following exercises from other tracks:

- [Gotta Snatch 'Em All](https://github.com/exercism/elm/blob/main/exercises/concept/gotta-snatch-em-all/) from the Elm track
- [Ozan's Playlist](https://github.com/exercism/javascript/blob/main/exercises/concept/ozans-playlist/) from the Javascript track

Instructions on how to contribute to the Java track and how to implement concept exercises can be found in the [contributing guide](https://github.com/exercism/java/blob/main/CONTRIBUTING.md).

As always, leave a comment here if you want to work on this exercise, and we'll assign it to you. In case you have any further questions, feel free to ask here.

**Comment by okaram** [comment]
@sanderploegsma I can work on this one, if it's OK ...

**Comment by sanderploegsma** [comment]
Great! I'll assign you to it.

Make sure to check out the contributing guide in this repository if you haven't already, and feel free to comment here in case you have any questions!

**Comment by sanderploegsma** [comment]
After adding the concept, it should be added to both the `practices` and `prerequisites` in the `config.json` for the following practice exercises:

- Custom Set
- Go Counting
- Robot Name
- Saddle Points

**Comment by sanderploegsma** [comment]
@okaram I'm unassigning you from this issue for now so that others can pick it up if they want to. If you still want to contribute please drop a comment and we can assign it back to you!
