### ISSUE TITLE
a animal -> an animal

### ISSUE THREAD

**Issue by RinatMambetov** [exercism/java#2561]
https://github.com/exercism/java/blob/8b8b73da1cd5c2a3e3de2cbe44d2e8de8e7ab279/exercises/concept/wizards-and-warriors/.docs/introduction.md?plain=1#L16

**Comment by sanderploegsma** [comment]
Feel free to open a PR to address this!

**Comment by smicaliz** [comment]
Done! I have created a PR to address this.
