### ISSUE TITLE
formatter->parser

### ISSUE THREAD

**Issue by RinatMambetov** [exercism/java#2597]
https://github.com/exercism/java/blob/e8aa324dc2f4ad868e956bc69bebf2c523c68330/exercises/concept/booking-up-for-beauty/.docs/introduction.md?plain=1#L84

**Comment by sanderploegsma** [comment]
Yup, good catch. Feel free to submit a PR to address this without first opening an issue, by the way!

**Comment by manumafe98** [comment]
Do you guys mind if I create the PR to fix this one? thanks!

**Comment by sanderploegsma** [comment]
@manumafe98 Sure! I'll assign this one to you.
