### ISSUE TITLE
Nucleotide Count unused method

### ISSUE THREAD

**Issue by manumafe98** [exercism/java#2604]
https://github.com/exercism/java/blob/d49ab9248fcd85ec031ced3809dd67adef28c0d5/exercises/practice/nucleotide-count/src/main/java/NucleotideCounter.java#L9

This method is unnecessary for the resolution of the exercise, does not even has tests as well, checking into community solutions seems that no one is using it. 

If you guys decide to delete it I can make a PR!

**Comment by sanderploegsma** [comment]
Good point, having both methods seems a bit pointless.

I would argue that keeping either method is possible. The nice thing about the `count(char)` method is that it doesn't force students to default to using a `Map` for their solution. It would require updating the tests too though, so perhaps keeping the `nucleotideCounts()` method easier.

Feel free to open a PR to address this. I leave the choice of which method to keep up to you!

**Comment by manumafe98** [comment]
Great, probably I would go for the easier approach, but I have another question.

https://github.com/exercism/java/blob/d49ab9248fcd85ec031ced3809dd67adef28c0d5/exercises/practice/nucleotide-count/.meta/src/reference/java/NucleotideCounter.java#L16

This one in the reference should be deleted as well? I was checking the whole directory to avoid making errors

**Comment by sanderploegsma** [comment]
Yes the reference implementation needs to be updated as well.

For practice exercises this file serves as an example of how the exercise could be solved. It's not visible to students or mentors but mainly serves as guidance for maintainers and as a way to run the exercise test suite in CI on this repository.
