### ISSUE TITLE
Allergies exercise

### ISSUE THREAD

**Issue by manumafe98** [exercism/java#2608]
I notice that the allergies exercise has this instructions: [appended instructions](https://github.com/exercism/java/blob/main/exercises/practice/allergies/.docs/instructions.append.md) that seem outdated, the exercise actually has an implementation that you could use.

**Comment by sanderploegsma** [comment]
Good find! Feel free to open a PR to address this.

In fact, _all_ exercises have been provided with a starter implementation over the last years, so any other exercises that still have this same snippet in their docs should be updated as well.
