### ISSUE TITLE
Implementing a concept exercise documentation outdated

### ISSUE THREAD

**Issue by manumafe98** [exercism/java#2622]
implementing a concept exercise [documentation](https://github.com/exercism/java/blob/main/reference/implementing-a-concept-exercise.md) seems to be outdated.

The link ``Java Concept exercises introduction`` leads to a 404, the same with the one in ``Step 3`` and the other lead to archived documentation.

**Comment by sanderploegsma** [comment]
Thank you for pointing this out! The document hasn't been updated in a while and in the mean time a lot has changed on Exercism. I opened a PR to address most of the issues in the document, feel free to leave any thoughts on it if you want!

**Comment by manumafe98** [comment]
This changes look great! When I dig into adding the ``Optionals`` concept, I'll give you a heads up if I find something that could be improved or if it's a bit tricky to grasp. Thanks!
