### ISSUE TITLE
Dominoes java track exercise violates equals x hashcode.

### ISSUE THREAD

**Issue by abmpicoli** [exercism/java#2642]
The code for Domino.java has a violation between equals x hashcode code.

The code for equals accepts rotated tiles: that is , a Domino where left=3 and right=1 equals to a Domino where left=1 and right=3.

However the hashcode is a hash of left,right: this means that you can have a class that equals, and have a different hashcode.

**Comment by sanderploegsma** [comment]
Thanks for pointing this out! You are right of course, and it's definitely something we should address since we should be setting an example.

PRs welcome!

**Comment by abmpicoli** [comment]
Created pull request with the solution https://github.com/exercism/java/pull/2704
