### ISSUE TITLE
Provide Gradle wrapper with each exercise to simplify local development environment

### ISSUE THREAD

**Issue by sanderploegsma** [exercism/java#2655]
Inspired by [this post on the forum](https://forum.exercism.org/t/question-about-the-java-builds-at-the-cli/9284), the process of setting up a local development environment for exercises on the Java track can be simplified by using the Gradle wrapper. This means that students only need to install the JDK in order to work on exercises on their local machine.

In order to support this, each exercise should provide the Gradle wrapper, similar to how it's done in the Kotlin track ([example](https://github.com/exercism/kotlin/tree/main/exercises/practice/hello-world)).

After this is done for all exercises, the public documentation can be updated to:

- No longer instruct to install Gradle locally
- Replace all instructions that use `gradle` to instead use `./gradlew` (or `./gradlew.bat` on Windows).

Additionally, https://github.com/exercism/cli can be updated to use the Gradle wrapper when running `exercism test` on Java exercises.

**Comment by manumafe98** [comment]
Hey @sanderploegsma I would like to give it a try! from I was reading from the [official doc](https://docs.gradle.org/current/userguide/gradle_wrapper.html) should be pretty straight forward, what I need to investigate how to set properly is the ``settings.gradle`` for the exercises itself

**Comment by sanderploegsma** [comment]
> Hey @sanderploegsma I would like to give it a try! from I was reading from the [official doc](https://docs.gradle.org/current/userguide/gradle_wrapper.html) should be pretty straight forward, what I need to investigate how to set properly is the `settings.gradle` for the exercises itself

Oops well I opened a PR while you were writing your comment... 🙈 

As for the `settings.gradle`, I believe it's not required to have one for each exercise, as there are no settings to change for a Java exercise. I know the Kotlin exercises have them but that is mainly to configure the Kotlin Gradle plugin, which we wouldn't use here.

**Comment by manumafe98** [comment]
> Oops well I opened a PR while you were writing your comment... 🙈

no problem!
