### ISSUE TITLE
Gradle wrapper JAR is corrupt

### ISSUE THREAD

**Issue by kahgoh** [exercism/java#2659]
It seems the gradle-wrapper.jar in the repository is corrupt. Here is what I get when I test the JAR file in the repository using zip (I use Arch Linux):

```
efreet practice/pop-count ‹main*› » zip -T gradle/wrapper/gradle-wrapper.jar
        zip warning: expected 33 entries but found 32

zip error: Zip file structure invalid (gradle/wrapper/gradle-wrapper.jar)
```

This is preventing me from running the tests locally:

```
efreet java/squeaky-clean » ./gradlew test                                                                        
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain
```

I had to run `gradle wrapper` to redownload the Gradle JAR file.

**Comment by kahgoh** [comment]
I'd be happy to continue looking into this one.

**Comment by sanderploegsma** [comment]
Oh no, that doesn't sound good... I am able to replicate it on Ubuntu in WSL, so something must have gone wrong. Strange, because I remember testing it and it didn't have issues.

Thanks for opening an issue to report this, I'll have a look as well.
