### ISSUE TITLE
CI test job should exclude deprecated exercises

### ISSUE THREAD

**Issue by sanderploegsma** [exercism/java#2666]
The GitHub Actions workflow that uses the java-test-runner to test all exercises in this repository currently tests _all_ exercise directories, including deprecated exercises. Since [deprecated exercises should remain untouched](https://exercism.org/docs/building/tracks/deprecated-exercises) and the java-test-runner recently dropped support for JUnit 4, the CI build is now failing on these exercises.

To resolve this, the [bin/test-with-test-runner](https://github.com/exercism/java/blob/main/bin/test-with-test-runner) script should be updated to skip deprecated exercises. Deprecated exercises are marked with `"status": "deprecated"` in the track's `config.json`, so it should be fairly simple to determine which exercises are deprecated by using `jq`.

**Comment by manumafe98** [comment]
I will work on this one, I think I have an idea on how to do it!
