### ISSUE TITLE
#48in24: Add approaches to Parallel Letter Frequency

### ISSUE THREAD

**Issue by sanderploegsma** [exercism/java#2710]
The Parallel Letter Frequency exercise on the Java track [is being featured in the #48in24 challenge](https://exercism.org/challenges/48in24/implementation_status), which means that we expect an influx of students attempting to solve it during that week.

It would be nice if the exercise contains some more content by that time.
One example of this is to add one or more [approaches](https://exercism.org/docs/building/tracks/approaches) to the exercise, so that students can dive in deeper after they have solved it themselves.

For an example of how approaches have been added to other practice exercises, take a look at [the approaches for the Leap exercise](https://github.com/exercism/java/tree/main/exercises/practice/leap/.approaches).

**Comment by masiljangajji** [comment]
Hello @sanderploegsma 
Are you still looking for a contributor?
If so, I would like to contribute to this.

**Comment by kahgoh** [comment]
Hi @masiljangajji! Feel free to go for it! I've assigned to you now.

**Comment by masiljangajji** [comment]
Hi @kahgoh , could you review this for me? I’m planning to talk to my friends about open source contribution this Friday, so I’d appreciate it if you could take a look!

**Comment by kahgoh** [comment]
Hi @masiljangajji, thanks for working on this one! Your PR is next on my list and I should get to it later today.
