### ISSUE TITLE
#48in24: Add approaches to Knapsack

### ISSUE THREAD

**Issue by sanderploegsma** [exercism/java#2712]
The Knapsack exercise on the Java track [is being featured in the #48in24 challenge](https://exercism.org/challenges/48in24/implementation_status), which means that we expect an influx of students attempting to solve it during that week.

It would be nice if the exercise contains some more content by that time.
One example of this is to add one or more [approaches](https://exercism.org/docs/building/tracks/approaches) to the exercise, so that students can dive in deeper after they have solved it themselves.

For an example of how approaches have been added to other practice exercises, take a look at [the approaches for the Leap exercise](https://github.com/exercism/java/tree/main/exercises/practice/leap/.approaches).

**Comment by kahgoh** [comment]
I'd like to work on this one. 

The two main approaches I am currently aware of:
- A recursive approach like [this one](https://exercism.org/tracks/java/exercises/knapsack/solutions/smith494) or [this one](https://exercism.org/tracks/java/exercises/knapsack/solutions/pldupont)
- Iterative approach, building a table of max values, like [this one](https://exercism.org/tracks/java/exercises/knapsack/solutions/glennj)

**Comment by sanderploegsma** [comment]
Great, go ahead!
