### ISSUE TITLE
Collatz Conjecture: Test case should be added to check for more than one method call

### ISSUE THREAD

**Issue by Mauricio-MdS** [exercism/java#2775]
A possible solution to this exercise would be to use recursion. However, a likely error in using recursion would be to place the steps as a field instead of a local variable of the method. This way, the steps would possibly not be reset on each new method call. There is no test case for this mistake.

**Comment by sanderploegsma** [comment]
I'm not 100% sure I understand your concern @Mauricio-MdS without an example solution highlighting the problem you're describing. From what I gather though, I don't think the aim of this exercise (or most of the other exercises for that matter) is to care about details like these. The challenge is to correctly implement the Collatz Conjecture _algorithm_, quite probably by using recursion. All that matters is that the solution provides the correct answer given some input. I think that is adequately covered by the existing test cases.
