### ISSUE TITLE
Mentoring signup url broken

### ISSUE THREAD

**Issue by bruincub** [exercism/java#2786]
The mentoring url [http://mentoring.exercism.io/](http://mentoring.exercism.io/) in the appended instructions leads to a URL that does not exist. It also is using the http protocol instead of https.

https://github.com/exercism/java/blob/main/exercises/practice/hello-world/.docs/instructions.append.md

**Comment by manumafe98** [comment]
Thanks for opening an issue @bruincub ! You're right!
