### ISSUE TITLE
Sync yacht tests

### ISSUE THREAD

**Issue by kahgoh** [exercism/java#2862]
This task is to check the tests against those in the [problem specification](https://github.com/exercism/problem-specifications/blob/main/exercises/yacht/canonical-data.json) and update accordingly.

**Comment by jagdish-15** [comment]
Hello @kahgoh!

Upon review, I found that the tests were already in sync. However, there was a minor discrepancy in the documentation that needed to be updated. I have raised a PR to sync the changes accordingly.

**Comment by jagdish-15** [comment]
However, there are several other exercises that are not in sync, as shown in the screenshot below:

![Screenshot 2024-11-16 010257](https://github.com/user-attachments/assets/daaea131-7205-41d5-a581-0c23cd964b78)

Would you like me to proceed with raising a PR to sync them all? Let me know if I have your go-ahead.

**Comment by kahgoh** [comment]
Thanks for looking into syncing Yacht! For some reason I had thought there was a test or two missing, but it appears to be all there when I looked again.

In regards to syncing the other tests, is it just the instructions and introduction Markdown files that need updating for them all? If so, feel free to sync them all under one PR. (Note, I am suggesting using _just one_ PR to sync them all to avoid having to raise and go through many PRs).

**Comment by jagdish-15** [comment]
Thanks for confirming about Yacht! Regarding the other exercises, there are indeed some tests that need to be synced as well, in addition to the instructions and introduction Markdown files. I'll take care of raising a PR to sync everything.

And don’t worry, I wouldn’t create separate PRs for each exercise — I'll handle it all in a single PR to keep the process efficient and streamlined. 😊

Thanks for the suggestion!

**Comment by jagdish-15** [comment]
Shouldn't we mark this issue as resolved since we have verified that the tests for the Yacht exercise are already in sync, and updates for the other exercises are currently in progress?

**Comment by kahgoh** [comment]
Yeah, I think you're right because the original purpose was to just check the Yacht exercise, but that's done now. Closing this issue.
