### ISSUE TITLE
Binary Search Exercise: Fix test name

### ISSUE THREAD

**Issue by akmaekki** [exercism/java#2881]
The test name `aValueLargerThanTheArraysSmallestValueIsNotFound` should be changed to `aValueLargerThanTheArraysLargestValueIsNotFound`, because the value 13 to be tested is larger than the arrays largest value 11.

**Comment by kahgoh** [comment]
@akmaekki good spotting! You're right, the test is named incorrectly. Would you like to fix the test's name? You would only need to update the test in [exercises/practice/binary-search/src/test/java/BinarySearchTest.java](https://github.com/exercism/java/blob/main/exercises/practice/binary-search/src/test/java/BinarySearchTest.java).

**Comment by akmaekki** [comment]
@kahgoh 
Sure, will fix it.
