### ISSUE TITLE
Check out the "New Language Track" repo and look for neat features to bring into the Java track

### ISSUE THREAD

**Issue by jtigger** [exercism/java#320]
Katrina and Peter have pulled together a pretty sweet starter kit for new tracks.

But hey, just because we're Java, doesn't mean we're not hip, right?  right?!?!  :)

Take a look at this repo... especially the scripts and `.md`s... there are a number of little tools and GitHub configuration that we might enjoy here...

https://github.com/exercism/request-new-language-track

**Comment by stkent** [comment]
We're looking pretty good here. I can't see much new apart from the relocation of the README insert. Java has also moved its README contents elsewhere.

**Comment by stkent** [comment]
@kytrinyx is this change required? I don't remember a tracking issue.

https://github.com/exercism/request-new-language-track/commit/4355efe6b9c8950f5e2ef016ef150313c69664e4

**Comment by stkent** [comment]
(Specifically the docs -> config portion.)

**Comment by kytrinyx** [comment]
You have the template: https://github.com/exercism/java/blob/master/config/exercise_readme.go.tmpl

Other than that (and moving the insert) I can't think of anything.

**Comment by stkent** [comment]
I think #742 takes care of the change needed here.

**Comment by stkent** [comment]
#742 merged; closing this!
