### ISSUE TITLE
difference-of-squares: should methods return double instead of int?

### ISSUE THREAD

**Issue by shawnHartsell** [exercism/java#331]
when doing this exercise, I noticed that the test fixture expects that the return value of the 
```computeSquareOfSumTo```, ```computeSumOfSquaresTo```,  and ```betweenSquareOfSumAndSumOfSquaresTo``` to be an int. Should these return a ```double``` instead?

For example, running ```Difference.computeSumOfSquaresTo(Interger.MAX_VALUE)``` will cause an overflow.

Would be happy to submit a patch as well as an additional test for this.

**Comment by shawnHartsell** [comment]
as a reference, here's the implementation I'm using: http://exercism.io/submissions/cb914b009bac4dc1b35eae721d709300

**Comment by jtigger** [comment]
... also avoids an annoying cast when using `Math.pow()` (for those inclined). ;)

For those using a functional approach, `DoubleStream` does not share the convenience methods `#range()` and `#rangeClosed()`.  This can invite such practitioners to go beyond such convenience methods and teach/remind/invoke the notion of turning an infinite stream into a finite one with `#limit()`.  Would that be a feature?

**Comment by shawnHartsell** [comment]
It's funny you mentioned the ```Math.pow``` cast. That was actually one of my first attempts, but then realized that making an explicit cast could cause a runtime exception.

I think having to use ```limit``` is an added bonus as well. I actually learned about that in a later exercise. It could also be a good way to learn about casting between types.

My main concern was that the methods should return ```double``` so that calculations could be made on any int. As it stands now, the function can only be ran on a subset of them, which makes it less useful.

**Comment by jtigger** [comment]
Personally, I'm liking the little extra adventures that can come from this adjustment: nudging the practitioner into using a different number type as the consequences of that add value, IMO.

Anyone else want to weigh in? @exercism/java

**Comment by stkent** [comment]
I like the change; might it be worth adding a test case that necessitates the double return type also (if there isn't one already)? Could be a good upstream add also?

**Comment by jtigger** [comment]
"upstream add" as in PR to x-common?

**Comment by stkent** [comment]
Yes indeed!

**Comment by jtigger** [comment]
@shawnHartsell looks like we have rough consensus.  "Normally," I'd close this issue and create a brand-fresh one with a clear objective.  However, you suggested you might hit the work of this, as is.

Does that offer still stand? :)

**Comment by shawnHartsell** [comment]
Hey @jtigger , sorry for the late reply, I just started a new gig. I would def be up for making a PR for this :)

**Comment by stkent** [comment]
See discussion in #652 for issue resolution.
