### ISSUE TITLE
Rework the "About the Java Track" page to be more *enticing*

### ISSUE THREAD

**Issue by jtigger** [exercism/java#347]
The introduction page to the Java track (http://exercism.io/languages/java/about) immediately dives into language-nerd soup and inadvertently elbows out any enticement to the other two cohorts on Exercism: the Early Programmer and the Craftsperson.

Please rewrite this page (source: https://github.com/exercism/xjava/blob/master/docs/ABOUT.md) so that:
1. the introductory text is short, sweet, accessible to all, and sparks a desire to learn more about the language (see guidance in [Writing Track Documentation]).(https://github.com/exercism/exercism.io/blob/master/docs/writing-track-documentation.md).
1. feel free to include some more linguistic candy but do that at the bottom of the description.
1. it clarifies the issue identified in #406.
----
_edit: included comment about odd reference to "dependencies"._

**Comment by RhuanKrum** [comment]
Hi! I just opened a pull request about this rework task.

Please, feel free to suggest changes or improvements. 
Looking forward to contribute to more content here! Thanks!

**Comment by FridaTveit** [comment]
Fixed in PR #959. Thanks @RhuanKrum! :)
