### ISSUE TITLE
Direct would-be contributors to the "good first patch" backlog in "Contributing to Java on Exercism"

### ISSUE THREAD

**Issue by jtigger** [exercism/java#349]
Please update the [Contributing to Java on Exercism](http://exercism.io/languages/java/contribute) to suggest if the would-be contributors has never submitted a PR to an open source project before that they start with [the good first patch backlog](https://github.com/exercism/xjava/labels/good%20first%20patch).

**Comment by stkent** [comment]
Pointer: https://github.com/exercism/exercism.io/blob/6271d86e8c7486eb35074587c8bdba95425c0e38/app/views/languages/_contribute.erb

**Comment by Smarticles101** [comment]
This can be closed now

**Comment by FridaTveit** [comment]
Thanks @Smarticles101! :)

**Comment by stkent** [comment]
Nice! I thought this was going to be a lot more involved :)
