### ISSUE TITLE
bob: extract common setup

### ISSUE THREAD

**Issue by jtigger** [exercism/java#364]
In the `bob` exercise test suite, a single instance of `Bob` is created for all test methods.  This presumes there is no state; there is no need to make that assumption.

Please extract the construction of `Bob` to a [`setUp()`](http://junit.sourceforge.net/javadoc/org/junit/Before.html) method.

**Comment by saylerb** [comment]
I'm looking to contribute my first patch. Can you assign this to me?

**Comment by FridaTveit** [comment]
You can just start working on it if you like :) As long as you've commented on here other people will know not to pick it up :)

**Comment by jtigger** [comment]
Agreed with @FridaTveit.  Also: https://github.com/exercism/xjava/issues/343#issuecomment-287791015.
