### ISSUE TITLE
hamming: introduce use of @Rule

### ISSUE THREAD

**Issue by jtigger** [exercism/java#369]
After #142, the exercise `hamming` is now the first to use the JUnit `@Rule` feature.  This feature is often not intuitive to those new-to-the-framework.

Please:
1. include a `HINT.md` file that describes the `@Rule` feature as succinctly and clearly as possible.
1. include a comment right about the use of `@Rule` that points the practitioner to JUnit documentation specifically about this feature (see [QueenAttackCalculatorTest](https://github.com/exercism/xjava/blob/master/exercises/queen-attack/src/test/java/QueenAttackCalculatorTest.java#L11) for inspiration).
1. Remove the inline comments that (re-)explain `@Rule` from tests that appear in exercises later in the track

**Comment by stkent** [comment]
Should that read "is _now_ the first"?
