### ISSUE TITLE
Clarification of the sentence on implementation dependencies in the Java "about" page

### ISSUE THREAD

**Issue by kotp** [exercism/java#406]
@travisfw commented on [Mon Mar 06 2017](https://github.com/exercism/exercism.io/issues/3396)

The [about page for Java](http://exercism.io/languages/java/about ) says "It has been specifically designed to have as few implementation dependencies as possible" and links to [a page about "implementation dependencies" with regards to Netbeans](https://www.java-tips.org/other-api-tips-100035/60-netbeans/1025-what-is-an-implementation-dependency-and-whathowwhen-should-i-use-one.html ). I have been programming with Java since 2003 and for a year of that used Netbeans, and I have never encountered the feature described on java-tips.org. Java 9 will introduce a *module* concept which seems similar design-wise to the *OpenIDE* modules described there, but I'm not sure what the relationship between the two is (I suspect this Netbeans feature influenced the design of Java 9 modules, and may have even served to prototype that design, but I'm speculating). In any case, it's an inappropriate link for an introduction to what Java is about.

Regardless of the confusing link, I don't know what the sentence about implementation dependencies is trying to communicate. Can it be clarified?

---

@kotp commented on [Mon Mar 06 2017](https://github.com/exercism/exercism.io/issues/3396#issuecomment-284312429)

Thank you @travisfw for opening this issue.  Do you have the time to make an improvement of this paragraph?  Either removal, or clarification if that can be determined?

---

@tejasbubane commented on [Mon Mar 06 2017](https://github.com/exercism/exercism.io/issues/3396#issuecomment-284312879)

@travisfw [This](https://github.com/exercism/xjava/blob/master/docs/ABOUT.md) is the file you want to change.

---

@kytrinyx commented on [Tue Mar 07 2017](https://github.com/exercism/exercism.io/issues/3396#issuecomment-284929382)

/cc @exercism/java 

---

@kytrinyx commented on [Thu Mar 30 2017](https://github.com/exercism/exercism.io/issues/3396#issuecomment-290481039)

This issue should be in the https://github.com/exercism/xjava repository to get tracked by the right folks.

**Comment by jtigger** [comment]
Thanks @travisfw for bringing this up.  Thanks, @kotp for moving this in our space.

This is an excellent additional point to #347.  I'll add the reference.

**Comment by FridaTveit** [comment]
I have the following suggestions:
- We remove the link but keep the sentence as it is.
- We replace the link with [this one](https://askubuntu.com/questions/361741/what-are-dependencies) which more generally talks about what dependencies are.
- We remove the sentence with the link altogether.

What do you think @exercism/java?

**Comment by stkent** [comment]
> We remove the sentence with the link altogether.

gets my vote.

**Comment by Smarticles101** [comment]
I agree with @stkent. Removing the sentence sounds like a good idea

**Comment by FridaTveit** [comment]
Okay, will do that then :)
