### ISSUE TITLE
Mentoring Guides for Exercises in Java

### ISSUE THREAD

**Issue by jtigger** [exercism/java#451]
Dear @exercism/java,

So, I've recently jumped back into mentoring the Java track.  In doing so, I crafted [a discussion guide](https://docs.google.com/document/d/1ov3ng-GrcA0XGYGHIcKIgk0ql0K-eNujdiR49xbLd64/edit#) for my own use.  It got me thinking...

... would it be useful/good idea/advisable/great if we came up with some discussion guides for a set of exercises?  Perhaps if it were only made available to folks who clearly want to be mentors...?

This would seriously lower the barrier for people to comment and participate.

I've been able to make a dent in the second exercise in the track: `rna-transcription`: http://exercism.io/stats/java

Thoughts?

**Comment by stkent** [comment]
I think that as a mentoring tool, the guide you have written is great, and a bunch of the content could be common across exercises! Is there any way to embed that content within the discussion page as it currently stands?

Here are my personal thoughts atm:

- Is there harm in making those notes available to everyone who completes the exercise immediately, as a set of prompts to think about? That way they benefit without the track relying on tons of manual participation, which doesn't always scale well. (For the same reason I think it might be worth exposing the example solutions for comparison purposes, but that's a separate issue).
- Given that Exercism's whole experience is in the process of being overhauled, I'm leery of sinking time into aspects of that experience that feel quite likely to change.
- Personally, I rarely have the time to dedicate to tackling the overwhelming task of sifting through submissions. Maybe in the future participants could be required to opt their solutions in to the discussion pool, which would (1) vastly reduce the backlog, and (2) ensure that mentors are able to focus their efforts where discussion is actively desired.

**Comment by jtigger** [comment]
> Is there harm in making those notes available to everyone who completes the exercise immediately, as a set of prompts to think about? That way they benefit without the track relying on tons of manual participation, which doesn't always scale well.

Yeah, there are no secrets in there and no need to by coy. :)  ... and at least there would be _some_ prompt(s) to explore further.  That said, it would move away, not towards the kind of experience we'd love to see flourish on Exercism: a lively discussion about crafting code.

I love where you're going with the different modes.  Why couldn't those prompts be something that people could turn on or off? :)  ... and toggle whether a given exercise is "private" or "public" ?

> I rarely have the time to dedicate to tackling the overwhelming task of sifting through submissions.

Yeah, I absolutely relate.  I tried this experiment where I only review the one exercise.  Right now: `rna-transcription`.  It's at the very front of the track, so that's the most number of submissions.  With the discussion guide, and a little formula, I crank through them in 10-30 minutes:

My formula:
> _(Greeting by name)_
> _(Something I like about their submission)_
> _(one of the prompts/suggestions from the discussion guide; sometimes, with adjustments to contextualize)_

It's still very personalized, but I've managed to "automate" the truly repeated parts.  I named each of the parts in the "discussion guide" in terms of what I see in their submission which makes it easy/fast to find the snippet.   The rest of my energies are spent in relating.

For reinforcing feedback, I've been watching [the stats page](http://exercism.io/stats/java) at _just_ this exercise (`rna-transcription`) get better and better, each day. :)  Between _that_ and some of the genuine feedback from individuals who are thanking me, I've been properly motivated. :)

**Comment by Smarticles101** [comment]
@exercism/java I'd like for us to be able to close this. Is there any reason to keep it open? The information here might be valuable to mentors, where is a good place to link to it where mentors will see it?

**Comment by FridaTveit** [comment]
I'm happy with closing it 🙂  Not sure where we can link to it so that mentors can see... Any ideas @sjwarner-bp? 🙂

**Comment by sjwarner-bp** [comment]
I'm not too sure exactly where would be a good place for this. Maybe a link out from one of our documentation pages?

As far as I am aware there isn't any documentation specifically for track mentors (though that would be nice)! :slightly_smiling_face:

**Comment by FridaTveit** [comment]
@sjwarner-bp there are these [mentoring notes](https://github.com/exercism/mentors/tree/master/tracks/java), not sure if they're used much though?

**Comment by Smarticles101** [comment]
@FridaTveit that's an interesting thought, I haven't seen those before. That might be a good spot to put these

**Comment by jmrunkle** [comment]
The first mentor notes that are officially integrated into the website were added in October 2018. I think we can safely close this.
