### ISSUE TITLE
Remove starter implementations for exercises with positions 21 or greater

### ISSUE THREAD

**Issue by stkent** [exercism/java#554]
Ref.: https://github.com/exercism/xjava/blob/master/POLICIES.md#starter-implementations

**Comment by redshirt4** [comment]
Are the exercise positions (>= 21) referring to this ordered list? http://exercism.io/languages/java/exercises

**Comment by Smarticles101** [comment]
No, they refer to the [config](https://github.com/exercism/java/blob/master/config.json) file

**Comment by stkent** [comment]
(Those two lists are generally in sync; the website might lag behind the config file by a few days is all :))

**Comment by Smarticles101** [comment]
Lol yeah I just realized that the site follows the order in the config file.

**Comment by Smarticles101** [comment]
Closed by #681
