### ISSUE TITLE
Add probot config to close out stale support issues

### ISSUE THREAD

**Issue by stkent** [exercism/java#610]
See #555 for discussion.

Once probot/stale#22 is resolved, add a probot configuration file in the java repo that sweeps for issues marked with the https://github.com/exercism/xjava/labels/support label _only_.

**Comment by Smarticles101** [comment]
@sjwarner-bp I would agree, I'm okay with closing this. I personally don't feel like we need probot. Let's see what @FridaTveit has to say.

**Comment by FridaTveit** [comment]
I agree, happy with closing this 🙂
