### ISSUE TITLE
nucleotide-count: sync sample solution and test class names

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#697]
As far as I'm aware it's best practice to name a test class after the class it's testing. So if you're testing `SomeClass` you would name the test class `SomeClassTest`. We usually do this but in nucleotide-count we have `NucleotideTest` which test the class `DNA`. I suggest we:
1. Rename `NucleotideTest` to `DNATest` (or possibly `Dna` and `DnaTest` to make it more readable?)
2. Add this preference to the POLICIES doc

Do you agree with this @exercism/java?

**Comment by Smarticles101** [comment]
What if we renamed the `DNA` class to `Nucleotide`? Normally, the solution class is named after the exercise. Other than that, I think adding what you said to the POLICIES doc is a great idea.

**Comment by stkent** [comment]
+1 `NucleotideCount`, or even `NucleotideCounter`.
+1 a new entry under the 'best practices' section of the policies.
