### ISSUE TITLE
Test documentation references a nonexistant GETTING_STARTED.md file.

### ISSUE THREAD

**Issue by terminaltraces** [exercism/java#698]
The current documentation for running Java tests (http://exercism.io/languages/java/tests) references a exercises/hello-word/GETTING_STARTED.md file that currently doesn't exist. 

This line could either be removed, or changed to reference the exercises/hello-world/TUTORIAL.md file, depending on particular preferences!

**Comment by stkent** [comment]
Great spot; thanks for reporting!
