### ISSUE TITLE
binary-search-tree: add angle brackets when calling constructor

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#700]
Since the `BST` class uses generics it should be constructed using angle brackets. For example:
```
BST<Integer> binarySearchTree = new BST<>();
```
This is done sometimes in `BSTTest` but not always. It should be done everywhere where a `BST` object is created in `BSTTest`.

**Comment by stkent** [comment]
(Reminder that this exercise is pending review for use of generics per https://github.com/exercism/java/issues/230 also.)

**Comment by ribhav-pahuja** [comment]
@FridaTveit , I would like to contribute to this.

**Comment by Smarticles101** [comment]
@ribhav-pahuja Feel free to tackle this! 👍

**Comment by FridaTveit** [comment]
Yes, like @Smarticles101 said, feel free to work on it :)

**Comment by FridaTveit** [comment]
Fixed in PR #842. Thanks @szielinski! :) 

I'm sorry if you were still working on it @ribhav-pahuja. I forgot about your comment when merging the PR, sorry. There should be lots of other `good-first-patch` issues you can work on though. Let me know if you have any problems finding any :)
