### ISSUE TITLE
pig-latin: simplify example implementation

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#718]
There are a few simplifications that can be made to `PigLatinTranslator` in `/pig-latin/src/example`:

1. `Arrays.asList().stream()` can be simplified to `Arrays.stream()`
2. `.map(x -> translateWord(x))` can be simplified to use a method reference: `.map(this::translateWord)`
3. All the public class variables can be made [private](https://docs.oracle.com/javase/tutorial/java/javaOO/accesscontrol.html) 
4. The class and the `translate` method can be made [package private](https://docs.oracle.com/javase/tutorial/java/javaOO/accesscontrol.html) (by just removing the public modifier)

**Comment by riktimmondal** [comment]
Is it still open?I would to fix those things.

**Comment by stkent** [comment]
It looks like @matthewstyler has already worked on this issue, but if you're looking for other issues to tackle that are a similar level of difficulty, check out the [good first patch](https://github.com/exercism/java/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+patch%22) list :)
