### ISSUE TITLE
series: simplify example implementation

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#723]
The example implementation for `Series` can be simplified by:
- `Arrays.asList(string.split((""))).stream()` can just be `Arrays.stream(string.split(("")))`
- `.map(digit -> Integer.parseInt(digit))` can be simplified by using a method reference:
`.map(Integer::parseInt)`
- The class and its methods can be made [package private](https://docs.oracle.com/javase/tutorial/java/javaOO/accesscontrol.html) (by removing the `public` access modifier)

**Comment by m-a-ge** [comment]
@FridaTveit, 
PR #727 has been created.

Please add your feedback and suggestions for my future contributions

**Comment by FridaTveit** [comment]
Fixed in PR #727. Thanks @m-a-ge! :)
