### ISSUE TITLE
Commented tests in TwoferTest Class and possibly one case missing

### ISSUE THREAD

**Issue by m-a-ge** [exercism/java#728]
While doing  `two-fer` I've noticed that two positive test cases were commented (not sure why).
```java
    @Ignore("Remove to run test")
    @Test
    public void aNameGiven() {
        String input = "Alice";
        String expected = "One for Alice, one for me.";

        assertEquals(expected, twofer.twofer(input));
    }

    @Ignore("Remove to run test")
    @Test
    public void anotherNameGiven() {
        String input = "Bob";
        String expected = "One for Bob, one for me.";

        assertEquals(expected, twofer.twofer(input));
    }
```

I guess they shouldn't be ignored by default.

Moreover, I suggest adding additional one (but not sure if it complies with task description):
```java
    @Test
    public void emptyStringGiven() {
        String input = "";
        String expected = "One for you, one for me.";

        assertEquals(expected, twofer.twofer(input) );
    }
```

**Comment by Smarticles101** [comment]
The readme for the exercise describes the usage of the `@Ignore` annotations. They're basically there so that people can work on one test case at a time.

The additional test case you suggested isn't in the [canonical data for the exercise](https://github.com/exercism/problem-specifications/blob/master/exercises/two-fer/canonical-data.json) but it seems like a good idea to me. Thoughts @exercism/java ?

**Comment by stkent** [comment]
Interesting, as currently written this depends on how we interpret 'no name':

> If no name is given, the result should be "One for you, one for me."

Is a blank string 'no name', or is `null` the only way to represent 'no name'? 🤔 

Could be worth asking in `problem-specifications`, though i'd be surprised if we get a clear consensus on the above :)

**Comment by Smarticles101** [comment]
The old hello-world exercise used `null` and/or a blank string to represent no name. The fact that this is different in two-fer suggests that this may have been changed on purpose. Might require some digging to find out.

**Comment by m-a-ge** [comment]
@Smarticles101, thanks for clarification!

The issue can be closed then.

But in the real life you are expected to deal with empty Strings too :mask:

**Comment by stkent** [comment]
[Slightly more specific reference](https://github.com/exercism/problem-specifications/issues/290#issuecomment-230727326):

> Also agreed that if the language can differentiate between empty string and nil, it should probably treat the empty string as a name.

**Comment by stkent** [comment]
Might still be worth adding a blank string test to the Java track even though it's not captured in the canonical data (since it wouldn't make sense for all languages in the canonical data).

**Comment by m-a-ge** [comment]
It's your call, I can create PR if you want and mark this test as with `@Ignore("Remove to run test")`

**Comment by stkent** [comment]
I think that'd be a good addition, so yes, please! I'd add it as the last test so it's separated from the 'canonical' tests.

**Comment by m-a-ge** [comment]
Sure, will do later today when I get back home

**Comment by m-a-ge** [comment]
@stkent, PR #733 has been created, please review 👨‍💻
