### ISSUE TITLE
rna-transcription: Tests miss edge case for invalid input

### ISSUE THREAD

**Issue by McEileen** [exercism/java#730]
[Feedback on my initial submission](http://exercism.io/submissions/ba4be59781d14eae8daa7f658574bcbf) made me realize the RNA transcription exercise has no tests for the edge case of invalid input.  Other language tracks have tests for this edge case, and so does [the canonical data] (https://github.com/exercism/problem-specifications/blob/master/exercises/rna-transcription/canonical-data.json) for this exercise.  

Addendum: I can open a pull request with tests for the invalid input edge case, but I'm not sure why those tests from the canonical data weren't already included?  I don't think this change requires a change to the broader exercism curriculum, since it seems to be a small discrepancy between the Java track and the broader exercism curriculum.

**Comment by m-a-ge** [comment]
I guess it would be a good idea to stick to `canonical-data.json` and update java tests

**Comment by stkent** [comment]
Just for some context: the Java track does not generate tests based on the canonical data, so over time it's quite possible/typical that our tests fall out of sync with the canonical data. That's where maintainers and contributors come in! Your input based on completing an exercise and discovering it to be out of date is most welcome.

If you'd like to tackle a pull request to update the tests, that would be fabulous. If you do so, I'd recommend adding a version comment to the top of the test file - that's a new practice we've adopted recently to make it clear(er) when an exercise was last updated to match the canonical data. See [list-ops](https://github.com/exercism/java/blob/master/exercises/list-ops/src/test/java/ListOpsTest.java#L10-L12) for an example.
