### ISSUE TITLE
Fix track configuration

### ISSUE THREAD

**Issue by stkent** [exercism/java#743]
v3.3.0 of `configlet` reports:

```
$ configlet lint .
-> An implementation for '.idea' was found, but config.json does not reference this exercise.
-> An implementation for '.gradle' was found, but config.json does not reference this exercise.
-> The implementation for '.idea' is missing an example solution.
-> The implementation for '.gradle' is missing an example solution.
-> The implementation for '.gradle' is missing a test suite.
```

We should investigate these warnings.

**Comment by Smarticles101** [comment]
This could be fixed with the `ignored` key in config.json, however, support for that was removed. Ref. #633 exercism/meta#3

**Comment by stkent** [comment]
I wonder if configlet could be updated to respect the .gitignore

**Comment by stkent** [comment]
Ref.: https://github.com/exercism/configlet/issues/108

**Comment by FridaTveit** [comment]
Looks like a PR has been opened to fix this: https://github.com/exercism/configlet/pull/115. So hopefully it should be fixed soon 🙂

**Comment by sjwarner-bp** [comment]
https://github.com/exercism/configlet/pull/115 has been merged :tada: 

That closes this issue :slightly_smiling_face:
