### ISSUE TITLE
difference-of-squares: improve test names

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#753]
In `DifferenceOfSquaresCalculatorTest` all the test names are of the form `testSquareOfSum1` and `testSumOfSquares5`. These names would be more readable as `testSquareOfSumUpToOne` and `testSumOfSquaresUpToFive`.

Having the number spelled out doesn't matter too much. I think it makes it a bit more readable, but that's just my opinion :) Adding `UpTo` definitely makes it more clear what the test is testing though so that's the most important change.

**Comment by balachandarsv** [comment]
May I take this up? @FridaTveit

**Comment by FridaTveit** [comment]
Sure, go for it @balachandarsv! :)

**Comment by FridaTveit** [comment]
Fixed by PR #794, thanks @balachandarsv! :)
