### ISSUE TITLE
Update local dev instructions to note jq dependency

### ISSUE THREAD

**Issue by stkent** [exercism/java#769]
When I try to run the journey test locally, it fails because I don't have `jq` installed.

My guess is that this used to be installed automatically, and that this is no longer true since the test restructuring (cc @Smarticles101 for verification).

We should update the CONTRIBUTING.md file in light of this change.

**Comment by Smarticles101** [comment]
afaik `jq` still needed to be installed before running the journey test before all the changes came.

**Comment by stkent** [comment]
Ah, I must have removed it inadvertently then! Still a worthy documentation add in that case :)

**Comment by mohanarpit** [comment]
Hey, I'm new to the world of contributing to OSS. Would you like me to make an edit to the CONTRIBUTING.md file to include the instructions that jq & ruby need to be installed for a local setup?

**Comment by FridaTveit** [comment]
Hi, thanks for wanting to contribute to open source! :)

Yes, it would be great if you could add something saying `jq` and `ruby` need to be installed for a complete local setup (in the [complete local setup section](https://github.com/exercism/java/blob/master/CONTRIBUTING.md#advanced-complete-local-setup) of the CONTRIBUTING.md document) :) Does that make sense? Let me know if you have any more questions! :)
