### ISSUE TITLE
SpringComponentFinderStrategy: support Spring Meta-Annotation facility

### ISSUE THREAD

**Issue by mishraanmol** [exercism/java#771]
We annotate our spring services and repositories with custom annotations like
`@Target(ElementType.TYPE)
@Service
public @interface MyService {
}`
Do you support this in SpringComponentFinderStrategy?
If not, please take this as a feature request ;-)

**Comment by stkent** [comment]
My guess is that you accidentally opened this issue in the wrong repository! Since the question is not relevant here, I'm going to close it :)
