### ISSUE TITLE
GitHub API Rate Limit

### ISSUE THREAD

**Issue by Smarticles101** [exercism/java#772]
Sometimes, the journey test on travis-ci will fail to only test against the files changed because the rate limit has been exceeded.

```json
{
  "message": "API rate limit exceeded for 52.54.31.11. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

**Comment by stkent** [comment]
@Smarticles101 any ideas for this one?

**Comment by Smarticles101** [comment]
Perhaps we could clone `master` and get the `diff` between `master` and the branch the build is on? That's the only idea I have other than actually authenticating with github's api

**Comment by m-a-ge** [comment]
I've faced the same problem while creating issues for Python track. The goal was to create over 70 issues, but after 35-40 created issues I've started getting this response

Didn't research much, but it's annoying

**Comment by Smarticles101** [comment]
Has anyone looked into this since? I think a good option at this point would be to pull master inside the travis environment (rather than using the github api) to get a diff.

**Comment by FridaTveit** [comment]
No, I haven't looked into it. However, with the changes to the journey-test script, the builds are now really fast. So I think it would be fine to keep everything as it is. It means some more tests will run every time we run into this issue, but it shouldn't really matter with the builds being faster anyway 🙂 What do you think @Smarticles101, @sjwarner-bp? 🙂

**Comment by sjwarner-bp** [comment]
There hasn't been too much pain around this for a little while now I think, and with our super-fast builds now I think I am happy for everything around there to remain the same for the moment :slightly_smiling_face:

**Comment by Smarticles101** [comment]
@FridaTveit since I've been out of the loop for a while, I'll check in on the journey-test script to become more familiar with recent changes. Glancing at the [travis](https://travis-ci.org/exercism/java/pull_requests) page, some PRs are still taking quite a long time. Such as #1506 which went over 30 minutes when it should have just ran the two-fer test I believe.
