### ISSUE TITLE
saddle-points: unhelpful error message

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#778]
When running the saddle-points tests you don't get a very descriptive error message (unless I'm doing something wrong). The error message I get is something along the lines of:

`expected:<MatrixCoordinate@1f> but was:<MatrixCoordinate@0`

Which isn't much help in finding out what you've done wrong. 

To improve this we could iterate over the sets and compare each point with a more detailed error message e.g.

`"Expected row to be " + expected.getRow() + " and it was " + actual.getRow()
                + ". Expected column to be " + expected.getCol() + " and it was " + actual.getCol() + ".";`

What do you think @exercism/java?

**Comment by Smarticles101** [comment]
Great idea. Another possible fix would be to implement a `toString` method for `MatrixCoordinate`

**Comment by FridaTveit** [comment]
Great idea, that would be much neater and gives a very clear error message! I'll open a PR to implement `toString` for `MatrixCoordinate` :)
