### ISSUE TITLE
bob: add topics

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#792]
As part of the update to the exercism website, we want to add topics to each exercise. This should be topics that will most likely be relevant to the exercise even though you might be able to solve it without encountering that topic. There is a [list of topics](https://github.com/exercism/problem-specifications/blob/master/TOPICS.txt) used across all exercism tracks but you can add track specific ones as well if needed.

See issue #523 for a discussion about adding topics. There are also some exercises (e.g. hello-world and two-fer) that already have topics so you can look at them as examples. The topics need to be added to the entry for the relevant exercise in `config.json`.

**Comment by spmvanmierlo** [comment]
Can I contribute? How do I start? :)

**Comment by FridaTveit** [comment]
Sure, that would be great! :) See my comment on issue #793 for an explanation on how to start :) Let me know if you have any further questions :)

**Comment by FridaTveit** [comment]
Fixed in PR #795. Thanks @spmvanmierlo! :)
