### ISSUE TITLE
house: add topics

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#793]
As part of the update to the exercism website, we want to add topics to each exercise. This should be topics that will most likely be relevant to the exercise even though you might be able to solve it without encountering that topic. There is a [list of topics](https://github.com/exercism/problem-specifications/blob/master/TOPICS.txt) used across all exercism tracks but you can add track specific ones as well if needed.

See issue #523 for a discussion about adding topics. There are also some exercises (e.g. hello-world and two-fer) that already have topics so you can look at them as examples. The topics need to be added to the entry for the relevant exercise in `config.json`.

**Comment by kapilaNR** [comment]
Hi i would like to help this issue. how can i contribute to this.

**Comment by FridaTveit** [comment]
Great @kapilaNR! :) For generally advice about contributing to exercism see [this guide](https://github.com/exercism/docs/tree/master/contributing-to-language-tracks). For general advice about contributing to this track see [this guide](https://github.com/exercism/java/blob/master/CONTRIBUTING.md).

Specifically for this issue you would need to [fork this repository](https://help.github.com/articles/fork-a-repo/), make your changes, commit and push them to a branch on your fork and then [open a pull request](https://help.github.com/articles/creating-a-pull-request/) :) 

The changes you need to make is to go to the `config.json` file which contains some [information about each exercise](https://github.com/exercism/docs/blob/master/language-tracks/configuration/exercises.md). Find the exercise you want to change (`house`) and change the `topics` entry from `null` to an array of topics. See the entry for `two-fer` or `hello-world` for an example . You can choose topics from the [list of topics](https://github.com/exercism/problem-specifications/blob/master/TOPICS.txt). To help you choose topics that are relevant to the exercise you can look at the [test suite](https://github.com/exercism/java/blob/master/exercises/house/src/test/java/HouseTest.java) and [example implementation](https://github.com/exercism/java/blob/master/exercises/house/.meta/src/reference/java/House.java) of the exercise.

Does that make sense? Let me know if you have any more questions :)

**Comment by kapilaNR** [comment]
Thank you @FridaTveit i'll proceed with this.

**Comment by FridaTveit** [comment]
@kapilaNR are you still working on this? Or is it free for other people to work on? :)

**Comment by FridaTveit** [comment]
I think we can say this is free for people to work on :)
