### ISSUE TITLE
Triangle: test and readme conflict

### ISSUE THREAD

**Issue by lbesaw** [exercism/java#799]
In the "Triangle" challenge on the Java track, there is a comment in the "Note" section of the readme that reads "For a shape to be a triangle at all, all sides have to be of length > 0, and the sum of the lengths of any two sides must be greater than or equal to the length of the third side." 

This contradicts the test where a Triangle of sides 2, 2, and 4 are supposed to return an exception.

**Comment by FridaTveit** [comment]
Good spot @lbesaw, thanks for bringing it to our attention. I agree that the README and the tests should not contradict each other like this. The [canonical data]() metions this case:
> Pursuant to discussion in #202, we have decided NOT to test triangles 
> where all side lengths are positive but a + b = c. e.g:               
> (2, 4, 2, Isosceles), (1, 3, 4, Scalene).                             
> It's true that the triangle inequality admits such triangles.These    
> triangles have zero area, however.                                
> They're degenerate triangles with all three vertices collinear.

So I suggest we should change the test to, e.g. 2, 2, and 3. I don't mind if we change the README or not. thoughts @exercism/java, @lbesaw?

**Comment by jackattack24** [comment]
I would say we should change the test to something like 2, 2, and 5 so that it does violate the triangle inequality. (2, 2, and 3 is a valid isosceles triangle)

Or maybe we could edit the README and tests to add degenerate as a triangle type. The Dig Deeper section of the README already mentions this as something for the user to try on their own though, so maybe just changing the test would be better.

**Comment by FridaTveit** [comment]
Sure, changing that test to 2, 2 and 5 sounds like a great plan :)

I think adding a degenerate type would also be good. The canonical data says each language track can deal with the degenerate triangles in whatever way best suits their language, and I think adding a degenerate type would suit the Java exercise very well. Great suggestion @jackattack24! :) If we do that then we also need to remove the "Dig Deeper" section from the README.

Do you agree with this approach @exercism/java?

**Comment by jackattack24** [comment]
Okay, great @FridaTveit! I can work on either change, but I'll wait for further feedback on the issue first.

**Comment by Smarticles101** [comment]
I like the idea of adding a degenerate type @FridaTveit :)

**Comment by FridaTveit** [comment]
I think this issue has become very dependent on the outcome of issue #800, so I'll close this one and we can keep discussing it in issue #800 if that's okay :)
