### ISSUE TITLE
nucleotide-count: add topics

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#808]
As part of the update to the exercism website, we want to add topics to each exercise. This should be topics that will most likely be relevant to the exercise even though you might be able to solve it without encountering that topic. There is a [list of topics](https://github.com/exercism/problem-specifications/blob/master/TOPICS.txt) used across all exercism tracks but you can add track specific ones as well if needed.

See issue #523 for a discussion about adding topics. There are also some exercises (e.g. hello-world and two-fer) that already have topics so you can look at them as examples. The topics need to be added to the entry for the relevant exercise in `config.json`.

**Comment by sjwarner-bp** [comment]
I think I'll try this one, if it is still up for grabs. I'll try just doing one to familiarise myself with the process and make sure I am doing it right, then afterwards I'll do a few, if that is ok?

**Comment by sjwarner-bp** [comment]
I have just submitted the PR - thank you @FridaTveit, I did submit it to the wrong place originally! :smiley:

**Comment by FridaTveit** [comment]
Fixed in PR #820. Thanks @sjwarner-bp! :)

**Comment by sjwarner-bp** [comment]
Thanks for letting me help out @FridaTveit !

**Comment by FridaTveit** [comment]
No problem, thanks for wanting to help! :)
