### ISSUE TITLE
kindergarten-garden: add topics

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#853]
As part of the update to the exercism website, we want to add topics to each exercise. This should be topics that will most likely be relevant to the exercise even though you might be able to solve it without encountering that topic. There is a [list of topics](https://github.com/exercism/problem-specifications/blob/master/TOPICS.txt) used across all exercism tracks but you can add track specific ones as well if needed.

See issue #523 for a discussion about adding topics. There are also some exercises (e.g. hello-world and two-fer) that already have topics so you can look at them as examples. The topics need to be added to the entry for the relevant exercise in `config.json`.

Please comment on this issue or reference it in your pull request (using #issue-number) if you're going to be working on it. If you put "fixes #issue-number" in the pull request description then it will also automatically close this issue when the pull request gets merged :)

**Comment by mhdsmr2** [comment]
Do I have to add topics to exercises with `null` topics (in `config.json`)? Is that what I have to do?

**Comment by FridaTveit** [comment]
You have to add topics to the exercise with slug `kindergarten-garden` in `config.json`. It should currently have `topics` set to `null` :) Does that make sense?

**Comment by mhdsmr2** [comment]
I got it. Thanks!
I am working on it now.

**Comment by FridaTveit** [comment]
Great :)

**Comment by mhdsmr2** [comment]
Do I have to create a new branch?

**Comment by mhdsmr2** [comment]
Done!
Please merge it with the main repo.
Thanks.

**Comment by FridaTveit** [comment]
You need to [open a pull request](https://help.github.com/articles/creating-a-pull-request/) so that we can review it and then merge it once we're happy with it :)

**Comment by FridaTveit** [comment]
Let me know if you need any help with that :)

**Comment by FridaTveit** [comment]
And yes, it would be preferable if you do the work on a branch on your fork :)

**Comment by FridaTveit** [comment]
I see now that you have opened a pull request. It would be great if you could link to this issue in the description, and especially if you put "fixes #853" in the description since that automatically closes this issue when the PR is merged :)

**Comment by mhdsmr2** [comment]
Okay.

**Comment by FridaTveit** [comment]
Thanks! :)

**Comment by mhdsmr2** [comment]
When will this pull request will be merged?

**Comment by FridaTveit** [comment]
You need to address my comments before I can merge it. First it needs to be reivewed and approved, only then can it be merged.

**Comment by mhdsmr2** [comment]
Okay.
