### ISSUE TITLE
Sanitise eclipse settings from exercises

### ISSUE THREAD

**Issue by wolf99** [exercism/java#935]
For this of us not using eclipse, the eclipse settings and project files in some exercises (eg Luhn)  cause IDE's to spit out reams of errors. I notice that not all the exercises suffer this so these items are obviously required. Can we remove them from all the exercises that contain them?

**Comment by stkent** [comment]
Could you please point me to the exact location of such a file? Having a hard time locating in within `luhn`. Thanks!

**Comment by wolf99** [comment]
Hmm, now I check the repo itself I see these aren't part of the exercise. Unsure if this is what I downloaded as part of the exercise or if it got added in the meantime.
Not sure why VS Code would add eclipse settings only to then complain about them though.
Travelling at the moment so can't test this properly. Will do so when I have proper access again and update here.

**Comment by stkent** [comment]
Awesome, no rush, let us know what you find whenever you get a chance! 🔍

**Comment by wolf99** [comment]
Apologies - it is actually the IDE! 😬 Hadn't realised but possibly the Java plugin for VS Code is adding these during some types of actions.

**Comment by stkent** [comment]
No worries; glad you got to the bottom of it!
