### ISSUE TITLE
luhn: Add test enforcing that non-digit characters are invalid

### ISSUE THREAD

**Issue by rstockbridge** [exercism/java#972]
I discovered that my solution to luhn (http://exercism.io/submissions/05a450216e9d4fc5965831a58760efe8) passed all the tests even if I didn't check that all digits excluding spaces were non-numeric. There are two reasons for this:

- I used `Character.getNumericValue()` to parse the string, and that function still returns numeric output for non-digits
- The tests checking that symbols and punctuation are invalid passed simply because the mathematical calculation using the numeric output from `Character.getNumericValue()` produces values that are not multiples of 10. 

I propose adding the following test to require checking if digits are non-numeric:

```
public void testThatStringContainingSymbolsIsInvalid2() {
     assertFalse(luhnValidator.isValid("34&"));
}
```
Without the check, the string `"34&"` evaluates to 10 since `Character.getNumericValue('&')` = -1 and so `isValid()` will return true, failing the test.

**Comment by stkent** [comment]
Specifically, you're saying that if you replace

```java
if (numberWithoutSpaces.length() == 1 || !numberWithoutSpaces.matches("[0-9]+")) {
    return false;
}
```

by

```java
if (numberWithoutSpaces.length() == 1) {
    return false;
}
```

 in the solution you linked to, then all existing tests continue to pass but the new test you describe fails?

**Comment by rstockbridge** [comment]
Correct!

**Comment by stkent** [comment]
We should definitely patch this in the Java track.

We should also socialize it in problem-specifications; though I doubt it makes sense to add this exact test case to the canonical data, it might be worth adding a warning comment (for other track maintainers).

**Comment by LodrKumquat** [comment]
I see that a test with candidate String `"85&"` has been added in response to the raised by @rstockbridge issue, although they suggested it to be `"34&"`. I discovered that test with `"85&"` doesn't fail if I use `Character.digit()` without following check for `-1`. For the reference see solution https://exercism.org/tracks/java/exercises/luhn/solutions/tentativeTentacle. However the initially suggested `"34&"` testing value does cause for the test to fail.

**Comment by eduardoPeniche** [comment]
Any string containing `"&"` will fail or pass depending on the sum of the other digits if it reaches the sum loop.

Excercise says _"Spaces are allowed in the input, but they should be stripped before checking. All other non-digit characters are disallowed."_

Why dont just validate the string with regex at the beggining? If it matches a non-digit or `length <= 1`, return `false`.

```java
if (!candidate.matches("^[\\d ]*$")) return false;
String numbers = candidate.replaceAll("\\s", "");
```
