### ISSUE TITLE
difference-of-squares: Add starter implemention

### ISSUE THREAD

**Issue by rstockbridge** [exercism/java#975]
difference-of-squares is missing a starter DifferenceOfSquaresCalculator.java file.

**Comment by stkent** [comment]
(and it _should_ have one, per https://github.com/exercism/java/blob/master/POLICIES.md#starter-implementations)

**Comment by FridaTveit** [comment]
I think it does have starter implementation: https://github.com/exercism/java/blob/master/exercises/sum-of-multiples/src/main/java/SumOfMultiples.java?

**Comment by stkent** [comment]
I think this was actually for `difference-of-squares`!

**Comment by FridaTveit** [comment]
I see! Then I agree, it should have starter implementation :)
