### ISSUE TITLE
anagram: replace Arrays.asList with Collections.singletonList

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#981]
In [the anagram tests](https://github.com/exercism/java/blob/master/exercises/anagram/src/test/java/AnagramTest.java) there are several instances where `Arrays.asList` is used to construct a list with only one element. Since the list only has one element `Collections.singletonList` should be used instead to save memory. For example:
`assertTrue(detector.match(Arrays.asList("eagle")).isEmpty());`
should be changed to
`assertTrue(detector.match(Collections.singletonList("eagle")).isEmpty());`

**Comment by jonnynabors** [comment]
Taking a stab at this:
https://github.com/exercism/java/pull/1005

**Comment by stkent** [comment]
Closed in #1005
