### ISSUE TITLE
atbash-cipher: improve reference solution

### ISSUE THREAD

**Issue by FridaTveit** [exercism/java#983]
In [the atbash-cipher reference solution](https://github.com/exercism/java/blob/master/exercises/atbash-cipher/.meta/src/reference/java/Atbash.java) `+=` is used to append to a string in a loop. For appending to strings in a loop it's better to use a [StringBuilder](https://docs.oracle.com/javase/8/docs/api/java/lang/StringBuilder.html). This is because by using `+=` to append strings you are creating a new string every time since strings are [immutable](https://www.mkyong.com/java/java-mutable-and-immutable-objects/). A `StringBuilder` is mutable, so it doesn't have the same problem. Therefore a `StringBuilder` should be used in the `encode`, `decode` and `stripInvalidCharacters` methods in the reference solution.

In addition, all the `public` class and method [access modifiers](https://docs.oracle.com/javase/tutorial/java/javaOO/accesscontrol.html) in reference solution can be changed to `package private` (which is the default therefore the access modifier can be left out). For example, `public class Atbash {` should be changed to `class Atbash {`.

We do this since it's best practice to restrict access to a class and its methods as much as possible (see our [POLICIES doc](https://github.com/exercism/java/blob/master/POLICIES.md#adhere-to-best-practices) for more information).

**Comment by stkent** [comment]
Closed in #987
